algolia/api-clients-automation

generators/src/main/java/com/algolia/codegen/AlgoliaJavaGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaJavaScriptGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaPhpGenerator.java
generators/src/main/java/com/algolia/codegen/Utils.java
templates/java/api.mustache
templates/java/model.mustache
templates/javascript/clients/algoliasearch/builds/browser.mustache
templates/javascript/clients/algoliasearch/builds/models.mustache
templates/javascript/clients/algoliasearch/builds/node.mustache
templates/javascript/clients/api-single.mustache
templates/javascript/clients/client/builds/browser.mustache
templates/javascript/clients/client/builds/node.mustache
templates/javascript/clients/client/model/clientMethodProps.mustache
templates/javascript/clients/client/model/modelBarrel.mustache
templates/javascript/clients/model.mustache
templates/php/ApiException.mustache
templates/php/ConfigWithRegion.mustache
templates/php/Configuration.mustache
templates/php/ModelInterface.mustache
templates/php/ObjectSerializer.mustache
templates/php/api.mustache
templates/php/client_config.mustache
templates/php/model.mustache
website/docs/contributing/add-new-language.md

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/APIC-583
Sets the generation notice banner at the top of every files, feel free to recommend a better syntax/sentence.
Generated code :D

fix(clients): add generation banner to generated files

---

.eslintignore
.github/workflows/renovate.yml
.github/workflows/scheduled-release.yml
renovate.json

Maybe fix renovate regex, and add manual trigger for the `renovate` workflow

chore(deps): fix renovate and manual trigger

---

README.md
SECURITY.md

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/APIC-586
Update README format and content
[Preview](https://github.com/algolia/api-clients-automation/blob/b4a6efbf6041088b3c3af86a1b8bea035f852108/README.md)

chore: update README

---

.github/workflows/check.yml
renovate.json

In #532 the regex for `package.mustache` and `.yarnrc.yml` are too broad and detect things that don't have versions,
this should help renovate to find only real deps.

chore(deps): strict regex for package.json and yarn

---

specs/search/paths/synonyms/searchSynonyms.yml
tests/CTS/methods/requests/search/searchSynonyms.json

`query` is a body parameter.
CI :D

fix(specs): wrong parameters for `searchSynonyms`

---

clients/algoliasearch-client-java-2/algoliasearch-core/src/main/java/com/algolia/ApiClient.java
clients/algoliasearch-client-java-2/algoliasearch-core/src/main/java/com/algolia/utils/JSONBuilder.java
clients/algoliasearch-client-javascript/bundlesize.config.json
clients/algoliasearch-client-javascript/packages/client-common/src/createEchoRequester.ts
clients/algoliasearch-client-javascript/packages/client-common/src/transporter/createTransporter.ts
clients/algoliasearch-client-javascript/packages/client-common/src/transporter/helpers.ts
clients/algoliasearch-client-javascript/packages/client-common/src/types/Requester.ts
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/src/echoRequester.ts
clients/algoliasearch-client-javascript/packages/requester-node-http/src/echoRequester.ts
clients/algoliasearch-client-php/lib/RequestOptions/RequestOptionsFactory.php
clients/algoliasearch-client-php/lib/RetryStrategy/ApiWrapper.php
generators/src/main/java/com/algolia/codegen/cts/tests/TestsRequest.java
playground/javascript/node/search.ts
templates/java/api.mustache
templates/java/tests/requests/requests.mustache
templates/javascript/clients/api-single.mustache
templates/php/api.mustache
tests/output/java/src/test/java/com/algolia/EchoInterceptor.java
tests/output/javascript/yarn.lock
website/docs/contributing/testing/common-test-suite.md

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-321
The issue was discovered in https://github.com/algolia/api-clients-automation/pull/823, but I've moved the fix for the clients here.
The goal of this PR is to assert the body of each requests in the CTS even when we don't expect to have one.
On some `POST` requests, the body can be optional (e.g. `browse`), but needs to be a valid JSON object, when no body is expected at all (e.g. `clearAllSynonyms`), an empty string is considered as valid. ~In any case, an empty object (`'{}'`) is considered as valid.~ Some endpoints **do not expect a body at all**, so we need to move that logic at the method level since it can't be factorized.
1. Calling the `browse` method with only an `indexName` throws an empty body error
2. Calling the …

fix(clients): make POST body related to the endpoint, assert body in tests

---

.github/workflows/check.yml
clients/algoliasearch-client-javascript/packages/client-common/src/transporter/createTransporter.ts
clients/algoliasearch-client-javascript/packages/client-common/src/types/Requester.ts
clients/algoliasearch-client-javascript/packages/client-common/src/types/Transporter.ts
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/jest.config.ts
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/src/__tests__/browser-xhr-requester.test.ts
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/tsconfig.json
clients/algoliasearch-client-javascript/packages/requester-node-http/jest.config.ts
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/src/__tests__/node-http-requester.test.ts
clients/algoliasearch-client-javascript/packages/requester-node-http/tsconfig.json
clients/algoliasearch-client-javascript/yarn.lock

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/APIC-588
The goal of this PR is to import requester related tests implemented in v4 to ensure we did not broke it when refactoring.
Changes in this PR:
- Import requester tests from v4, they are 1:1 the same, except some syntax changes
- I've kept the server logic in the test files, but it will be moved at the monorepo level later to be able to do similar tests on the CTS
- Some of those tests should also disappear once we have the e2e CTS in place, but can be done in parallel
- Fix wrong requester.send signature that was made compliant for the `echoRequester`
- Add some type definition + re-use types
Ensure body is correct in POST and DELETE methods
- Done in https://github.com/algolia/api-clients-automation/pull/849
CI :D

fix(javascript): ensure requesters work as in v4

---

.github/actions/restore-artifacts/action.yml
.github/workflows/check.yml
clients/README.md
clients/algoliasearch-client-javascript/base.rollup.config.js
clients/algoliasearch-client-javascript/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/index.ts
clients/algoliasearch-client-javascript/packages/requester-fetch/jest.config.ts
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/src/__tests__/fetch-requester.test.ts
clients/algoliasearch-client-javascript/packages/requester-fetch/src/createFetchRequester.ts
clients/algoliasearch-client-javascript/packages/requester-fetch/tsconfig.json
clients/algoliasearch-client-javascript/packages/requester-node-http/src/__tests__/node-http-requester.test.ts
clients/algoliasearch-client-javascript/tests/utils.ts
clients/algoliasearch-client-javascript/yarn.lock
config/generation.config.js
scripts/common.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/APIC-572
Import `fetch` requester from the community implementation: https://github.com/algolia/algoliasearch-client-javascript/pull/1411
Only changes that were added from the first implementation are:
- Use ms for timeouts
- Allow overriding default `requesterOptions`
I've also moved the test utils to their own folder as it was becoming redundant
CI :D

feat(javascript): add `requester-fetch`

---

.github/workflows/check.yml

We don't always generate/build all clients, therefore we can't run `bundlesize` on every runs. I've changed the condition to only run on prepare release PRs for now, and will try to find a conditional way. Ticket added here: https://algolia.atlassian.net/browse/APIC-596
CI :D

fix(ci): only run size check on release

---

.github/actions/restore-artifacts/action.yml
.github/workflows/check.yml
scripts/ci/githubActions/createMatrix.ts
scripts/ci/githubActions/types.ts

Follow up of https://github.com/algolia/api-clients-automation/pull/869
The CTS runs everything present in the client CTS folder, as our CI only run tasks for clients that have changed, we need to:
1. delete every tests present
2. generate tests for clients that have changed
3. store tests of clients that have changed
CI :D

fix(ci): make CTS only run generated tests

---

specs/recommend/common/schemas/RecommendationsResponse.yml
specs/search/common/schemas/SearchResponse.yml
specs/search/paths/search/searchSingleIndex.yml
tests/CTS/methods/requests/search/searchSingleIndex.json

- The `required` field for `hits` was at the wrong spot
- `hits` is required in a `SearchResponse`, but also a `RecommendationsResponse`
- The `facets` returned are a `Record<string, Record<string, number>>`
- All parameters of `searchParams` are optional, therefore we don't need to make it required.
CI :D

fix(specs): make `hits` required, `facets` count as an integer, `searchParams` as optional

---

clients/algoliasearch-client-javascript/packages/requester-node-http/src/__tests__/node-http-requester.test.ts
clients/algoliasearch-client-javascript/packages/requester-node-http/src/createHttpRequester.ts

I discovered during the Crawler implementation that it was already possible in v4 to override those options, but was not introduced here.
CI :D

feat(javascript): allow providing options for node requester

---

templates/javascript/clients/algoliasearch/builds/imports.mustache
templates/javascript/clients/algoliasearch/builds/models.mustache
templates/javascript/clients/api-single.mustache

Sub `algoliasearch` client's type are not exposed, which can be useful in complex implementations like in the Crawler. It also help to differentiate which client does what.
CI :D

fix(javascript): expose sub `algoliasearch` client's type

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.1 -> **`prerelease` _(e.g. 5.0.0-alpha.2)_**
- java: 4.4.0-SNAPSHOT -> **`patch` _(e.g. 4.4.1-SNAPSHOT)_**
- php: 4.0.0-alpha.6 -> **`prerelease` _(e.g. 4.0.0-alpha.7)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- fix(ci): make CTS only run generated tests (#871)
- fix(ci): remove size check on CI …

chore: prepare release 2022-07-27

---

clients/algoliasearch-client-javascript/packages/client-common/src/types/CreateClient.ts
templates/javascript/clients/algoliasearch/builds/browser.mustache
templates/javascript/clients/algoliasearch/builds/imports.mustache
templates/javascript/clients/algoliasearch/builds/initClients.mustache
templates/javascript/clients/algoliasearch/builds/models.mustache
templates/javascript/clients/algoliasearch/builds/node.mustache
templates/javascript/clients/client/builds/browser.mustache
templates/javascript/clients/client/builds/imports.mustache
templates/javascript/clients/client/builds/node.mustache

`algoliasearch` should provide as much options as the other clients.
I've also updated the names to be a bit more descriptive.
CI :D

fix(javascript): provide more options to `algoliasearch`

---

clients/algoliasearch-client-php/composer.json
clients/algoliasearch-client-php/lib/Algolia.php
clients/algoliasearch-client-php/lib/Http/CurlHttpClient.php
config/generation.config.js
templates/php/composer.mustache

🎟 JIRA Ticket: APIC-600
OpenAPI default generated client introduced Guzzle as a dependency in the composer file, which is different from the current PHP client where this library is just suggested.
The goal of this PR is to mimic the current behaviour where Guzzle is suggested and where the logic fallbacks on a custom HTTP Client in case Guzzle is not installed on the project.
(PR also contains a fix on the Husky exclusion pattern)
- CI / playground

feat(php): Restore Guzzle as a suggestion

---

clients/algoliasearch-client-javascript/packages/algoliasearch/__tests__/algoliasearch.test.ts
templates/javascript/clients/api-single.mustache

Those two properties were missing from the root of the client, which introduced unwanted breaking change.
Those properties were already present in v4, I've just imported it here.
CI :D

fix(javascript): expose `clearCache` and `appId`

---

specs/common/responses/common.yml
specs/search/paths/keys/common/schemas.yml
specs/search/paths/keys/key.yml
specs/search/paths/keys/keys.yml
specs/search/paths/objects/common/schemas.yml
specs/search/paths/objects/getObjects.yml
specs/search/paths/objects/multipleBatch.yml
specs/search/paths/objects/partialUpdate.yml
templates/java/api.mustache
templates/javascript/clients/client/api/helpers.mustache
templates/javascript/clients/client/model/clientMethodProps.mustache
tests/CTS/methods/requests/search/partialUpdateObject.json

- Fix some wrong types and missing parameter of the API key response.
- Better name for the `partialUpdateObject` method parameter
- Fix missing required properties of `multipleBatch`
- Fix missing required `requests` of `getObjects`
CI :D

fix(specs): `getApiKeyResponse`, `multipleBatch`, `partialUpdateObject`

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.3 -> **`prerelease` _(e.g. 5.0.0-alpha.4)_**
- java: 4.4.2-SNAPSHOT -> **`patch` _(e.g. 4.4.3-SNAPSHOT)_**
- php: 4.0.0-alpha.8 -> **`prerelease` _(e.g. 4.0.0-alpha.9)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): dependencies 2022-08-01 (#879)
</details>

chore: prepare release 2022-08-03

---

playground/javascript/node/search.ts
templates/javascript/clients/client/api/helpers.mustache
templates/javascript/clients/client/model/clientMethodProps.mustache
website/docs/clients/installation.mdx
website/docs/clients/migration-guides/javascript.md

🎟 JIRA Ticket: - 
- `waitFor*` types were wrong (shouldn't require `maxRetries` and `timeout`)
- State default in JSDoc for `browse*` methods
- Add `@alpha` tag to installation guides
- `yarn docker playground javascript search` to test on the playground

fix(javascript): helpers type options

---

specs/search/paths/objects/partialUpdate.yml
specs/search/paths/rules/common/schemas.yml
specs/search/paths/rules/saveRules.yml
tests/CTS/methods/requests/search/partialUpdateObject.json
tests/CTS/methods/requests/search/saveRules.json

Fixes https://github.com/algolia/api-clients-automation/issues/891
↑ The full details are in the issue ↑
We now leverage the built-in `x-codegen-request-body-name` property in the spec to override the automatically guessed `requestBody`. 
I'll update the contributing guide in the docs in the next PR.
CI :D

fix(specs): wrong body parameter name

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.4 -> **`prerelease` _(e.g. 5.0.0-alpha.5)_**
- java: 4.4.3-SNAPSHOT -> **`patch` _(e.g. 4.4.4-SNAPSHOT)_**
- php: 4.0.0-alpha.9 -> **`prerelease` _(e.g. 4.0.0-alpha.10)_**
<details>
<summary>
</summary>
- chore: add CONTRIBUTING.md (#893)
</details>
<details>
<summary>
</summary>
</details>

chore: prepare release 2022-08-04

---

clients/algoliasearch-client-javascript/packages/client-common/src/__tests__/create-iterable-promise.test.ts
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/src/__tests__/browser-xhr-requester.test.ts
clients/algoliasearch-client-javascript/packages/requester-fetch/src/__tests__/fetch-requester.test.ts
clients/algoliasearch-client-javascript/packages/requester-node-http/src/__tests__/node-http-requester.test.ts

The tests can take 0ms to run, so we need to take that into account.
CI :D

fix(javascript): utils tests run time

---

specs/common/schemas/IndexSettings.yml
specs/search/common/schemas/SearchResponse.yml
tests/CTS/methods/requests/search/setSettings.json

- The `cursor` parameter of the `browseResponse` is optional.
- `indexSettings` was missing an attribute
- `exhaustiveTypo` shouldn't be required in the `searchResponse`
CI :D

fix(specs): browseResponse, IndexSettings and searchResponse

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.5 -> **`prerelease` _(e.g. 5.0.0-alpha.6)_**
- java: 4.4.4-SNAPSHOT -> **`patch` _(e.g. 4.4.5-SNAPSHOT)_**
- php: 4.0.0-alpha.10 -> **`prerelease` _(e.g. 4.0.0-alpha.11)_**
<details>
<summary>
</summary>
- docs: add troubleshooting section to contributing guide (#897)
</details>
<details>
<summary>
</summary>
- chore(deps): …

chore: prepare release 2022-08-08

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.6 -> **`prerelease` _(e.g. 5.0.0-alpha.7)_**
- java: 4.4.5-SNAPSHOT -> **`patch` _(e.g. 4.4.6-SNAPSHOT)_**
- php: 4.0.0-alpha.11 -> **`prerelease` _(e.g. 4.0.0-alpha.12)_**
_(None)_

chore: prepare release 2022-08-09

---

specs/search/paths/objects/batch.yml

`batch` body parameters are all required to be sent.
CI :D

fix(specs): make `batch` body parameters required

---

templates/java/api.mustache
templates/javascript/clients/algoliasearch/builds/initClients.mustache
templates/javascript/clients/client/builds/checkParameters.mustache
templates/php/ConfigWithRegion.mustache
templates/php/api.mustache
templates/php/tests/client/suite.mustache
tests/CTS/client/personalization/parameters.json
tests/CTS/client/predict/parameters.json
tests/CTS/client/query-suggestions/parameters.json
tests/CTS/client/sources/parameters.json

🎟 JIRA Ticket:
- https://algolia.atlassian.net/browse/APIC-619
- https://algolia.atlassian.net/browse/APIC-620
Suggested by @matthew1809
- Make missing region error include the available regions.
- Make PHP client detect missing `region` parameter when required
CI :D

fix(clients): list available regions when region is missing

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.7 -> **`prerelease` _(e.g. 5.0.0-alpha.8)_**
- java: 4.4.6-SNAPSHOT -> **`patch` _(e.g. 4.4.7-SNAPSHOT)_**
- php: 4.0.0-alpha.12 -> **`prerelease` _(e.g. 4.0.0-alpha.13)_**
_(None)_

chore: prepare release 2022-08-10

---

clients/algoliasearch-client-javascript/packages/client-common/src/transporter/createTransporter.ts
generators/src/main/java/com/algolia/codegen/AlgoliaJavaScriptGenerator.java
generators/src/main/java/com/algolia/codegen/cts/tests/TestsClient.java
templates/javascript/clients/api-single.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/APIC-621
See https://algolia.atlassian.net/browse/PRED-523 for context
The Predict API does not yet support user-agent query parameters, which makes every requests being rejected for unknown/non-parsable query parameter.
This is a not-really-pretty patch until it gets implemented, I've tried to minimize the footprint on the other clients but they all use the same requester. LMK if you have alternatives.
- JavaScript: We now send an empty string to the factory, which is not forwarded by the transporter.
- Tests: Small condition to skip the generation of the user-agent test for the Predict client.
I've added the Jira ticket in a comment near the patches until it gets resolved, to avoid forgetting to remove it.
The fix is only applied for …

fix(javascript): do not send user-agent for Predict

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.8 -> **`prerelease` _(e.g. 5.0.0-alpha.9)_**
- ~java: 4.4.7-SNAPSHOT (no commit)~
- ~php: 4.0.0-alpha.13 (no commit)~
_(None)_

chore: prepare release 2022-08-11

---

clients/algoliasearch-client-javascript/bundlesize.config.json
templates/javascript/clients/client/api/operation/parameters.mustache
tests/CTS/methods/requests/abtesting/listABTests.json
tests/CTS/methods/requests/search/getLogs.json
tests/CTS/methods/requests/search/hasPendingMappings.json
tests/CTS/methods/requests/search/listIndices.json
tests/CTS/methods/requests/search/listUserIds.json

🎟 JIRA Ticket: 
- https://algolia.atlassian.net/browse/APIC-590
- https://algolia.atlassian.net/browse/APIC-622
Discovered during Crawler implementation.
Some methods only have optional parameters, but still require an empty object as a parameter, which is not an ideal DX.
CI :D

fix(javascript): allow undefined object when all parameters are optional

---

.eslintignore
scripts/generate.ts

By default we lint the main folder of the client, which makes sense for all of them except JavaScript, since clients are generated in their own subfolder.
Locally it reduce the time by a lot, idk how it affects the CI but is already better for dev (especially if you don't have an M1).
On my computer, I've went from 30s to 10s for the following: 
```
yarn docker generate javascript search
```
1. Run generate for a few clients on `main`
2. Run generate for a few clients on this branch
3. See time of formatting decreased

chore: prevent linting all clients for JavaScript

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.9 -> **`prerelease` _(e.g. 5.0.0-alpha.10)_**
- ~java: 4.4.7-SNAPSHOT (no commit)~
- ~php: 4.0.0-alpha.13 (no commit)~
<details>
<summary>
</summary>
- chore: prevent linting all clients for JavaScript (#923)
- chore: fix license link (#921)
</details>
<details>
<summary>
</summary>
</details>

chore: prepare release 2022-08-12

---

website/docs/clients/guides/send-data-to-algolia.mdx
website/docs/clients/migration-guides/php.md

🎟 JIRA Ticket: APIC-547
- Update main table
- Add a small code sample to generate secured api key
- fix a small bug in a code sample
- Netlify preview

docs(php): update migration guide for PHP

---

playground/javascript/node/search.ts
templates/javascript/clients/package.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/PRED-530 https://algolia.atlassian.net/browse/APIC-625
Slack thread: https://algolia.slack.com/archives/C0341QDM3EG/p1660811425419539
This updates the clients exports to use the [`exports`](https://nodejs.org/api/packages.html#packages_main_entry_point_export) field.
There were issues in how clients were exported because the `module` assumed that it would get executed in a Node environment. This threw in multiple scenarios: Vite, Rollup, standard `<script type="module">`, etc.
We now rely on `exports` with two branches: `"node"` to load the Node ESM and `"default"` to load the browser ESM.
> When using environment branches, always include a `"default"` condition where possible. Providing a `"default"` condition ensures that any unknown …

fix(javascript): use `exports` field to pick correct bundle

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.10 -> **`prerelease` _(e.g. 5.0.0-alpha.11)_**
- ~java: 4.4.7-SNAPSHOT (no commit)~
- php: 4.0.0-alpha.14 -> **`prerelease` _(e.g. 4.0.0-alpha.15)_**
_(None)_

chore: prepare release 2022-08-23

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.11 -> **`prerelease` _(e.g. 5.0.0-alpha.12)_**
- ~php: 4.0.0-alpha.15 (no commit)~
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(docker): rename the container to api-client to be less generic (#951)
</details>

chore: prepare release 2022-08-25

---

.github/workflows/renovate.yml

Github seems to use a cached version when using tag like `@v1`, and never updates.
We want to use the latest feature (like `pull-request-title`) so we use the `latest` tag, as long as @bodinsamuel doesn't sabotage his action
Wait until next friday to try it out !

chore(deps): use latest version of renovate-automatic-branch action

---

clients/algoliasearch-client-javascript/packages/algoliasearch/__tests__/algoliasearch.test.ts
clients/algoliasearch-client-javascript/packages/client-common/src/createEchoRequester.ts
clients/algoliasearch-client-javascript/packages/client-common/src/transporter/helpers.ts
playground/javascript/node/predict.ts
templates/javascript/tests/client/suite.mustache
tests/output/javascript/yarn.lock

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/APIC-629
_Reported by the Predict team_
The query parameters were serialized but not encoded, I'm not sure when it has been removed since this piece of code comes from the current implementation.
It seems that on the Search API side, it either does not require the parameters to be encoded, or silently fails. Either way, it should now behave like in the current JavaScript client.
echoRequester: use same encoding/decoding than client
search requests work:
- `yarn docker playground javascript search`
predict requests work:
- set predict hack month creds in `.env`
- `yarn docker playground javascript predict`

fix(javascript): encode query parameters

---

scripts/buildClients.ts
scripts/ci/githubActions/createMatrix.ts

See build error in https://github.com/algolia/api-clients-automation/pull/974
Glob pattern match does not work with single match (unless we add a trailing comma). We can use regular scope syntax when there's a single element to prevent this error.
This throw:
```
cd clients/algoliasearch-client-javascript && yarn build:many '{@algolia/predict}'
```
This does not:
```
cd clients/algoliasearch-client-javascript && yarn build:many @algolia/predict
// OR
cd clients/algoliasearch-client-javascript && yarn build:many '{@algolia/predict,}'
```

chore: fix JavaScript build

---

generators/src/main/java/com/algolia/codegen/cts/tests/TestsRequest.java

When a new method is added to the spec, we check that there is a corresponding request test, but the error message was backward.
Now it's: 
`operationId 'getMachin' does not exist in the tests suite, please create the file 'tests/CTS/methods/requests/client/getMachin.json'`
Remove a test from the CTS

fix(cts): friendly error message when test is missing

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.13 -> **`prerelease` _(e.g. 5.0.0-alpha.14)_**
- ~java: 4.0.0-SNAPSHOT (no commit)~
- ~php: 4.0.0-alpha.15 (no commit)~
<details>
<summary>
</summary>
- chore: fix JavaScript build (#975)
</details>
<details>
<summary>
</summary>
- fix(cts): friendly error message when test is missing (#976)
- chore(deps): dependencies 2022-08-29 …

chore: prepare release 2022-08-31

---

generators/src/main/java/com/algolia/codegen/cts/tests/ParametersWithDataType.java

Friendly error message when a parameter is not recognized in the CTS, proposing what's accepted.
It can be confusing when it comes from a oneOf because we infer it's type before, and then display all the possibilities, it could also be a wrong match.
Also warning message for list oneOf, which are not well supported.
Change the name of a param.

fix(cts): friendly error message when a paremeter is not recognized

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.14 -> **`prerelease` _(e.g. 5.0.0-alpha.15)_**
- php: 4.0.0-alpha.15 -> **`prerelease` _(e.g. 4.0.0-alpha.16)_**
<details>
<summary>
</summary>
- chore: add CODEOWNERS (#979)
</details>
<details>
<summary>
</summary>
- fix(cts): friendly error message when a paremeter is …

chore: prepare release 2022-09-01

---

specs/predict/responses/UserProfile.yml

In #980 I forgot a capital letter for `predictionsFunnelStage`, which gets exported as the `PredictionsFunnelStage` type.
None added.

fix(specs): fix funnel stage type casing

---

.github/workflows/renovate.yml

The `latest` tag seems to not be automatically generated, so we fix it to the current latest `1.0.8`.

chore(deps): fix version of bodinsamuel/renovate-automatic-branch

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.16 -> **`prerelease` _(e.g. 5.0.0-alpha.17)_**
- php: 4.0.0-alpha.16 -> **`prerelease` _(e.g. 4.0.0-alpha.17)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): fix version of bodinsamuel/renovate-automatic-branch (#986)
- …

chore: prepare release 2022-09-08

---

generators/src/main/java/com/algolia/codegen/cts/AlgoliaCTSGenerator.java
playground/javascript/node/predict.ts
specs/predict/spec.yml
tests/CTS/client/predict/parameters.json

🎟 JIRA Ticket: [PRED-560](https://algolia.atlassian.net/browse/PRED-560)
Related PR: https://github.com/algolia/doc/pull/7336
- Update Predict Client API URL
New URL should be https://predict.us.algolia.com/ or https://predict.eu.algolia.com/ depending on region.

feat(specs): update predict client API URL

---

scripts/release/updateAPIVersions.ts

The `node_modules` inside `clients/algoliasearch-client-javascript` are required to release, but we never install them locally in reality.

chore(scripts): always install node modules during release process

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.18 -> **`prerelease` _(e.g. 5.0.0-alpha.19)_**
- php: 4.0.0-alpha.18 -> **`prerelease` _(e.g. 4.0.0-alpha.19)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(scripts): always install node modules during release process (#1012)
</details>

chore: prepare release 2022-09-14

---

specs/common/schemas/SearchParams.yml
specs/search/common/schemas/DeleteByParams.yml
specs/search/paths/objects/deleteBy.yml
tests/CTS/methods/requests/search/deleteBy.json

feat(specs): deleteByParams

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.19 -> **`prerelease` _(e.g. 5.0.0-alpha.20)_**
- php: 4.0.0-alpha.19 -> **`prerelease` _(e.g. 4.0.0-alpha.20)_**
_(None)_

chore: prepare release 2022-09-15

---

specs/predict/responses/UserProfile.yml

This fixes an inconsistency in our types: it adds the `predictions` prefix to the predictions success responses.
You can [see the exported types on Paka](https://paka.dev/npm/@algolia/predict@1.0.0-alpha.20/api#ab81a3e8312849b0).
- Prefix predictions success types with `predictions`
None added.

fix(specs): prefix Predict predictions success types

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.20 -> **`prerelease` _(e.g. 5.0.0-alpha.21)_**
- php: 4.0.0-alpha.20 -> **`prerelease` _(e.g. 4.0.0-alpha.21)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): dependencies 2022-09-19 (#1019)
</details>

chore: prepare release 2022-09-20

---

specs/predict/responses/Models.yml

Update Predict models response properties to avoid naming conflicts
- Change from `error` to `errorMessage`
- Change from `status` to `modelStatus`
- CTS tests remain unchanged for methods

fix(specs): update model response

---

specs/predict/common/schemas/modelsParams.yml
specs/predict/paths/models/models.yml
specs/predict/responses/Models.yml
tests/CTS/methods/requests/predict/activateModelInstance.json
tests/CTS/methods/requests/predict/updateModelInstance.json

Update Predict models endpoint to match revised API spec
🎟 JIRA Ticket: [PRED-639](https://algolia.atlassian.net/browse/PRED-639)
- Change `affinities` to `modelAttributes` and update its type
- Update the description of `modelAttributes`
- Update `status` to `modelStatus` in all description references
- Update models CTS tests
- Updated CTS tests for models methods

chore(specs): setup revised predict model spec

---

specs/predict/responses/Models.yml

- set `modelAttributes` as array of objects
- set `modelAttributes` as array of objects
- CTS tests remain unchanged for methods

fix(specs): update predict model endpoint modelAttributes type

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.23 -> **`prerelease` _(e.g. 5.0.0-alpha.24)_**
- php: 4.0.0-alpha.23 -> **`prerelease` _(e.g. 4.0.0-alpha.24)_**
_(None)_

chore: prepare release 2022-10-03

---

specs/predict/responses/Models.yml

- Content Attributes are now optional parameters in model instance responses
- Model Attributes are now optional parameters in model instance responses
- Remove `contentAttributes` from list of required parameters for model instance responses
- Remove `modelAttributes` from list of required parameters for model instance responses
- Tests remain unchanged

feat(specs): attributes no longer required in model instance response

---

specs/predict/paths/models/getModelMetrics.yml

add `modelID` as part of `getModelMetrics` response
[Please find spec here](https://docs.google.com/document/d/1ZiVXPqq7OzUhNQUN6gHm1bDZemGBs5I_UTPrNe__3B8/edit#heading=h.xtpurwy7k1mk)
- Changing the structure of the `getModelMetrics` response (within Predict client) from
```
object[]
```
to
```
{modelID:string, metrics:object[]}
```
CTS tests remain unchanged

feat(specs): add modelID as part of getModelMetrics response

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.25 -> **`prerelease` _(e.g. 5.0.0-alpha.26)_**
- php: 4.0.0-alpha.25 -> **`prerelease` _(e.g. 4.0.0-alpha.26)_**
_(None)_

chore: prepare release 2022-10-12

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.26 -> **`prerelease` _(e.g. 5.0.0-alpha.27)_**
- php: 4.0.0-alpha.26 -> **`prerelease` _(e.g. 4.0.0-alpha.27)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): dependencies 2022-10-31 (#1105)
</details>

chore: prepare release 2022-11-03

---

specs/ingestion/common/parameters.yml
specs/ingestion/common/schemas/authentication.yml
specs/ingestion/common/schemas/common.yml
specs/ingestion/common/schemas/destination.yml
specs/ingestion/common/schemas/event.yml
specs/ingestion/common/schemas/observability.yml
specs/ingestion/common/schemas/pagination.yml
specs/ingestion/common/schemas/run.yml
specs/ingestion/common/schemas/source.yml
specs/ingestion/common/schemas/task.yml
specs/ingestion/paths/authentications/authenticationID.yml
specs/ingestion/paths/authentications/authentications.yml
specs/ingestion/paths/destinations/destinationID.yml
specs/ingestion/paths/destinations/destinations.yml
specs/ingestion/paths/runs/events/eventID.yml
specs/ingestion/paths/runs/events/events.yml
specs/ingestion/paths/runs/runID.yml
specs/ingestion/paths/runs/runs.yml
specs/ingestion/paths/runs/task/taskID.yml
specs/ingestion/paths/sources/sourceID.yml
specs/ingestion/paths/sources/sources.yml
specs/ingestion/paths/tasks/disableTask.yml
specs/ingestion/paths/tasks/enableTask.yml
specs/ingestion/paths/tasks/runTask.yml
specs/ingestion/paths/tasks/taskID.yml
specs/ingestion/paths/tasks/tasks.yml
specs/ingestion/spec.yml

🎟 JIRA Ticket: [DI-382](https://algolia.atlassian.net/browse/DI-382)
Create the openapi specification for the Ingestion API ([repository](https://github.com/algolia/data-ingestion), [RFC](https://docs.google.com/document/d/13UnFi4Osfw4vOJr5iN4P4RJDZdslpFs4OgM4F1VBwQc/edit#heading=h.kp12qj1w1lig)).
This first PR is missing the pagination because it's not clear how it will be handled (body or query params).
It's also missing a lot of `description` fields, but we can definitely improve on the doc in the future.

feat(specs): create ingestion specs

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.27 -> **`prerelease` _(e.g. 5.0.0-alpha.28)_**
- php: 4.0.0-alpha.27 -> **`prerelease` _(e.g. 4.0.0-alpha.28)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): dependencies 2022-11-28 (#1144)
- chore(deps): dependencies 2022-11-14 …

chore: prepare release 2022-12-15

---

specs/search/spec.yml

This PR fixes two hostnames in the Search API spec.
This brings the API spec in line with what's used by the API clients and what's in the current documentation.
- `https://{appId}.algolianet.com` -> `https://{appId}.algolia.net`
- `https://{appId}-dsn.algolianet.com` -> `https://{appId}-dsn.algolia.net`
N/A

fix(specs): Algolia Search hostnames

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.28 -> **`prerelease` _(e.g. 5.0.0-alpha.29)_**
- php: 4.0.0-alpha.28 -> **`prerelease` _(e.g. 4.0.0-alpha.29)_**
<details>
<summary>
</summary>
- chore: bump docs deps (#1180)
</details>
<details>
<summary>
</summary>
</details>

chore: prepare release 2022-12-23

---

specs/ingestion/common/schemas/source.yml

This PR modify the `Ingestion` client.
Client will now be able to add a `JsonInput` when creating a new `Source`.
- New enum value for source type
- New enum value for http method

feat(specs): add source json to ingestion client

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.29 -> **`prerelease` _(e.g. 5.0.0-alpha.30)_**
- php: 4.0.0-alpha.29 -> **`prerelease` _(e.g. 4.0.0-alpha.30)_**
_(None)_

chore: prepare release 2022-12-28

---

specs/search/paths/advanced/getTask.yml

This PR fixes the type of the example of the `taskID` path parameter. It should be an integer, not a string.
- Change type of example of `taskID` to integer

fix(specs): example should be integer

---

specs/search/common/schemas/listIndicesResponse.yml

This PR aims to improve the specs for the `listIndicesResponse` schema.
Testing the `/1/indexes` endpoint, I found that `numberOfPendingTasks` should be plural.
This PR also adds default values for `pendingTask` (`false`) and `numberOfPendingTasks` (`0`) as both values always seem to be part of the response.
- fix name of response parameter `numberOfPendingTasks`
- Add default values for `numberOfPendingTasks` and `pendingTask`
- Make `numberOfPendingTasks` required for `listIndicesResponse`
- Make `primary` and `replicas` nullable

fix(specs): numberOfPendingTasks is plural

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.30 -> **`prerelease` _(e.g. 5.0.0-alpha.31)_**
- php: 4.0.0-alpha.30 -> **`prerelease` _(e.g. 4.0.0-alpha.31)_**
_(None)_

chore: prepare release 2023-01-04

---

specs/search/paths/rules/searchRules.yml

The `enabled` property has a default of `null` but wasn't declared `nullable`.
This PR addresses that.
- Make `enabled` nullable

fix(specs): make enabled nullable

---

specs/ingestion/common/schemas/task.yml

Put the `lastRun` and `nextRun` in the `trigger` object on tasks, and update `frequency` to `cron`

fix(specs): move lastRun and nextRun to task.trigger

---

specs/ingestion/common/schemas/destination.yml
specs/ingestion/common/schemas/source.yml

The field `authenticationID` is not required in `Source`. For example, we can setup a new Source, without authentication setup.
- Remove field from required

fix(specs): authenticationID is not required in source and destination

---

specs/ingestion/common/schemas/authentication.yml
specs/ingestion/common/schemas/source.yml
specs/ingestion/common/schemas/task.yml
specs/ingestion/paths/authentications/authenticationID.yml

The auth list endpoint doesn't return the `input` field.
Fixed the `description` for locales.
Make `scope` not required.

fix(specs): remove input from auth list

---

clients/algoliasearch-client-javascript/bundlesize.config.json
clients/algoliasearch-client-javascript/packages/client-common/src/transporter/errors.ts
clients/algoliasearch-client-javascript/packages/client-common/src/transporter/helpers.ts

Create new error type `DetailedApiError` that will be used if an `error` is present in the response, mostly used by the ingestion API.

feat(javascript): add error to APIError if possible

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.33 -> **`prerelease` _(e.g. 5.0.0-alpha.34)_**
- ~java: 4.0.0-SNAPSHOT (no commit)~
- ~php: 4.0.0-alpha.33 (no commit)~
_(None)_

chore: prepare release 2023-01-17

---

specs/ingestion/common/authenticationParameters.yml
specs/ingestion/common/destinationParameters.yml
specs/ingestion/common/schemas/authentication.yml
specs/ingestion/common/sourceParameters.yml
specs/ingestion/paths/authentications/authentications.yml
specs/ingestion/paths/destinations/destinations.yml
specs/ingestion/paths/sources/sources.yml

🎟 JIRA Ticket: [DI-837](https://algolia.atlassian.net/browse/DI-837)
Add query param filtering to lists endpoint in the ingestion API client:
- sources
- destinations
- authentications
[DI-837]: https://algolia.atlassian.net/browse/DI-837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add query param to filter list endpoint results

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.35 -> **`prerelease` _(e.g. 5.0.0-alpha.36)_**
- php: 4.0.0-alpha.34 -> **`prerelease` _(e.g. 4.0.0-alpha.35)_**
_(None)_

chore: prepare release 2023-01-19

---

config/openapitools.json

The java CTS is not handling well `allOf` property, and runs into stack overflow issue.
We can disable it for now and add back the predict client once the CTS is fixed.

feat(java): remove predict client temporarely

---

specs/ingestion/common/authenticationParameters.yml
specs/ingestion/common/schemas/authentication.yml
specs/ingestion/common/sourceParameters.yml
specs/ingestion/common/taskParameters.yml
specs/ingestion/paths/tasks/tasks.yml

- Add `sourceID` query param to help task filtering
- Remove `AuthenticationNone` type
- Add `PlatformNone` type

feat(specs): add sourceID query param to task list endpoint

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.36 -> **`prerelease` _(e.g. 5.0.0-alpha.37)_**
- php: 4.0.0-alpha.35 -> **`prerelease` _(e.g. 4.0.0-alpha.36)_**
_(None)_

chore: prepare release 2023-01-26

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.37 -> **`prerelease` _(e.g. 5.0.0-alpha.38)_**
- php: 4.0.0-alpha.36 -> **`prerelease` _(e.g. 4.0.0-alpha.37)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): dependencies 2023-01-30 (#1266)
</details>

chore: prepare release 2023-01-30

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.38 -> **`prerelease` _(e.g. 5.0.0-alpha.39)_**
- php: 4.0.0-alpha.37 -> **`prerelease` _(e.g. 4.0.0-alpha.38)_**
_(None)_

chore: prepare release 2023-01-31

---

specs/ingestion/common/schemas/task.yml

This PR fixes some wrong types on the Ingestion specs, and makes the definition closer to the real API.
- there's no test for this client.

fix(specs): correct types for Tasks trigger

---

generators/src/main/java/com/algolia/codegen/AlgoliaJavaScriptGenerator.java
templates/javascript/clients/api-single.mustache
templates/javascript/clients/client/api/guards.mustache
templates/javascript/clients/client/api/imports.mustache

🎟 JIRA Ticket: Related to [DI-873](https://algolia.atlassian.net/browse/DI-873)
- add type guards to help determine Task Trigger specific type
- add imports
- add file to the client
[DI-873]: https://algolia.atlassian.net/browse/DI-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(javascript): add task trigger type guards

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.39 -> **`prerelease` _(e.g. 5.0.0-alpha.40)_**
- php: 4.0.0-alpha.38 -> **`prerelease` _(e.g. 4.0.0-alpha.39)_**
_(None)_

chore: prepare release 2023-02-03

---

specs/ingestion/common/schemas/task.yml
specs/ingestion/common/taskParameters.yml
templates/javascript/clients/client/api/guards.mustache

the `on_demand` property have been renamed to `onDemand`
-

fix(specs): rename task type to `onDemand`

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.41 -> **`prerelease` _(e.g. 5.0.0-alpha.42)_**
- php: 4.0.0-alpha.39 -> **`prerelease` _(e.g. 4.0.0-alpha.40)_**
_(None)_

chore: prepare release 2023-02-06

---

specs/ingestion/common/schemas/source.yml

Add CSV Source for Data Ingestion client API.
Add CSV to Source type.

feat(specs): add CSV source

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.42 -> **`prerelease` _(e.g. 5.0.0-alpha.43)_**
- php: 4.0.0-alpha.40 -> **`prerelease` _(e.g. 4.0.0-alpha.41)_**
_(None)_

chore: prepare release 2023-02-09

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.43 -> **`prerelease` _(e.g. 5.0.0-alpha.44)_**
- php: 4.0.0-alpha.41 -> **`prerelease` _(e.g. 4.0.0-alpha.42)_**
_(None)_

chore: prepare release 2023-02-10

---

specs/predict/responses/Segment.yml

The Predict API doesn't support a segment version yet. This will be added in a later iteration.
🎟 JIRA Ticket: n/a
- Remove `version` from `Segment` response.
n/a

fix(specs): remove segment version

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.45 -> **`prerelease` _(e.g. 5.0.0-alpha.46)_**
- php: 4.0.0-alpha.43 -> **`prerelease` _(e.g. 4.0.0-alpha.44)_**
_(None)_

chore: prepare release 2023-02-14

---

generators/src/main/java/com/algolia/codegen/AlgoliaJavaGenerator.java
specs/predict/responses/Segment.yml
tests/CTS/methods/requests/predict/createSegment.json
tests/CTS/methods/requests/predict/updateSegment.json

Since the API client generator tool doesn't support `>` symbol as keys, we decided to use the `GT` syntax both in the API client and in the Predict REST API.
This PR updates symbol operators like `"="` to textual operators like `"EQ"`.
- Updated the probability filters to use textual operators like `"EQ"`
- Updated all operators to uppercase
- Remove operator converter introduced in [`e1c61be` (#1202)](https://github.com/algolia/api-clients-automation/pull/1202/commits/e1c61bea44a33ed1c5f54ba444682300cac56345)
- Added test with filter probability
- https://github.com/algolia/predict-api/pull/67

fix(specs): update Predict Segment operators to textual format

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.47 -> **`prerelease` _(e.g. 5.0.0-alpha.48)_**
- php: 4.0.0-alpha.45 -> **`prerelease` _(e.g. 4.0.0-alpha.46)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): dependencies 2023-02-20 (#1319)
</details>

chore: prepare release 2023-02-22

---

.github/actions/setup/action.yml
.github/workflows/check.yml
.github/workflows/codegen.yml
.github/workflows/pr-title.yml
.github/workflows/scheduled-release.yml
clients/algoliasearch-client-java-2/.github/workflows/release.yml
clients/algoliasearch-client-javascript/.github/workflows/release.yml
scripts/ci/githubActions/createMatrix.ts
scripts/ci/githubActions/setRunVariables.ts
scripts/ci/githubActions/utils.ts
scripts/package.json
yarn.lock

🎟 JIRA Ticket: [DI-923](https://algolia.atlassian.net/browse/DI-923)
We have a lot of deprecation warning, for node 12 and for the `set-output` thing, but it's not supported in js so we have to do a [workaround](https://github.com/actions/toolkit/issues/1218#issuecomment-1288890856) until this is fixed.
[DI-923]: https://algolia.atlassian.net/browse/DI-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(scripts): catch up on deprecated github actions

---

specs/ingestion/common/schemas/run.yml

🎟 JIRA Ticket:
- add a `reason` prop to the `run` object

feat(specs): add a reason string to the run object

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.49 -> **`prerelease` _(e.g. 5.0.0-alpha.50)_**
- php: 4.0.0-alpha.47 -> **`prerelease` _(e.g. 4.0.0-alpha.48)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(scripts): catch up on deprecated github actions (#1345)
</details>

chore: prepare release 2023-02-28

---

specs/ingestion/common/schemas/run.yml

`skipped` run can be used to filter runs, and are returned by the API.
doc: The run have been skipped by the tasks-scheduler due to an already ongoing run for the given task.

fix(specs): add skipped runs

---

config/openapitools.json
generators/build.gradle
package.json
scripts/cts/generate.ts
templates/java/pojo.mustache
templates/javascript/clients/model.mustache
yarn.lock

🎟 JIRA Ticket: [DI-904](https://algolia.atlassian.net/browse/DI-904)
Upgrade to the latest version, it was a lot less difficult than last time, I guess some bugs got fixed along the way.
It changes some weird things on the generated clients, but all the tests are okay, maybe it was because of inlining ?
- Build specs locally before generating CTS, the same as for generate clients.
[DI-904]: https://algolia.atlassian.net/browse/DI-904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(all): upgrade openapi-generator to v6.4.0

---

scripts/common.ts

When an error occurs in `execa` we printed the error twice, there is no need for that and we can print a better error instead.

chore(scripts): remove double error log

---

scripts/release/createReleasePR.ts

#1365 broke the release script because the output of `run` changes based on the verbose level, maybe it should and should always return the same thing (there is a newline at the end in verbose mode)

fix(scripts): release need verbose=false

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.50 -> **`prerelease` _(e.g. 5.0.0-alpha.51)_**
- php: 4.0.0-alpha.48 -> **`prerelease` _(e.g. 4.0.0-alpha.49)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- fix(scripts): release need verbose=false (#1367)
- chore(scripts): remove double error …

chore: prepare release 2023-03-02

---

scripts/ci/codegen/pushGeneratedCode.ts
scripts/ci/codegen/spreadGeneration.ts
scripts/ci/utils.ts
scripts/common.ts
scripts/release/common.ts
scripts/release/createReleasePR.ts

Refacto some functions to put them in the right common file and avoid importing between folders.
Fix the java release by deleting the tag before the release

fix(java): delete tag before release

---

clients/algoliasearch-client-java-2/CHANGELOG.md

- ~javascript: 5.0.0-alpha.51 (no commit)~
- ~php: 4.0.0-alpha.49 (no commit)~
_(None)_

chore: prepare release 2023-03-03

---

specs/ingestion/common/schemas/destination.yml
specs/ingestion/common/schemas/source.yml

authenticationID is not always required

fix(specs): authenticationID not required in source and destination

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.51 -> **`prerelease` _(e.g. 5.0.0-alpha.52)_**
- php: 4.0.0-alpha.49 -> **`prerelease` _(e.g. 4.0.0-alpha.50)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): dependencies 2023-03-06 (#1373)
- fix(scripts): release independently …

chore: prepare release 2023-03-07

---

scripts/ci/codegen/spreadGeneration.ts

`released` tag needs to be deleted both locally and on origin apparently.

fix(scripts): released tag needs to be deleted

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.52 -> **`prerelease` _(e.g. 5.0.0-alpha.53)_**
- php: 4.0.0-alpha.50 -> **`prerelease` _(e.g. 4.0.0-alpha.51)_**
<details>
<summary>
</summary>
- chore: release 2023-03-07 [skip ci]
- chore: prepare release 2023-03-07 (#1381)
</details>
<details>
<summary>
</summary>
- …

chore: prepare release 2023-03-08

---

specs/predict/responses/UserProfile.yml

Introducing support for numbers and booleans in the value property of the `Affinity` type
From
```js
{
name:string,
value:string,
probability:number
}
```
to
```js
{
name:string,
value:string | number | boolean,
probability:number
}
```
- Add `PredictionAffinityValue` type

feat(specs): update affinity value type to accomodate booleans and numbers

---

specs/ingestion/spec.yml

🎟 JIRA Ticket:
- make the `eu` region available for the ingestion client

feat(specs): make the `eu` region available for the ingestion client

---

specs/ingestion/common/schemas/source.yml
specs/ingestion/common/schemas/task.yml
specs/ingestion/spec.yml
templates/javascript/clients/client/api/guards.mustache

- Fix the `tasks.trigger` property
- Rename `on_demand` to `onDemand`
- Add the 4 custom requests

fix(specs): add customRequest to ingestion and small fix

---

clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.53 -> **`prerelease` _(e.g. 5.0.0-alpha.54)_**
- php: 4.0.0-alpha.51 -> **`prerelease` _(e.g. 4.0.0-alpha.52)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- feat(cts): add ingestion tests (#1419)
- chore(deps): dependencies 2023-03-20 (#1403) …

chore: prepare release 2023-03-24

---

clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.55 -> **`prerelease` _(e.g. 5.0.0-alpha.56)_**
- php: 4.0.0-alpha.53 -> **`prerelease` _(e.g. 4.0.0-alpha.54)_**
- go: 4.0.0-alpha.2 -> **`prerelease` _(e.g. 4.0.0-alpha.3)_**
_(None)_

chore: prepare release 2023-04-06

---

playground/go/analytics.go
playground/go/ingestion.go
playground/go/insights.go
playground/go/main.go
playground/go/personalization.go
playground/go/predict.go
playground/go/query-suggestions.go
playground/go/recommend.go
playground/go/search.go
playground/go/util.go
scripts/playground.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/APIC-664
More structured playground examples were added for the go client to give more examples to test.
- Playground examples added for generated go packages. 
can be tested with `yarn docker playground go {client}`

feat(go): add more playground examples

---

templates/javascript/clients/client/api/imports.mustache

Fix forgotten type import for updated type guard

fix(specs): task trigger guard import

---

clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.56 -> **`prerelease` _(e.g. 5.0.0-alpha.57)_**
- php: 4.0.0-alpha.54 -> **`prerelease` _(e.g. 4.0.0-alpha.55)_**
- go: 4.0.0-alpha.3 -> **`prerelease` _(e.g. 4.0.0-alpha.4)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): …

chore: prepare release 2023-04-12

---

clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.57 -> **`prerelease` _(e.g. 5.0.0-alpha.58)_**
- php: 4.0.0-alpha.55 -> **`prerelease` _(e.g. 4.0.0-alpha.56)_**
- go: 4.0.0-alpha.4 -> **`prerelease` _(e.g. 4.0.0-alpha.5)_**
_(None)_

chore: prepare release 2023-04-18

---

clients/algoliasearch-client-javascript/packages/requester-fetch/src/createFetchRequester.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1210
Motivations can be found in https://github.com/algolia/algoliasearch-client-javascript/pull/1452
TLDR: We can remove this parameter from the defaulted values, as it's not compatible with Cloudflare workers. If the user wants to specify it, they can by providing request options.

fix(javascript): remove `mode` from Fetch requester

---

.github/workflows/check.yml

It's not possible to easily debug issues like https://github.com/algolia/api-clients-automation/pull/1474 as the artifact is not generated when the CI fails, and therefore the file not accessible. This PR changes the CI check to be non blocking but to print the file if it exists

chore: make Java breaking changes non blocking

---

scripts/ci/githubActions/setRunVariables.ts
scripts/ci/githubActions/utils.ts

The cache key computing was pretty strict since we were developping a lot on this repository, not that it's a bit stalled we can loose it so that we don't end-up with false computed cache and unwanted behaviors

chore: loose cache key computing by including CTS

---

specs/predict/responses/Segment.yml

Follow up to https://github.com/algolia/api-clients-automation/pull/1434
🎟 JIRA Ticket: [PRED-1277](https://algolia.atlassian.net/browse/PRED-1277)
This adds the segment's `size` to the create and update responses.
n/a
[PRED-1277]: https://algolia.atlassian.net/browse/PRED-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add predict segment size to responses [PRED-1277]

---

clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.58 -> **`prerelease` _(e.g. 5.0.0-alpha.59)_**
- php: 4.0.0-alpha.56 -> **`prerelease` _(e.g. 4.0.0-alpha.57)_**
- go: 4.0.0-alpha.5 -> **`prerelease` _(e.g. 4.0.0-alpha.6)_**
<details>
<summary>
</summary>
- chore: loose cache key computing by including CTS (#1477)
- chore: make Java breaking changes non blocking …

chore: prepare release 2023-04-20

---

specs/ingestion/common/schemas/source.yml

🎟 JIRA Ticket: DI-1034
- added `bigquery` to `sourceTypes` enum

feat(clients): add bigquery to sourceTypes enum

---

specs/ingestion/common/schemas/task.yml

🎟 JIRA Ticket: [DI-1218](https://algolia.atlassian.net/browse/DI-1218)
Remove `delete` option in the task action type enum so it is also removed in the doc, as it's unsupported right now
[DI-1218]: https://algolia.atlassian.net/browse/DI-1218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(specs): remove unsupported delete option for task action type

---

clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.60 -> **`prerelease` _(e.g. 5.0.0-alpha.61)_**
- php: 4.0.0-alpha.58 -> **`prerelease` _(e.g. 4.0.0-alpha.59)_**
- go: 4.0.0-alpha.7 -> **`prerelease` _(e.g. 4.0.0-alpha.8)_**
_(None)_

chore: prepare release 2023-05-09

---

specs/ingestion/common/schemas/source.yml

🎟 JIRA Ticket: [DI-1276](https://algolia.atlassian.net/browse/DI-1276)
- add `customSQLRequest` property to the BigQuery source input
[DI-1276]: https://algolia.atlassian.net/browse/DI-1276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add property to BigQuery source input

---

clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.61 -> **`prerelease` _(e.g. 5.0.0-alpha.62)_**
- php: 4.0.0-alpha.59 -> **`prerelease` _(e.g. 4.0.0-alpha.60)_**
- go: 4.0.0-alpha.8 -> **`prerelease` _(e.g. 4.0.0-alpha.9)_**
_(None)_

chore: prepare release 2023-05-16

---

templates/go/api.mustache
templates/go/client.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/APIC-665
To improve the developer experience, we need better documentation on our code so the users will not need to switch between external documentation and code again and again.
- Added and improved comments on all the requests.
- Some pieces are reordered to give easier navigation when using the package.
Nothing changed functionally, generated commit can be checked to see examples of the comments.

feat(go): comments are enhanced to provide better developer experience

---

clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.64 -> **`prerelease` _(e.g. 5.0.0-alpha.65)_**
- php: 4.0.0-alpha.62 -> **`prerelease` _(e.g. 4.0.0-alpha.63)_**
- go: 4.0.0-alpha.11 -> **`prerelease` _(e.g. 4.0.0-alpha.12)_**
_(None)_

chore: prepare release 2023-05-25

---

clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.65 -> **`prerelease` _(e.g. 5.0.0-alpha.66)_**
- php: 4.0.0-alpha.63 -> **`prerelease` _(e.g. 4.0.0-alpha.64)_**
- go: 4.0.0-alpha.12 -> **`prerelease` _(e.g. 4.0.0-alpha.13)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
<i>Commits …

chore: prepare release 2023-05-31

---

specs/ingestion/common/schemas/source.yml

Add support for `docker` source.

fix(specs): add docker source input

---

clients/algoliasearch-client-dart/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.66 -> **`prerelease` _(e.g. 5.0.0-alpha.67)_**
- php: 4.0.0-alpha.64 -> **`prerelease` _(e.g. 4.0.0-alpha.65)_**
- go: 4.0.0-alpha.13 -> **`prerelease` _(e.g. 4.0.0-alpha.14)_**
- dart: 0.1.0-alpha.1 -> **`prerelease` _(e.g. 0.1.0-alpha.2)_**
_(None)_

chore: prepare release 2023-06-05

---

templates/javascript/clients/client/api/helpers.mustache

The logic was somehow inverted in order to determine if the key had been updated or not.

fix(javascript): waitForApiKey helper

---

templates/javascript/clients/client/api/helpers.mustache

So actually the logic was correct, we compare the payload of the update with the payload of the get API key, if they are similar, then it has changed, otherwise we retry

revert: "fix(javascript): waitForApiKey helper (#1598)"

---

clients/algoliasearch-client-dart/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.68 -> **`prerelease` _(e.g. 5.0.0-alpha.69)_**
- php: 4.0.0-alpha.66 -> **`prerelease` _(e.g. 4.0.0-alpha.67)_**
- go: 4.0.0-alpha.15 -> **`prerelease` _(e.g. 4.0.0-alpha.16)_**
- dart: 0.3.0 -> **`patch` _(e.g. 0.3.1)_**
_(None)_

chore: prepare release 2023-06-15

---

clients/algoliasearch-client-dart/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.69 -> **`prerelease` _(e.g. 5.0.0-alpha.70)_**
- php: 4.0.0-alpha.67 -> **`prerelease` _(e.g. 4.0.0-alpha.68)_**
- go: 4.0.0-alpha.16 -> **`prerelease` _(e.g. 4.0.0-alpha.17)_**
- dart: 0.3.1 -> **`patch` _(e.g. 0.3.2)_**
_(None)_

chore: prepare release 2023-06-16

---

specs/ingestion/common/schemas/source.yml

Fixes a tiny typo in the Github Container Repository.

fix(specs): change github container registry name

---

clients/algoliasearch-client-dart/melos.yaml
scripts/release/updateAPIVersions.ts

The scripts is not able to update static version and config file after an update.
- Update melos post script
- Update config file version script

chore(ci): fix melos version post scripts

---

clients/algoliasearch-client-dart/melos.yaml
clients/algoliasearch-client-dart/sync.sh

The command `sed` isn't behaving the same way in both macos and linux, causing the scripts to fail.
🎟 JIRA Ticket:
Update the script to work for BSD/Linux platforms.

chore(ci): fix melos post script compat

---

clients/algoliasearch-client-dart/melos.yaml
clients/algoliasearch-client-dart/packages/client_core/lib/src/transport/dio/dio_requester.dart
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml

Starting from version `5.2.0`, the HTTP client Dio has started throwing errors in `dart analyze` due to a migration from `DioError` to `DioException`. Any errors thrown during `dart analyze` will cause the release process to fail.
- The error handling logic has been updated to use `DioException`.
- The dio version has been updated.
- The Melos scripts have been updated to run `dart analyze` and will now fail if any errors are found.

fix(dart): update `dio` exceptions handling 

---

templates/dart/pubspec.mustache

This PR pins the versions of the Algolia packages in the `pubspec.yaml` to ensure compatibility and stability as we await API stabilization. This proactive measure minimizes the risk of unexpected behavior or issues stemming from uncontrolled version updates. 
Pinned versions of Algolia packages. On version update, `melos version` will automatically adjust these pinned versions.

refactor(dart): pin algolia packages versions

---

website/docs/clients/guides/manage-dictionary-entries.mdx
website/sidebars.js

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/APIC-516
This PR adds a small guide that indices to the user how to manage dictionary entries.
See [netlify preview](https://deploy-preview-1663--api-clients-automation.netlify.app/docs/clients/guides/manage-dictionary-entries/)

docs: add `manage dictionary entries` guide

---

clients/algoliasearch-client-dart/.github/scripts/version.sh

Resolve an issue within Dart CI workflow where the publish script used `GITHUB_ENV`, where it should have utilized `GITHUB_OUTPUT` instead.
Update the script to use `GITHUB_OUTPUT`.

chore(dart): update publish script

---

website/docs/clients/guides/replace-all-rules-synonyms.mdx
website/sidebars.js

🎟 JIRA Ticket: APIC-518
Add guide to replace all rules and synonyms using `saveRules` and `saveSynonyms` methods respectively.
[Preview](https://deploy-preview-1668--api-clients-automation.netlify.app/docs/clients/guides/replace-all-rules-synonyms)

docs(guides): replace all rules and synonyms

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md

The `CHANGELOG.md` files, which are parsed and rendered by pub.dev, have been found to contain minor formatting issues. This can cause difficulties in interpretation and readability when displayed on pub.dev.
We have addressed and rectified the formatting inconsistencies within the `CHANGELOG.md` files

docs(dart): update changelog formatting

---

website/docs/clients/guides/copy-or-move-index-rules-settings-synonyms.mdx
website/docs/clients/migration-guides/index.mdx
website/sidebars.js

🎟 JIRA Ticket: [APIC-517](https://algolia.atlassian.net/browse/APIC-517)
The existing snippets are generic enough for this guide, just updated the title and added the old function name to make it easier to find.
[APIC-517]: https://algolia.atlassian.net/browse/APIC-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: add migration guide for copyRules/settings/synonyms

---

specs/ingestion/common/schemas/authentication.yml
specs/ingestion/paths/authentications/authenticationID.yml

The list authentications endpoint now return `input` too (although obfuscated)

fix(specs): add input to authentication list

---

Dockerfile
package.json
scripts/docker/mount.sh

This PR aims to streamline the process of creating release PRs for Docker images. 
We can now use the `yarn docker:release` command to create a release PR.
🎟 JIRA Ticket: APIC-699
- Added `docker:release` command in `package.json`.
- Modified `Dockerfile` to install `git` during the Docker image build process.
_`GITHUB_TOKEN` environment variable is required to run the release command._

chore: add release using docker

---

website/docs/clients/guides/delete-objects.mdx
website/docs/clients/guides/manage-dictionary-entries.mdx
website/docs/clients/guides/replace-all-rules-synonyms.mdx

The migration guides are currently missing Java code snippets.
🎟 JIRA Ticket: APIC-685
Added Java snippets to:

docs(java): add migration guides code snippets

---

Dockerfile
scripts/formatter.ts
templates/go/tests/requests/requests.mustache

unused imports aren't removed, and as the linter is not fully setup yet, let's quickly unlock pending PRs (https://github.com/algolia/api-clients-automation/pull/1683) . I've created https://algolia.atlassian.net/browse/DI-1417 for next sprint
Also fix the PATH so that it uses the same command everywhere, useful when using sh directly

fix(scripts): unused imports in go tests

---

clients/algoliasearch-client-javascript/yarn.lock
generators/src/main/java/com/algolia/codegen/cts/manager/JavaScriptCTSManager.java
scripts/cts/generate.ts
templates/javascript/tests/package.mustache
tests/output/javascript/yarn.lock

an other bug discovered in https://github.com/algolia/api-clients-automation/pull/1683, the package.json for the JavaScript client tests were outdated and manually created, now they are fully generated

fix(cts): generate lock and package.json for javascript

---

specs/search/paths/advanced/getLogs.yml
specs/search/paths/advanced/getTask.yml

This PR reviews just the advanced operations of the Search API.
`pendingTask` is returned in the response but isn’t in the OAS. The [docs](https://www.algolia.com/doc/rest-api/search/#interpreting-the-response) say “pendingTask is deprecated and shouldn’t be used.” Given that it _is_ returned, should it be added to the OAS along with a description saying something like  “`pendingTask` is a legacy value, no longer used by Algolia”?

docs(specs): Review OpenAPI Search API (advanced operations)

---

specs/search/paths/manage_indices/listIndices.yml
specs/search/paths/manage_indices/operationIndex.yml
specs/search/paths/settings/settings.yml
tests/CTS/methods/requests/search/listIndices.json

This PR reviews just the index operations of the Search API.
- Original content says “ You can't move a source index that has replicas.” but that appears not to be true. I can carry out a move operation on an index with replicas. It won’t rename the original but, instead, creates an empty index with the destination name. Should this be stated?
- The `page` parameter requires a  `hitsPerPage` parameter to make any sense/return sensible results. This was missing in the original OAS, I’ve added it but is the default of 100 correct?
- In the response, `allowCompressionOfIntegerArray` notes say “If `true`, the engine applies a better compression ratio. This is recommended for arrays containing non-negative integers. When enabled, the …

docs(specs): Review OpenAPI Search API (index operations)

---

specs/search/paths/dictionaries/batchDictionaryEntries.yml
specs/search/paths/dictionaries/common/parameters.yml
specs/search/paths/dictionaries/common/schemas/Languages.yml
specs/search/paths/dictionaries/common/schemas/SearchDictionaryEntriesResponse.yml
specs/search/paths/dictionaries/dictionarySettings.yml
specs/search/paths/dictionaries/getDictionaryLanguages.yml
specs/search/paths/dictionaries/searchDictionaryEntries.yml

This PR reviews just the dictionary operations of the Search API.
Plurals and compounds are part of the `standardEntries` object but only stop words are supported by the API call. Should the OAS change?

docs(specs): Review OpenAPI Search API (dictionary operations)

---

renovate.json

`ignorePaths` and `includePaths` don't work together, only `includePaths` was taken into account

chore(renovate): don't use includePaths

---

specs/abtesting/common/parameters.yml
specs/abtesting/common/schemas/ABTest.yml
specs/abtesting/common/schemas/AddABTestsVariant.yml
specs/abtesting/common/schemas/Variant.yml
specs/abtesting/paths/abtest.yml
specs/abtesting/paths/abtests.yml
specs/abtesting/paths/stopABTest.yml
specs/abtesting/spec.yml
specs/search/common/schemas/SearchResponse.yml
tests/CTS/methods/requests/abtesting/addABTests.json

This PR reviews the A/B testing API.
In the response, the difference between `count` and `total` is confusing. For instance, I listed the A/B tests on G6TRZ8PT96: `count` = 10 and `total` = 12. The original text implies that:
- 10 A/B tests have been implemented
- 12 A/B tests can be retrieved
It feels like the descriptions are the wrong way around.
Why can’t some tests be retrieved? Because they’ve been deleted? Only due to deletion? Or due to being outside the analytics retention window of 90 to 365 days?
In the response, under `abtests > variants > averageClickPosition`, what does a click position of `0` indicate? No click events? Or does `null` indicate no click events?
🎟 JIRA Ticket: [DOC-1113](https://algolia.atlassian.net/browse/DOC-1113)
Update summary, description and examples …

docs(specs): Review OpenAPI A/B testing  specs

---

package.json
scripts/release/createReleasePR.ts
scripts/release/types.ts
scripts/release/updateAPIVersions.ts

See https://github.com/algolia/api-clients-automation/actions/runs/5584120552/jobs/10205172965, it seems like I forgot to convert the release script to esm.
Also use `--env-file` instead of inline `env` for the release, so that it matches what we recommend in the [release process](https://api-clients-automation.netlify.app/docs/contributing/release-process/)

fix(scripts): esm release

---

specs/search/paths/keys/common/parameters.yml
specs/search/paths/keys/common/schemas.yml
specs/search/paths/keys/key.yml
specs/search/paths/keys/keys.yml
specs/search/paths/keys/restoreApiKey.yml

This PR reviews just the API key operations of the Search API.
On the [docs site,](https://www.algolia.com/doc/rest-api/search/#keys-endpoints) there are quite a few more operations that deal with index-specific API keys. These aren’t present in the Search API OAS. Should they be added to it?

docs(specs): Review OpenAPI Search API (API key operations)

---

specs/analytics/paths/status/getStatus.yml

This is one of several PRs addressing the Analytics API.
This PR reviews just the advanced operations of the Analytics API.
Some seemingly contradictory statements here: 
- There’s a note that says “The Analytics API is updated every 5 minutes” Does that mean that the API data can be up to five minutes behind real-time? 
- The statement “Returns the latest update time of the Analytics API for an index.” seems to refer to that “When in the last five minutes has the Analytics API (data?) been updated?” Should it instead say something like “Returns the time of the most recent Analytics API call”?
- The statement “If the index has been recently created or no search has been performed yet, `updatedAt` will be `null`.” seems to imply that the Analytics API (data) will be updated even if no …

docs(specs): Review OpenAPI Analytics (advanced)

---

specs/search/paths/multiclusters/batchAssignUserIds.yml
specs/search/paths/multiclusters/getTopUserIds.yml
specs/search/paths/multiclusters/hasPendingMappings.yml
specs/search/paths/multiclusters/listClusters.yml
specs/search/paths/multiclusters/searchUserIds.yml
specs/search/paths/multiclusters/userId.yml
specs/search/paths/multiclusters/userIds.yml

This PR reviews just the cluster operations of the Search API.
Given that [MCM is no longer offered](https://www.algolia.com/doc/guides/scaling/managing-multiple-clusters-mcm/#managing-multiple-clusters), check the new note in spec.yml. Is this ok?
[Docs site](https://www.algolia.com/doc/rest-api/search/#list-userids) intimates a hitsPerPage default of 1,000. However, the OAS states a default of 100. Which is correct?
The two statements seem self-contradictory:
1. To ensure rapid updates, the userIDs index isn't built at the same time as the mapping. Instead, it's built every 12 hours, at the same time as the update of user ID usage. For example, if you add or move a user ID, the search will show an old value until the next time the …

docs(specs): Review OpenAPI Search API (multicluster operations)

---

specs/search/paths/synonyms/clearAllSynonyms.yml
specs/search/paths/synonyms/common/parameters.yml
specs/search/paths/synonyms/common/schemas.yml
specs/search/paths/synonyms/saveSynonyms.yml
specs/search/paths/synonyms/searchSynonyms.yml
specs/search/paths/synonyms/synonym.yml

This PR reviews just the synonym operations of the Search API.
You can add synonym objectIDs in the path parameter and the body parameter. It appears that the objectID in the body parameter takes precedence. Is that always the case?

docs(specs): Review OpenAPI Search API (synonym operations)

---

clients/algoliasearch-client-dart/packages/client_core/lib/src/transport/dio/dio_requester.dart
templates/dart/api.mustache
templates/dart/serialization/json_serializable/deserialize.mustache

Custom calls  (.e.g. `post`) can encounter failure due to several factors, which include:
- Issues with path encoding
- Problems during response deserialization
- Absence of required request headers
- Path encoding is now skipped
- Raw response is returned, rather than deserialized data
- The `Content-Type` header is now added by default if a request body is provided

fix(dart): custom calls path and deserialization

---

scripts/__tests__/common.test.ts
scripts/common.ts

The spread logic is failing https://github.com/algolia/api-clients-automation/actions/runs/5598140574/jobs/10237573027, this is because the `execaCommand` doesn't seem to support multiline arguments, however the `execa` one does.

fix(scripts): execa command for git commits

---

config/generation.config.mjs

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1437
now that we rely on lerna for version bumping, we should allow the package.json to be pushed, which allows us to let the generation read the updates when running `yarn docker:release`
alternatively, we could have this logic only for the release process I believe, but this would introduce much more logic change

fix(javascript): allow package.json to be pushed

---

scripts/release/createReleasePR.ts

release can fail if the branch already exists, we now force and reset the branch if it's the case.

fix(scripts): prevent branch exists error

---

clients/algoliasearch-client-dart/CHANGELOG.md
clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/lib/src/version.dart
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/predict/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.73 -> **`prerelease` _(e.g. 5.0.0-alpha.74)_**
- php: 4.0.0-alpha.71 -> **`prerelease` _(e.g. 4.0.0-alpha.72)_**
- go: 4.0.0-alpha.20 -> **`prerelease` _(e.g. 4.0.0-alpha.21)_**
- dart: 0.1.1+3 -> **`minor` _(e.g. 0.2.0)_**
<details>
<summary>
</summary> …

chore: prepare release 2023-07-19

---

.github/actions/setup/action.yml

cache path is not found for go (see https://github.com/algolia/api-clients-automation/actions/runs/5607959724 on every CI runs)

chore: fix go cache path

---

clients/algoliasearch-client-javascript/package.json
clients/algoliasearch-client-javascript/scripts/publish.ts
clients/algoliasearch-client-javascript/tsconfig.script.json

publish failed (see https://github.com/algolia/algoliasearch-client-javascript/actions/runs/5608097896/jobs/10260028906) as it was expecting a commonjs file

fix(javascript): publish script esm

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/predict/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.74 -> **`prerelease` _(e.g. 5.0.0-alpha.75)_**
- ~java: 4.0.0-SNAPSHOT (no commit)~
- ~php: 4.0.0-alpha.72 (no commit)~
- ~go: 4.0.0-alpha.21 (no commit)~
- dart: 0.1.1+4 -> **`minor` _(e.g. 0.2.0)_**
<details>
<summary>
</summary>
- chore: fix renovate for Dart (#1831)
- chore: fix go cache path (#1785)
</details>
<details>
<summary> …

chore: prepare release 2023-07-25

---

renovate.json

I just realized the regex was still not working https://github.com/algolia/api-clients-automation/issues/539, while being a correct regex, this negative pattern is not supported by RE2.
Since we know we only want stable version, we can just exclude versions with a `-` in it.
see https://regex101.com/r/jgtqJs/1

chore: fix renovate for Dart

---

specs/ingestion/common/schemas/authentication.yml

🎟 JIRA Ticket: [DI-1239](https://algolia.atlassian.net/browse/DI-1239)
- auth input partial descriptions
[DI-1239]: https://algolia.atlassian.net/browse/DI-1239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(specs): allow partial input update for authentications

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java-2/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/predict/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json

- javascript: 5.0.0-alpha.75 -> **`prerelease` _(e.g. 5.0.0-alpha.76)_**
- php: 4.0.0-alpha.72 -> **`prerelease` _(e.g. 4.0.0-alpha.73)_**
- go: 4.0.0-alpha.21 -> **`prerelease` _(e.g. 4.0.0-alpha.22)_**
- dart: 0.1.2 -> **`patch` _(e.g. 0.1.3)_**
<details>
<summary>
</summary>
- …

chore: prepare release 2023-08-01

---

clients/algoliasearch-client-dart/packages/client_core/lib/src/transport/retry_strategy.dart

The current error-throwing logic doesn't stop the retry operations, which it should.
Correctly detect `4xx` errors to immediately stop retrying calls.

fix(dart): correctly rethrow 4xx errors

---

specs/recommend/common/schemas/RecommendationsResponse.yml
specs/search/common/schemas/SearchResponse.yml

`query` and `params` are required for _Search_ (and _Browse_), but not for _Recommend_
Set `query` and `params` as required for _Search_, and as optional for _Recommend_.

fix(specs): optional/required `query` and `params`

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/lib/src/version.dart
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
config/openapitools.json
scripts/release/createReleasePR.ts

- javascript: 5.0.0-alpha.76 -> **`prerelease` _(e.g. 5.0.0-alpha.77)_**
- java: 4.0.0-beta.1 -> **`prerelease` _(e.g. 4.0.0-beta.2)_**
- php: 4.0.0-alpha.73 -> **`prerelease` _(e.g. 4.0.0-alpha.74)_**
- go: 4.0.0-alpha.22 -> **`prerelease` _(e.g. 4.0.0-alpha.23)_**
- dart: 0.1.2+1 -> **`minor` _(e.g. 0.2.0)_**
<details>
<summary> …

chore: prepare release 2023-08-07

---

clients/algoliasearch-client-dart/packages/client_recommend/test/version_test.dart

Each package has a version test that checks if the version in `pubspec.yaml` is the same as the version inside `version.dart`.
Added version test for the package `algolia_client_recommend`.

chore(dart): add recommend version test

---

.github/workflows/check.yml
clients/algoliasearch-client-java/algoliasearch/build.gradle
generators/build.gradle
playground/java/build.gradle
scripts/common.ts
templates/java/tests/build.mustache

Gradle 9 will deprecate the `sourceVersion` so we need to use the new syntax.
Also disable the `generate client` cache on main to always build and run tests.

chore(java): use new gradle syntax

---

clients/algoliasearch-client-javascript/base.rollup.config.js
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
templates/javascript/clients/algoliasearch/lite.mustache
templates/javascript/clients/index.mustache
templates/javascript/clients/package.mustache

contributes to https://github.com/algolia/api-clients-automation/issues/1893, https://github.com/algolia/api-clients-automation/issues/1884
It seems like the issue is to resolve the `cjs.js` extensions, I'll try with full `cjs` output and see how it goes.

fix(javascript): move `cjs.js` to `cjs`

---

clients/algoliasearch-client-java/algoliasearch/gradle.properties

The current java client artifacts are published as `algoliasearch`, `algoliasearch-core`, `algoliasearch-apache`..etc.
- Rename the artifact `algoliasearch` to match the current naming.

chore(java): rename artifact to `algoliasearch`

---

scripts/ci/codegen/spreadGeneration.ts
scripts/release/common.ts
scripts/release/createReleasePR.ts
scripts/release/updateAPIVersions.ts

somehow melos can't force pull tags which makes the script fail locally and requires us to update the tags manually
```
Unhandled exception:
ProcessException: Melos: Failed executing a git command:  From github.com:algolia/api-clients-automation
! [rejected]            released   -> released  (would clobber existing tag)
```
while we could automate this, it would be better if we had a tag for each release instead of overwriting it every time.

feat(scripts): date monorepo released tags

---

clients/algoliasearch-client-java/CHANGELOG.md
config/clients.config.json

- ~javascript: 5.0.0-alpha.80 (no commit)~
- java: 4.0.0-beta.5 -> **`prerelease` _(e.g. 4.0.0-beta.6)_**
- ~php: 4.0.0-alpha.77 (no commit)~
- ~go: 4.0.0-alpha.26 (no commit)~
- ~dart: 0.2.0+2 (no commit)~
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- feat(scripts): date monorepo released …

chore: prepare release 2023-08-22

---

specs/ingestion/common/schemas/run.yml
specs/ingestion/common/schemas/task.yml

Adds the new `failureThreshold` option to the Ingestion API.

feat(specs): add `failureThreshold` to Ingestion API

---

specs/search/paths/keys/common/schemas.yml

🎟 JIRA Ticket: 
[AIE-512](https://algolia.atlassian.net/browse/AIE-512)
The `1/keys` endpoint supports the `inference` ACL and has been deployed to production. See [SRCH-6617](https://algolia.atlassian.net/browse/SRCH-6617). This change updates clients accordingly.
- Add `inference` ACL option
run cts tests
[AIE-512]: https://algolia.atlassian.net/browse/AIE-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SRCH-6617]: https://algolia.atlassian.net/browse/SRCH-6617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add inference ACL to API key object

---

specs/insights/common/schemas/EventAttributes.yml

The character limit for a user token in the Insights API is 129 characters.
I don't know when this was changed, but I tested to verify.
- Fix the `pattern` of the `userToken` parameter in the Insights API to allow up to 129 characters

fix(clients): user token character limit

---

specs/insights/common/schemas/EventAttributes.yml

Follow up of #2003. I forgot to update the `maxLength` attribute. 
- Update the `maxLength` attribute of the `userToken` parameter for the Insights API

fix(clients): userToken max length

---

specs/ingestion/common/schemas/event.yml

In the 'EventStatus' section of the event.yaml schema, the enum list of possible events has been expanded to include a new status, 'critical'. This change is designed to more accurately categorize and track the nature of events for better system monitoring and debugging.

fix(specs): add 'critical' event status to enum

---

specs/ingestion/common/schemas/destination.yml
specs/ingestion/common/schemas/source.yml

To improve clarity and code readability, the 'SourceDocker' was renamed to 'SourceUpdateDocker'. The required property 'configuration' was moved to SourceUpdateDocker, while the 'imageType' property now exists in both the SourceUpdateDocker and SourceDocker. In addition, SourceDocker now includes a reference to SourceUpdateDocker. These changes ensure a more logical and understandable schema structure.

fix(specs): introduced SourceUpdateDocker

---

specs/search/common/schemas/SearchResponse.yml

- Mark `exhaustiveNbHits` as optional

fix(specs): `exhaustiveNbHits` as optional

---

clients/algoliasearch-client-dart/.github/workflows/publish.yml
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
config/clients.config.json
config/openapitools.json
generators/src/main/java/com/algolia/codegen/AlgoliaDartGenerator.java
generators/src/main/java/com/algolia/codegen/Utils.java
package.json
scripts/release/createReleasePR.ts
scripts/release/updateAPIVersions.ts
website/docs/contributing/release-process.md

Dart release process is broken, and since we now sync versions between all packages, we can keep the same package bumping logic as the other clients.
also close https://github.com/algolia/api-clients-automation/pull/1890

feat(scripts): sync dart client versions

---

config/generation.config.mjs
generators/src/main/java/com/algolia/codegen/AlgoliaDartGenerator.java
templates/dart/pubspec.mustache

some `core` dart files were not generated on release, meaning their version is not bumped.
this PR adds them to the list so we don't have to do it manually anymore.

fix(scripts): generate some core files

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json

- javascript: 5.0.0-alpha.82 -> **`prerelease` _(e.g. 5.0.0-alpha.83)_**
- java: 4.0.0-beta.4 -> **`prerelease` _(e.g. 4.0.0-beta.5)_**
- php: 4.0.0-alpha.79 -> **`prerelease` _(e.g. 4.0.0-alpha.80)_**
- go: 4.0.0-alpha.28 -> **`prerelease` _(e.g. 4.0.0-alpha.29)_**
- dart: 0.2.1 -> **`patch` _(e.g. 0.2.2)_**
<details>
<summary>
</summary> …

chore: prepare release 2023-09-14

---

clients/algoliasearch-client-dart/README.md

- There is a typo in the flutter command for dart client
- Correct typo (s/algoliasearch/algoliasearch) in README for dart client

fix(dart): correct typo in readme

---

clients/algoliasearch-client-dart/README.md
clients/algoliasearch-client-dart/packages/algoliasearch/README.md

I found some more typos in various README for the dart client:
```
find . -type f -exec grep -li 'algolis' \{\} \;
./clients/algoliasearch-client-dart/README.md
./clients/algoliasearch-client-dart/packages/algoliasearch/README.md
```
- Corrected all remaining instances of `algolisearch` in README files.

fix(dart): correct multiple additional typos in READMEs

---

clients/algoliasearch-client-dart/packages/client_core/lib/src/transport/retry_strategy.dart

- Reset and use hosts for the call type only.

fix(dart): reset only hosts w/ call type

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json

- javascript: 5.0.0-alpha.83 -> **`prerelease` _(e.g. 5.0.0-alpha.84)_**
- ~java: 4.0.0-beta.5 (no commit)~
- ~php: 4.0.0-alpha.80 (no commit)~
- ~go: 4.0.0-alpha.29 (no commit)~
- dart: 0.2.2 -> **`patch` _(e.g. 0.2.3)_**
<details>
<summary>
</summary>
</details>
<details>
<summary>
</summary>
- chore(deps): dependencies …

chore: prepare release 2023-09-18

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json

- javascript: 5.0.0-alpha.84 -> **`prerelease` _(e.g. 5.0.0-alpha.85)_**
- ~java: 4.0.0-beta.5 (no commit)~
- ~php: 4.0.0-alpha.80 (no commit)~
- ~go: 4.0.0-alpha.29 (no commit)~
- ~dart: 0.2.3 -> **`patch` _(e.g. 0.2.4)_**~
-   - No `feat` or `fix` commit, thus unchecked by default.
_(None)_

chore: prepare release 2023-09-20

---

specs/ingestion/common/schemas/destination.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1501
This PR adds the new `attributesToExclude` property to the Ingestion specs.

feat(specs): add `attributesToExclude` for Ingestion

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json

- javascript: 5.0.0-alpha.85 -> **`prerelease` _(e.g. 5.0.0-alpha.86)_**
- java: 4.0.0-beta.5 -> **`prerelease` _(e.g. 4.0.0-beta.6)_**
- php: 4.0.0-alpha.80 -> **`prerelease` _(e.g. 4.0.0-alpha.81)_**
- go: 4.0.0-alpha.29 -> **`prerelease` _(e.g. 4.0.0-alpha.30)_**
- dart: 0.2.3 -> **`minor` _(e.g. 0.3.0)_**
<details>
<summary>
</summary> …

chore: prepare release 2023-09-28

---

generators/src/main/java/com/algolia/codegen/cts/AlgoliaCTSGenerator.java
generators/src/main/java/com/algolia/codegen/cts/lambda/EscapeDollarLambda.java
generators/src/main/java/com/algolia/codegen/cts/tests/TestsRequest.java
specs/insights/common/enums.yml
specs/insights/common/schemas/AddToCartEvent.yml
specs/insights/common/schemas/AddedToCartObjectIDs.yml
specs/insights/common/schemas/AddedToCartObjectIDsAfterSearch.yml
specs/insights/common/schemas/EventAttributes.yml
specs/insights/common/schemas/EventsItems.yml
specs/insights/common/schemas/PurchaseEvent.yml
specs/insights/common/schemas/PurchasedObjectIDs.yml
specs/insights/common/schemas/PurchasedObjectIDsAfterSearch.yml
templates/dart/tests/param_value.mustache
tests/CTS/methods/requests/insights/pushEvents.json

🎟 JIRA Ticket: [APIC-716](https://algolia.atlassian.net/browse/APIC-716)
Add the 4 new types of events for insights:
- `AddedToCartObjectIDs`
- `AddedToCartObjectIDsAfterSearch`
- `PurchasedObjectIDs`
- `PurchasedObjectIDsAfterSearch`
[APIC-716]: https://algolia.atlassian.net/browse/APIC-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add new events type for insights

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json

- javascript: 5.0.0-alpha.86 -> **`prerelease` _(e.g. 5.0.0-alpha.87)_**
- java: 4.0.0-beta.6 -> **`prerelease` _(e.g. 4.0.0-beta.7)_**
- php: 4.0.0-alpha.81 -> **`prerelease` _(e.g. 4.0.0-alpha.82)_**
- go: 4.0.0-alpha.30 -> **`prerelease` _(e.g. 4.0.0-alpha.31)_**
- dart: 0.3.0 -> **`minor` _(e.g. 0.4.0)_**
<details>
<summary>
</summary> …

chore: prepare release 2023-10-10

---

config/generation.config.mjs
scripts/release/createReleasePR.ts

🎟 JIRA Ticket:
there was a change in this file which made the release script unable to push package.json, this means versions became unsync'd at some point.
this should do the trick to allow release process changes, but prevent it in normal

fix(javascript): release process

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json
scripts/package.json
scripts/release/createReleasePR.ts

- javascript: 5.0.0-alpha.87 -> **`prerelease` _(e.g. 5.0.0-alpha.88)_**
- ~java: 4.0.0-beta.7 (no commit)~
- ~php: 4.0.0-alpha.82 (no commit)~
- ~go: 4.0.0-alpha.31 (no commit)~
- ~dart: 0.4.0 (no commit)~
_(None)_

chore: prepare release 2023-10-11

---

specs/abtesting/common/parameters.yml
specs/abtesting/common/schemas/ABTest.yml
specs/abtesting/common/schemas/Variant.yml

🎟 JIRA Ticket: [OPTIM-748]
- Fix `endAt` typing on `ABTest`
- Add Revenue typing for purchase, addToCart, and revenue significance, as well as metrics for `currencies` 
- Add `filterEffects` to display outlier data, taking the place of `outlier...Count` properties
- Add `configuration` on abtest creation `post` and retrieval `get` and `list`
Green CI
[OPTIM-748]: https://algolia.atlassian.net/browse/OPTIM-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): revenue and filterEffects typing updates

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json

- javascript: 5.0.0-alpha.88 -> **`prerelease` _(e.g. 5.0.0-alpha.89)_**
- java: 4.0.0-beta.7 -> **`prerelease` _(e.g. 4.0.0-beta.8)_**
- php: 4.0.0-alpha.82 -> **`prerelease` _(e.g. 4.0.0-alpha.83)_**
- go: 4.0.0-alpha.31 -> **`prerelease` _(e.g. 4.0.0-alpha.32)_**
- dart: 0.4.0 -> **`minor` _(e.g. 0.5.0)_**
_(None)_

chore: prepare release 2023-10-12

---

specs/search/paths/rules/common/parameters.yml
specs/search/paths/rules/rule.yml

this removes the warning discovered by @shortcuts, two parameters were named `objectID` and redocly didn't like that

fix(specs): remove duplicate objectID

---

templates/java/api_helpers.mustache

🎟 JIRA Ticket: DI-1591
Add search helpers `searchForHits` and `searchForFacets` (with sync/async variants) to java client

feat(java): add search helpers `searchForHits` and `searchForFacets`

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json

- javascript: 5.0.0-alpha.90 -> **`prerelease` _(e.g. 5.0.0-alpha.91)_**
- java: 4.0.0-beta.10 -> **`prerelease` _(e.g. 4.0.0-beta.11)_**
- php: 4.0.0-alpha.84 -> **`prerelease` _(e.g. 4.0.0-alpha.85)_**
- go: 4.0.0-alpha.33 -> **`prerelease` _(e.g. 4.0.0-alpha.34)_**
- kotlin: 3.0.0-beta.3 -> **`prerelease` _(e.g. 3.0.0-beta.4)_**
- dart: 1.0.0 -> **`minor` _(e.g. 1.1.0)_**
<details>
<summary> …

chore: prepare release 2023-11-06

---

specs/ingestion/common/schemas/common.yml
specs/ingestion/common/schemas/run.yml
specs/ingestion/paths/runs/events/events.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1639
adds the new window parameters in the observability response

feat(specs): add `window` parameter to observability responses

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json
scripts/release/createReleasePR.ts

- javascript: 5.0.0-alpha.91 -> **`prerelease` _(e.g. 5.0.0-alpha.92)_**
- java: 4.0.0-beta.11 -> **`prerelease` _(e.g. 4.0.0-beta.12)_**
- php: 4.0.0-alpha.85 -> **`prerelease` _(e.g. 4.0.0-alpha.86)_**
- go: 4.0.0-alpha.34 -> **`prerelease` _(e.g. 4.0.0-alpha.35)_**
- kotlin: 3.0.0-beta.4 -> **`prerelease` _(e.g. 3.0.0-beta.5)_**
- dart: 1.1.0 -> **`minor` _(e.g. 1.2.0)_**
_(None)_

chore: prepare release 2023-11-09

---

scripts/release/common.ts

we can't release many times a day, see https://github.com/algolia/api-clients-automation/actions/runs/6811827099/job/18523360577 because of the tag pattern https://github.com/algolia/api-clients-automation/tags
let's go full date since those release tags are just used for internal purposes, it's fine

fix(scripts): release with full hours

---

clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1646
this PR reverts the two failed releases, the last valid ones was https://github.com/algolia/api-clients-automation/releases/tag/released-2023-11-09, anything after that hasn't be published

chore: revert failed releases

---

clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
config/clients.config.json

- javascript: 5.0.0-alpha.92 -> **`prerelease` _(e.g. 5.0.0-alpha.93)_**
- ~java: 4.0.0-beta.12 (no commit)~
- php: 4.0.0-alpha.86 -> **`prerelease` _(e.g. 4.0.0-alpha.87)_**
- go: 4.0.0-alpha.35 -> **`prerelease` _(e.g. 4.0.0-alpha.36)_**
- kotlin: 3.0.0-beta.5 -> **`prerelease` _(e.g. 3.0.0-beta.6)_**
- ~dart: 1.2.0 (no commit)~
<details>
<summary>
</summary>
- chore: revert failed release (#2260)
- …

chore: prepare release 2023-11-13

---

templates/go/api.mustache

Discovered during the hackathon, the response from algolia can be null if there is an error.

fix(go): check for NPE

---

scripts/ci/githubActions/createMatrix.ts
scripts/ci/githubActions/setRunVariables.ts

this PR proposes to loose the cache key computing by providing more "common" dependencies to the jobs to run. In https://github.com/algolia/api-clients-automation/pull/2369 I had to bump the cache >3 times, which can be a blocker for new contributors and also slow us rather than speed up our CI builds since we need to run it many times.

chore: loose cache key

---

clients/algoliasearch-client-python/algoliasearch/http/api_response.py
templates/python/api.mustache

Since the deserializing logic is fully hardcoded it can live in the API response class directly for easier usage and iterations
also fix missing parameter when not using the read transporter

fix(python): common response deserializer

---

renovate.json

just realized it did not worked because that's not the correct filename, also remove `poetry` from the automated managers because we only want to update the templates

chore: renovate for Python

---

generators/src/main/java/com/algolia/codegen/cts/tests/TestsRequest.java
scripts/cts/runCts.ts
scripts/formatter.ts
tests/output/python/poetry.lock

for simplicity, we can append the test index to the operationID when no test name are provided, this avoid tests having the same name and/or forcing the contributor to provide a testName (description)
discovered in https://github.com/algolia/api-clients-automation/pull/2411 and https://github.com/algolia/api-clients-automation/pull/2401

chore(cts): add index to default test name

---

templates/ruby/base_object.mustache
templates/ruby/partial_model_generic.mustache

Some models can have arbitrary keys, my previous solution only worked for `x-is-generic`, but this works for everything.

fix(ruby): support additionalProperties: true

---

clients/algoliasearch-client-csharp/CHANGELOG.md
clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
clients/algoliasearch-client-python/CHANGELOG.md
clients/algoliasearch-client-ruby/CHANGELOG.md
clients/algoliasearch-client-scala/CHANGELOG.md
config/clients.config.json

- javascript: 5.0.0-alpha.93 -> **`prerelease` _(e.g. 5.0.0-alpha.94)_**
- java: 4.0.0-beta.12 -> **`prerelease` _(e.g. 4.0.0-beta.13)_**
- php: 4.0.0-alpha.87 -> **`prerelease` _(e.g. 4.0.0-alpha.88)_**
- go: 4.0.0-alpha.37 -> **`prerelease` _(e.g. 4.0.0-alpha.38)_**
- kotlin: 3.0.0-beta.6 -> **`prerelease` _(e.g. 3.0.0-beta.7)_**
- dart: 1.2.0 -> **`patch` _(e.g. 1.2.1)_**
- python: 4.0.0a1 -> **`minor` _(e.g. 4.0.0a2)_**
- ruby: 3.0.0.alpha.0 -> **`minor` _(e.g. 3.0.0.alpha.1)_**
- scala: 2.0.0-alpha.1 -> **`prerelease` _(e.g. 2.0.0-alpha.2)_**
- csharp: 7.0.0-alpha.0 -> **`prerelease` _(e.g. 7.0.0-alpha.1)_**
<p>It doesn't mean these …

chore: prepare release 2023-12-28

---

clients/algoliasearch-client-python/CHANGELOG.md
clients/algoliasearch-client-ruby/CHANGELOG.md
config/clients.config.json

- ~javascript: 5.0.0-alpha.94 (no commit)~
- ~java: 4.0.0-beta.13 (no commit)~
- ~php: 4.0.0-alpha.88 (no commit)~
- ~go: 4.0.0-alpha.38 (no commit)~
- ~kotlin: 3.0.0-beta.7 (no commit)~
- ~dart: 1.2.1 (no commit)~
- python: 4.0.0a2 -> **`minor` _(e.g. 4.0.0a3)_**
- ruby: 3.0.0.alpha.1
- ~scala: 2.0.0-alpha.2 (no commit)~
- ~csharp: 7.0.0-alpha.1 (no commit)~
<details>
<summary>
</summary>
- chore: …

chore: prepare release 2024-01-02

---

scripts/ci/githubActions/createMatrix.ts

see ci failure on main: https://github.com/algolia/api-clients-automation/actions/runs/7400572570/attempts/1
the ci thinks it should run `client_gen` because `shouldRun` is `true` since it is computed computed before we filter javascript from the matrix to put it in its own

chore(ci): compute shouldRun after filtering

---

clients/algoliasearch-client-csharp/CHANGELOG.md
clients/algoliasearch-client-dart/packages/algoliasearch/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_core/pubspec.yaml
clients/algoliasearch-client-dart/packages/client_insights/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_recommend/CHANGELOG.md
clients/algoliasearch-client-dart/packages/client_search/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
clients/algoliasearch-client-python/CHANGELOG.md
clients/algoliasearch-client-ruby/CHANGELOG.md
clients/algoliasearch-client-scala/CHANGELOG.md
config/clients.config.json

- javascript: 5.0.0-alpha.94 -> **`prerelease` _(e.g. 5.0.0-alpha.95)_**
- java: 4.0.0-beta.13 -> **`prerelease` _(e.g. 4.0.0-beta.14)_**
- php: 4.0.0-alpha.88 -> **`prerelease` _(e.g. 4.0.0-alpha.89)_**
- go: 4.0.0-alpha.38 -> **`prerelease` _(e.g. 4.0.0-alpha.39)_**
- kotlin: 3.0.0-beta.7 -> **`prerelease` _(e.g. 3.0.0-beta.8)_**
- dart: 1.2.1 -> **`patch` _(e.g. 1.2.2)_**
- python: 4.0.0a4 -> **`patch` _(e.g. 4.0.0a5)_**
- ruby: 3.0.0.alpha.1 -> **`patch` _(e.g. 3.0.0.alpha.2)_**
- scala: 2.0.0-alpha.2 -> **`prerelease` _(e.g. 2.0.0-alpha.3)_**
- csharp: 7.0.0-alpha.1 -> **`prerelease` _(e.g. 7.0.0-alpha.2)_**
<p>It doesn't mean these …

chore: prepare release 2024-01-04

---

specs/search/common/schemas/SearchForFacetValuesResponse.yml
specs/search/common/schemas/SearchResponse.yml
templates/python/tests/requests/requests.mustache
tests/CTS/requests/search/getSettings.json

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1748
We now deserialize responses in the generated models for Python, pydantic would raise an error if it failed
Also fix the search for facet values response which was missing properties

feat(clients): deserialize in e2e and SFFV response

---

clients/algoliasearch-client-python/algoliasearch/http/transporter.py
config/generation.config.mjs
generators/src/main/java/com/algolia/codegen/AlgoliaPythonGenerator.java
templates/python/api.mustache

_This PR applies the feedback from @kai687's review_

feat(python): improve docstring and fix transporter errors

---

clients/algoliasearch-client-python/CHANGELOG.md
clients/algoliasearch-client-ruby/CHANGELOG.md
config/clients.config.json
scripts/release/createReleasePR.ts

- ~java: 4.0.0-beta.16 (no commit)~
- ~javascript: 5.0.0-alpha.97 (no commit)~
- ~php: 4.0.0-alpha.91 (no commit)~
- ~go: 4.0.0-alpha.41 (no commit)~
- ~kotlin: 3.0.0-beta.10 (no commit)~
- ~dart: 1.3.0 (no commit)~
- python: 4.0.0a7 -> **`patch` _(e.g. 4.0.0b1)_**
- ruby: 3.0.0.alpha.3 -> **`patch` _(e.g. 3.0.0.alpha.4)_**
- ~scala: 2.0.0-alpha.4 (no commit)~
- ~csharp: 7.0.0-alpha.3 (no commit)~
_(None)_

chore: prepare release 2024-01-09

---

scripts/configReplacer.cjs
scripts/package.json
scripts/tsconfig.json
yarn.lock

By default, we need to rebuild the scripts everytime we change the the config files, but this is less than ideal.
The only way I found to fix it was by using a library, `tsc-alias`, that will replace after the transpilation every reference to `../config` with `../../../config` to fetch the original file.
Using `paths`, or `dynamic import` didn't work

chore(scripts): replace config path

---

clients/algoliasearch-client-ruby/algolia.gemspec

The published gem was 5.4MB instead of the expected `300KB`, because I forgot to remove files excluded by git.

fix(ruby): exclude vendor from bundled gem

---

scripts/docker/setup.sh

you can't setup docker with fish actually because it sets the env var from substitutions, but with bass (fish plugin) it works if we use export directly in the script we are running

chore: support fish for setup

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json

- ~csharp: 7.0.0-alpha.4 (no commit)~
- ~dart: 1.4.0 (no commit)~
- ~go: 4.0.0-alpha.42 (no commit)~
- ~java: 4.0.0-beta.17 (no commit)~
- javascript: 5.0.0-alpha.98 -> **`prerelease` _(e.g. 5.0.0-alpha.99)_**
- ~kotlin: 3.0.0-beta.11 (no commit)~
- ~php: 4.0.0-alpha.92 (no commit)~
- ~python: 4.0.0b2 (no commit)~
- ~ruby: 3.0.0.alpha.5 (no commit)~
- ~scala: 2.0.0-alpha.5 (no commit)~
- ~swift: 9.0.0-alpha.1 (no commit)~
_(None)_

chore: prepare release 2024-01-16

---

.github/workflows/pr-title.yml
templates/csharp/snippets/method.mustache

snippets include index of the test which doesn't have much context here, we can use the client name instead to prevent duplicated defintions

snippets: remove index from csharp

---

clients/algoliasearch-client-ruby/lib/algolia/api_client.rb
package.json
playground/ruby/Gemfile.lock
playground/ruby/search.rb
templates/ruby/api.mustache
templates/ruby/base_object.mustache
templates/ruby/partial_anyof_module.mustache
templates/ruby/partial_oneof_module.mustache
templates/ruby/tests/requests/requests.mustache
tests/output/ruby/test/helpers.rb

The ruby client was broken because of the change of namespaces.

fix(ruby): correct oneOf deserialization

---

.github/actions/setup/action.yml

Just like [golangci-lint-action](https://github.com/golangci/golangci-lint-action), we can cache the results of `golangci-lint` (about 10MB) and have a huge speed up when linting.
Of course this is dwarfed by swift :(

chore(ci): cache golangci-lint

---

generators/build.gradle
generators/src/main/java/com/algolia/codegen/AlgoliaCSharpGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaDartGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaGoGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaJavaGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaJavascriptGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaKotlinGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaPhpGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaPythonGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaRubyGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaScalaGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaSwiftGenerator.java
generators/src/main/java/com/algolia/codegen/utils/Helpers.java
templates/java/api.mustache

Following #2561, use the correct url for java, and rework the generators to use the already read spec file, and the correct types for servers.

fix(java): correct url for monitoring client

---

generators/src/main/java/com/algolia/codegen/AlgoliaPhpGenerator.java
generators/src/main/java/com/algolia/codegen/utils/Helpers.java
templates/csharp/Configuration.mustache
templates/dart/api.mustache
templates/go/client.mustache
templates/java/api.mustache
templates/javascript/clients/api-single.mustache
templates/javascript/clients/client/api/hosts.mustache
templates/kotlin/api.mustache
templates/kotlin/snippets/method.mustache
templates/php/api.mustache
templates/python/config.mustache
templates/ruby/api.mustache
templates/scala/api.mustache

Do the rest of the languages for #2561 , and add a new variable to make the templates more readable.

fix(clients): support the rest of the languages

---

config/clients.config.json
scripts/snippets/generate.ts
snippets/go/.golangci.yml
snippets/go/go.mod
templates/go/snippets/method.mustache

snippets(go): add snippets

---

clients/algoliasearch-client-ruby/algolia.gemspec
clients/algoliasearch-client-ruby/lib/algolia/api_client.rb
clients/algoliasearch-client-ruby/lib/algolia/transport/transport.rb
playground/ruby/search.rb
templates/ruby/api.mustache
templates/ruby/search_helpers.mustache

🎟 JIRA Ticket: [DI-1744](https://algolia.atlassian.net/browse/DI-1744)
First batch of helpers for ruby, with `wait_for_task` and `wait_for_api_key` !
[DI-1744]: https://algolia.atlassian.net/browse/DI-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ruby): add wait helpers

---

specs/query-suggestions/paths/getConfigurationStatus.yml
specs/query-suggestions/paths/getLogFile.yml
specs/query-suggestions/paths/qsConfig.yml
specs/query-suggestions/paths/qsConfigs.yml

Adding the ACLs to the QS api endpoints spec. Reference is https://github.com/algolia/go/blob/master/cmd/query-suggestions/query-suggestions-api/service/service.go

feat(specs): add acls to API endpoints

---

.github/actions/setup/action.yml

`setup-java` cache is a bit broken and takes more than 2 minutes in the `Post Setup` job to save to disk.
Using `setup-gradle` seems to be recommend, [here](https://github.com/gradle/gradle/issues/13510#issuecomment-1913366548) and [here](https://github.com/actions/setup-java/issues/588)

chore(ci): use setup-gradle to handle cache

---

specs/common/schemas/HighlightResult.yml
specs/common/schemas/SnippetResult.yml
templates/go/model_simple.mustache
templates/java/api_helpers.mustache
templates/java/snippets/method.mustache
templates/java/tests/requests/requests.mustache
templates/javascript/tests/package.mustache
tests/CTS/requests/search/searchSingleIndex.json

[DI-1797](https://algolia.atlassian.net/browse/DI-1797)
Snippet results can be an array sometimes ! This tests ensure that we can deserialize it properly.
Also applies to highlight result
[DI-1797]: https://algolia.atlassian.net/browse/DI-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(cts): add test for _snippetResult

---

config/clients.config.json
scripts/pre-gen/removeExistingCodegen.ts

Correctly remove Models and Api client before `gen`
🎟 JIRA Ticket: [DI-1811](https://algolia.atlassian.net/browse/DI-1811)
⚠️  `fsp.rm` do not seems to correctly manage wildcard. Deleting a folder works well, deleting files using wildcard does not.
[DI-1811]: https://algolia.atlassian.net/browse/DI-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(csharp): correctly clean code gen

---

clients/algoliasearch-client-swift/Sources/Core/Common/Credentials.swift

fix(swift): appID casing

---

.github/workflows/check.yml
clients/algoliasearch-client-php/composer.lock
templates/php/composer.mustache

🎟 JIRA Ticket: DI-1822
Following the feedback from the Magento team, we want to rollback the `psr/http-message` dependency by including the 1.1 version to allow them to use the generated PHP client in Magento.

fix(php): revert restriction for psr/http-message dependency

---

clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/extensions/SearchClient.kt

Simplify the return type to return the list of operations.
Return the list of intermediate task IDs.

fix(kotlin): return `replaceAllObjects`'s intermediate operations 

---

tests/CTS/requests/analytics/getTopSearches.json

Simple e2e to make sure the analytics API is called correctly, and that query params encoding is working properly.
Note: the scope of the PR is not very correct but it's just to trigger a release of all languages.

fix(clients): add e2e tests for analytics API

---

clients/algoliasearch-client-csharp/algoliasearch/Utils/ClientExtensions.cs
playground/python/app/search.py
templates/javascript/clients/client/api/helpers.mustache
templates/python/search_helpers.mustache

🎟 JIRA Ticket:
Catched by fluffman the page parameter doesn't exist in the synonyms response

fix(clients): browse synonyms page not in response

---

templates/javascript/clients/client/model/clientMethodProps.mustache

the automerge merged before I fix, this option should be available on both method not just the chunked one

fix(javascript): allow `batchSize` on `ReplaceAllObjectsOptions`

---

specs/ingestion/common/schemas/source.yml

🎟 JIRA Ticket: DI-1788
- Add missing attributes `url` and `fallbackIsInStockValue` for CT Source Update

fix(specs): add missing attributes for CT Source update

---

clients/algoliasearch-client-csharp/algoliasearch/Utils/SearchClientExtensions.cs

Move `SearchClient` extensions into instance functions.

refactor(csharp): move client search extensions to instance method

---

scripts/buildSpecs.ts

The normal spec was linted when building the doc spec, resulting in absolute chaos

fix(scripts): lint the correct bundled spec

---

templates/javascript/clients/client/model/types/dataType.mustache

discovered while testing on the crawler, the js template doesn't use the correct vendor extensions values (see https://github.com/algolia/api-clients-automation/blob/main/clients/algoliasearch-client-javascript/packages/client-search/model/searchHits.ts), meaning generics are broken

fix(javascript): use correct vendor values

---

clients/algoliasearch-client-scala/.github/workflows/release.yml
clients/algoliasearch-client-scala/build.sbt

At Scala client release time, gpg key is not used correctly.
- Attempt to fix gpg signing 
- Add logging (list installed pgp keys)

chore(scala): fix scala release ci

---

clients/algoliasearch-client-swift/Sources/Search/Extra/SearchHelpers.swift

- fix `replaceAllObjects` helper by waiting for tasks in the `chunkedBatch` method

fix(swift): wait for tasks while sending chunk batches

---

specs/ingestion/common/schemas/source.yml
specs/ingestion/common/schemas/task.yml
specs/ingestion/common/taskParameters.yml

GA4 BigQuery Export task type was added.
🎟 JIRA Ticket: EEX-1055
- Add `ga4BigqueryExport` task type
- Add `streaming` trigger type
- Add `append` action type

feat(specs): add ga4BigqueryExport, streaming and append options to task inputs

---

website/docusaurus.config.js

A small change to improve the labels for the specs in the navbar, for now 'Query Suggestions', and 'A/B testing'.

docs: better navbar labels

---

.github/workflows/check.yml
scripts/ci/githubActions/createMatrix.ts

- only run the Swift CTS on macOS if the CI is running on the main branch

fix(ci): run the swift cts on mac only on the main branch

---

scripts/pre-gen/removeExistingCodegen.ts

removeExistingCode was not targeting the correct folder for js and dart.

fix(scripts): correctly remove codegen for js and dart

---

.github/workflows/check.yml
generators/src/main/java/com/algolia/codegen/AlgoliaSwiftGenerator.java

- fix the blocking issue (problems below will be adressed in a later PR)
- ~check for forgotten source file duplicates~
- ~change directory before running the podspec linting~

fix(swift): harden macOS CI

---

.github/workflows/check.yml

- wasn't targeting the right variable of the github context

fix(swift): try fixing swift cts specific ci

---

scripts/buildSpecs.ts
scripts/types.ts

Add a separate `label` property to the `x-codeSamples` array.
This lets us use `lang` for the syntax highlighting grammar and an arbitrary `label`.
For now, this is only useful to render `C#` instead of `CSharp`.
See: [`x-codeSamples` (Redocly)](https://redocly.com/docs/api-reference-docs/specification-extensions/x-code-samples/).
🎟 JIRA Ticket:
- Rename `mapLanguagesToCodeSampleSupporter` to `getCodeSampleLabel` and return `C#` when the language is `csharp`.

docs: separate labels for code samples

---

clients/algoliasearch-client-scala/.github/workflows/release.yml

Publishing operation is run multiple times. This is required only once.
Remove `+` prefix, which is used to run the same command for each target scala version.
We need to run `sonatypeBundleRelease` only once.

chore(scala): publish artifacts once

---

templates/go/search_helpers.mustache

fix(go): typo in method name

---

templates/go/api.mustache
templates/go/search_helpers.mustache
templates/go/tests/requests/helpers.mustache
templates/go/tests/requests/requests.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1898
- Add `GetSecuredApiKeyRemainingValidity` helper
- Add tests for `GetSecuredApiKeyRemainingValidity` and `GenerateSecuredApiKey`

feat(go): add `GetSecuredApiKeyRemainingValidity` helper, fix `GenerateSecuredApiKey` encoding

---

templates/go/search_helpers.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1843
- Add `ReplaceAllObjects` helper
- Add `ChunkedBatch` helper
I'll add helper tests asap but the mock part discouraged me so brb

feat(go): add `ChunkedBatch` and `ReplaceAllObjects`

---

.github/workflows/check.yml

- Revert back to a previous working workflow

fix(swift): update CI workflow to a previous working state

---

clients/algoliasearch-client-swift/.github/workflows/release.yml
templates/swift/Package.mustache

- add privacy file in SPM
- invert gh release and cocoapods release so the tag exists

fix(swift): include privacy file in spm

---

clients/algoliasearch-client-swift/CHANGELOG.md
config/clients.config.json

- ~csharp: 7.0.0-alpha.7 (no commit)~
- ~dart: 1.6.3 (no commit)~
- ~go: 4.0.0-beta.10 (no commit)~
- ~java: 4.0.0-beta.28 (no commit)~
- ~javascript: 5.0.0-alpha.112 (no commit)~
- ~kotlin: 3.0.0-beta.23 (no commit)~
- ~php: 4.0.0-alpha.104 (no commit)~
- ~python: 4.0.0b13 (no commit)~
- ~ruby: 3.0.0.alpha.16 (no commit)~
- ~scala: 2.0.0-alpha.15 (no commit)~
- swift: 9.0.0-alpha.2 -> **`prerelease` _(e.g. 9.0.0-alpha.3)_**
<details> …

chore: prepare release 2024-04-03

---

.github/workflows/check.yml

codegen is skipped when only touching specs that don't impact clients, see [this](https://github.com/algolia/api-clients-automation/actions/runs/8551115939/job/23429436694) for example, this pr fixes it, see https://github.com/algolia/api-clients-automation/pull/2957

chore: run codegen anytime

---

website/docs/contributing/add-new-api-client.md
website/docs/contributing/docs.md
website/docusaurus.config.js
website/package.json
website/sidebars.js
website/src/css/custom.css
website/yarn.lock

Improve contribution guidelines for adding new clients and the documentation aspects of it.
- Edit the "Add new clients" guide to give it a clearer structure and edit for style.
- Add a new "docs" guide to define elements where we want to achieve consistent docs.
- Add the `remark-smartypants` plugin to render straight quotes as "correct" quotes.
- Left-align table headers (looks better IMO)
I'll update the specs to follow these guidelines in a separate PR.

docs: contribution guide for docs

---

.github/actions/setup/action.yml

Uses a workaround for https://github.com/swift-actions/setup-swift/issues/591 developer by a GitHub staff member and used in https://github.com/github/codeql/pull/16153

fix(ci): use workaround for Swift setup action

---

specs/ingestion/common/schemas/source.yml
specs/ingestion/common/schemas/task.yml

🎟 JIRA Ticket: [DI-1916]
- Update Shopify source input
- Update Shopify task input
[DI-1916]: https://algolia.atlassian.net/browse/DI-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): update shopify source and task inputs

---

CODEOWNERS

order is important apparently https://github.com/orgs/community/discussions/23644

chore: change CODEOWNERS order

---

generators/src/main/java/com/algolia/codegen/AlgoliaPythonGenerator.java
generators/src/main/java/com/algolia/codegen/cts/tests/ParametersWithDataType.java
specs/common/schemas/IndexSettings.yml
specs/common/schemas/SearchParams.yml
templates/go/tests/requests/requests.mustache
templates/python/tests/requests/requests.mustache
templates/ruby/base_object.mustache
tests/CTS/requests/search/search.json

Use recursive types to avoid creating in unnecessary oneOf and allow to use the full potential of the filters

fix(specs): simplify filter types

---

website/docs/contributing/docs.md

This PR updates the guidelines for writing long descriptions.
Essentially, don't use Markdown in the first sentence/paragraph in the descriptions.
The Algolia CLI uses the Search API spec to generate flags from the API parameter/index settings. The help text is generated from the first sentence of the `description` key.
It looks better on the command line if the help text doesn't contain Markdown.
For the most part, I already updated the specs with that in mind. There are some Markdown links, but they will be automatically removed when generating the flags and help text.

docs: update contribution guideline

---

specs/search/common/schemas/SearchForFacetValuesResponse.yml
specs/search/common/schemas/SearchResponse.yml

The `exhaustiveFacetsCount` property is considered deprecated in the Search response,
and users should rely on `exhaustive.facetsCount` instead.
The response from Search for facet values doesn't have an `exhaustive` object,
so `exhaustiveFacetsCount` can't be deprecated and we need to use different descriptions in both cases.
🎟 JIRA Ticket:
- Don't reuse the definition of `exhaustiveFacetsCount`, but inline them for the Search and Search for facet values responses, not marking it deprecated in the Sffv response.

fix(specs): exhaustiveFacetsCount is not deprecated for sffv

---

specs/search/paths/advanced/getAppTask.yml
specs/search/spec.yml
tests/CTS/requests/search/getAppTask.json

🎟 JIRA Ticket: [DI-2437](https://algolia.atlassian.net/browse/DI-2437)
Add the `/1/task/{taskID}` endpoint to wait for an application level task
[DI-2437]: https://algolia.atlassian.net/browse/DI-2437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add getAppTask endpoint to search

---

specs/search/common/schemas/Hit.yml

According to the doc examples, `promoted`, `words` and `filters` are not required on the `rankingInfo` response, and it's blocking on the dart client: https://github.com/algolia/algoliasearch-client-dart/issues/6

fix(specs): rankingInfo required properties

---

clients/algoliasearch-client-csharp/algoliasearch/Utils/SearchClientExtensions.cs
clients/algoliasearch-client-dart/packages/client_search/lib/src/extension/wait_task.dart
clients/algoliasearch-client-kotlin/client/src/commonMain/kotlin/com/algolia/client/extensions/SearchClient.kt
clients/algoliasearch-client-scala/src/main/scala/algoliasearch/extension/package.scala
clients/algoliasearch-client-swift/Sources/Search/Extra/SearchClientExtension.swift
templates/go/search_helpers.mustache
templates/java/api_helpers.mustache
templates/javascript/clients/client/api/helpers.mustache
templates/javascript/clients/client/api/imports.mustache
templates/javascript/clients/client/model/clientMethodProps.mustache
templates/php/api.mustache
templates/python/search_helpers.mustache
templates/ruby/search_helpers.mustache
website/docs/clients/guides/manage-dictionary-entries.mdx
website/src/components/CodeBlockLanguage.js
website/src/snippets.js

Add the `waitForAppTask` helper in all languages

feat(clients): add waitForAppTask helper

---

scripts/buildSpecs.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2440
js and dart ships unused models because the lite specs keep them

fix(clients): remove unused models from lite clients

---

clients/algoliasearch-client-csharp/README.md
clients/algoliasearch-client-dart/README.md
clients/algoliasearch-client-dart/packages/algoliasearch/README.md
clients/algoliasearch-client-go/README.md
clients/algoliasearch-client-java/README.md
clients/algoliasearch-client-javascript/README.md
clients/algoliasearch-client-kotlin/README.md
clients/algoliasearch-client-python/README.md
clients/algoliasearch-client-ruby/README.md
clients/algoliasearch-client-scala/README.md
clients/algoliasearch-client-swift/README.md
templates/kotlin/README.mustache
templates/python/pyproject.mustache
tests/output/python/pyproject.toml

seems like the value in between chevrons is parsed and required to be an email, we can remove it and let people use the link only, also update readmes so they all point to the same support page

fix(python): remove contact

---

generators/src/main/java/com/algolia/codegen/AlgoliaGoGenerator.java
generators/src/main/java/com/algolia/codegen/lambda/ScreamingSnakeCaseLambda.java
playground/go/go.mod
playground/go/go.sum
templates/go/model_enum.mustache
templates/go/search_helpers.mustache
website/src/snippets.js

🎟 JIRA Ticket: [DI-1641]
- Make enum have a upper snake case
[DI-1641]: https://algolia.atlassian.net/browse/DI-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(go): update enum casing

---

scripts/cli/index.ts
scripts/release/createReleasePR.ts
website/docs/contributing/release-process.md

add dry run option for the release which allows testing the lts in a better manner
also fix pre-release bump for python versions, which is not semver compliant

fix(scripts): add dry run release and fix major bump for python

---

scripts/ci/codegen/waitForAllReleases.ts

The `waitForAllRelease` script doesn't work for dart for some reason when using the `workflowID` with a branch.
Now the api supports using the name of the yaml directly so we can simplify the script, and use better types.

fix(scripts): waitForAllRelease works with dart

---

specs/ingestion/common/schemas/common.yml
specs/ingestion/common/schemas/task.yml
specs/ingestion/paths/runs/events/events.yml
specs/ingestion/paths/runs/runs.yml
website/docs/contributing/docs.md

Fixes a typo in the docs contribution guide.

docs: fix typo in docs contribution guide

---

.github/actions/setup/action.yml
.github/workflows/check.yml
scripts/common.ts

The `usage` client was generated twice for the clients, CTS, snippets, specs, wasting time on the CI and making the bundled spec contain duplicate.
Also run the macos swift CI in parallel now.

chore(scripts): remove double usage client

---

.github/workflows/check.yml

we build the doc for every kind of PRs which consumes a lot of resources for nothing, we can at least limit it to the main branch and PRs that targets it

chore: skip website build/deploys on non main target

---

.github/workflows/check.yml
scripts/buildSpecs.ts
scripts/ci/codegen/pushToAlgoliaDoc.ts
scripts/package.json
website/.gitignore

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2458
bring back our beloved spread script, which publishes to the official documentation:
- the documentation specs
- the generated code snippets
- the SLA chart and PNGs
we only spread after a successful release, see example PR here: https://github.com/algolia/doc/pull/9098

feat(scripts): push to docs on release

---

scripts/cli/index.ts
scripts/install.sh

🎟 JIRA Ticket: [DI-2462](https://algolia.atlassian.net/browse/DI-2462)
Update the compgen
[DI-2462]: https://algolia.atlassian.net/browse/DI-2462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(scripts): add release to the completion script

---

playground/ruby/Gemfile.lock
templates/ruby/search_helpers.mustache

🎟 JIRA Ticket: [DI-1845](https://algolia.atlassian.net/browse/DI-1845) [DI-1777](https://algolia.atlassian.net/browse/DI-1777)
Add the last missing helper for ruby !
Tested with the playground, it works fine, I'll try to add generated tests later.
[DI-1845]: https://algolia.atlassian.net/browse/DI-1845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DI-1777]: https://algolia.atlassian.net/browse/DI-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ruby): add chunked_batch and replace_all_objects helpers

---

scripts/ci/codegen/pushToAlgoliaDoc.ts

push the images to the assets directory, also removed the clearing folder logic to prevent deleting unwanted doc stuff, see https://github.com/algolia/doc/pull/9098

fix(scripts): push to correct directories

---

.github/workflows/check.yml
clients/algoliasearch-client-javascript/package.json

🎟 JIRA Ticket:
see https://github.com/algolia/api-clients-automation/pull/3212, js fails to run tests for algoliasearch because it's not supposed to run, we can ignore it when it's the case

fix(scripts): js ci when algoliasearch is missing

---

specs/ingestion/common/parameters.yml
specs/ingestion/common/schemas/common.yml
specs/ingestion/common/schemas/transformation.yml
specs/ingestion/paths/transformations/transformationID.yml
specs/ingestion/paths/transformations/transformations.yml
specs/ingestion/paths/transformations/transformationsSearch.yml
specs/ingestion/paths/transformations/transformationsTry.yml
specs/ingestion/spec.yml
tests/CTS/requests/ingestion/createTransformation.json
tests/CTS/requests/ingestion/deleteTransformation.json
tests/CTS/requests/ingestion/getTransformation.json
tests/CTS/requests/ingestion/getTransformations.json
tests/CTS/requests/ingestion/searchTransformations.json
tests/CTS/requests/ingestion/tryTransformations.json
tests/CTS/requests/ingestion/updateTransformation.json

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2430
add transformations endpoint to the ingestion spec

feat(specs): add transformations endpoints to ingestion

---

clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
templates/javascript/clients/package.mustache

🎟 JIRA Ticket: https://github.com/algolia/algoliasearch-client-javascript/actions/runs/9610985686/job/26508628098
js release is using deprecated options

fix(javascript): deprecated publish options

---

specs/recommend/paths/getRecommendations.yml
templates/javascript/clients/api-single.mustache
templates/javascript/clients/client/api/imports.mustache
templates/javascript/clients/client/api/operation/legacyGetRecommendationsCompatible/implementation.mustache
templates/javascript/clients/client/api/operation/legacyGetRecommendationsCompatible/imports.mustache
templates/javascript/clients/client/api/operation/legacyGetRecommendationsCompatible/model.mustache
templates/javascript/clients/client/api/operation/parameters.mustache
templates/javascript/clients/client/model/clientMethodProps.mustache

I tested the client with InstantSearch a little bit and some things don't work : 
- `algoliasearch/lite` does not have a default export
- `getRecommendations` does not default `threshold` to `0` like it does in v4, this makes our current implem fail
- Our client hydration logic in InstantSearch doesn't work as the transporter has `baseHeaders` and `baseQueryParamaters` rather than `headers` and `queryParameters`

feat(javascript): legacy `getRecommendations` signature

---

generators/src/main/java/com/algolia/codegen/AlgoliaDartGenerator.java

🎟 JIRA Ticket:
dart release failed because I've forgot to generate the LICENSE for the core client too, which is the manually written part https://github.com/algolia/algoliasearch-client-dart/actions/runs/9685244779/job/26724943976

fix(dart): add LICENSE to client_core

---

scripts/release/createReleasePR.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2494
https://github.com/algolia/api-clients-automation/pull/3304 was the last test to ensure we can promote to major in any case/force releases, we should be ready now

chore(scripts): allow forcing release

---

clients/algoliasearch-client-javascript/yarn.lock

annoyingly it keep failing after a deps upgrade

chore(javascript): nx cache lock

---

scripts/ci/codegen/pushToAlgoliaDoc.ts

delete files before pushing to algolia doc, see https://github.com/algolia/doc/pull/9156

chore: cleanup before pushing to docs

---

clients/algoliasearch-client-swift/Sources/Search/Extra/SearchClientExtension.swift

- the update method is a PUT operation, so the given ApiKey object contains all the data and must be checked fully

fix(swift): wait for api key helper update operation

---

.github/workflows/check.yml
clients/algoliasearch-client-ruby/algolia.gemspec
playground/ruby/Gemfile.lock

Add the `base64` library because it won't be included by default in ruby 3.4

fix(ruby): add the base64 dependency

---

scripts/ci/codegen/pushToAlgoliaDoc.ts
scripts/specs/format.ts

🎟 JIRA Ticket:
since the split of the CI, the generation of the snippets is done outside of the release step, but the website generated folder isn't pushed to the repo, see https://github.com/algolia/api-clients-automation/actions/runs/9908119385/job/27373697603
since this folder will disappear when the algolia doc leverages our snippets, we can already move our snippet guides in a dedicated folder that we push and keep code in, so the release step can also leverage it

chore: keep guides for docs close to snippets

---

scripts/cts/runCts.ts
specs/recommend/paths/getRecommendations.yml

Suggested by @Haroenv https://algolia.slack.com/archives/C0341QDM3EG/p1720795670762199

fix(specs): results is required in GetRecommendationsResponse

---

clients/algoliasearch-client-go/algolia/errs/no_more_host_to_try_err.go
clients/algoliasearch-client-go/algolia/transport/configuration.go
clients/algoliasearch-client-go/algolia/transport/transport.go
templates/go/client.mustache

feat(go): expose ExposeIntermediateNetworkErrors to the config

---

.github/workflows/check.yml
.gitignore
generators/src/main/java/com/algolia/codegen/cts/tests/TestsGenerator.java
scripts/ci/githubActions/createMatrix.ts
scripts/cts/testServer/benchmark.ts
scripts/cts/testServer/timeout.ts
tests/CTS/benchmark/search/benchmark.json
tests/CTS/client/search/api.json
tests/CTS/client/search/helpers.json

Report benchmark results in the generation comment directly

chore(cts): report benchmark results

---

scripts/ci/codegen/__tests__/spreadGeneration.test.ts
scripts/ci/codegen/pushGeneratedCode.ts
scripts/ci/codegen/spreadGeneration.ts
scripts/ci/codegen/text.ts
scripts/release/__tests__/createReleasePR.test.ts
scripts/release/createReleasePR.ts

While commit messages have little context here https://github.com/algolia/api-clients-automation/commits/main/, it's super ugly on client repositories https://github.com/algolia/algoliasearch-client-go/commits/next/
In this PR, we try to provide the exact same message as the original commit, plus a link to the repo's PR

chore(scripts): improve generation commit message

---

scripts/ci/codegen/__tests__/spreadGeneration.test.ts
scripts/ci/codegen/spreadGeneration.ts
scripts/ci/codegen/text.ts
scripts/release/__tests__/createReleasePR.test.ts

it makes it clearer if we mention that the code is generated

fix(scripts): mention generated is spread msg commit

---

generators/src/main/java/com/algolia/codegen/cts/tests/ParametersWithDataType.java
specs/search/paths/objects/common/schemas.yml
tests/CTS/requests/search/partialUpdateObject.json

Make `search.BuiltInOperation` accept also integers for values.
All built-in operations accept integers, only some also accept strings (`Add`, `Remove`, `AddUnique`). Currently, `value` only accepts strings, which makes partial updates with `Increment`, etc. fail.

fix(specs): built-in ops accept also int

---

specs/ingestion/common/schemas/source.yml
specs/ingestion/paths/sources/runSource.yml
specs/ingestion/spec.yml
tests/CTS/requests/ingestion/runSource.json

🎟 JIRA Ticket: [DI-2695](https://algolia.atlassian.net/browse/DI-2695)
Add the spec for the shopify endpoint to run multiple tasks at once.
[DI-2695]: https://algolia.atlassian.net/browse/DI-2695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add runSource endpoint

---

specs/search/paths/objects/multipleBatch.yml

For multipleBatch requests, the `body` property can be empty if the action is `delete` or `clear`, thus, it shouldn't be marked as required.
- Remove `body` from the list of required properties for the multipleBatch operation.

fix(specs): body is not required in multiple batch request

---

scripts/ci/codegen/pushToAlgoliaDoc.ts
scripts/common.ts

the script errors if the pull request is already opened, we can delete the branch so that it never fails
also updates the title and add a comment preview link

fix(scripts): prevent errors on push to docs

---

scripts/release/__tests__/sla.test.ts
scripts/release/sla.ts

we shouldn't update the date if it's the same version being released https://github.com/algolia/api-clients-automation/pull/3491#discussion_r1708837333 (which shouldn't be possible actually, but that's an other problem)

fix(scripts): sla update date

---

generators/src/main/java/com/algolia/codegen/utils/OneOf.java
specs/common/schemas/HighlightResult.yml
specs/common/schemas/SnippetResult.yml
templates/csharp/modelOneOf.mustache
templates/java/oneof_interface.mustache
templates/kotlin/oneof_interface.mustache
templates/python/model_oneof.mustache
templates/scala/oneof_trait.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2723
this is a regression introduced in the generated clients, it's not as good as what js v4 was proposing (a bit broad) but should still be better
contributes to https://github.com/algolia/api-clients-automation/issues/853#issuecomment-2277263394
closes https://github.com/algolia/algoliasearch-client-javascript/issues/1534

feat(specs): recursive snippets and highlights result

---

scripts/ci/codegen/pushToAlgoliaDoc.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2752
ad blocker extensions prevent the analytics spec from rendering, we need to provide a different name when pushing the doc to prevent that

chore: prevent ad block spec files

---

specs/common/schemas/SearchParams.yml

The object is rendered with its type name, which is a bit confusing, see https://www.algolia.com/doc/rest-api/search/#tag/Search/operation/searchSingleIndex

chore(specs): update rendered title for search params

---

specs/abtesting/common/parameters.yml
specs/abtesting/common/schemas/ScheduleABTestResponse.yml
specs/abtesting/common/schemas/ScheduledABTestResponse.yml
specs/abtesting/paths/scheduleABTest.yml
specs/abtesting/spec.yml
tests/CTS/requests/abtesting/scheduleABTest.json

Add documentation for newly added `/schedule` endpoint
🎟 JIRA Ticket: [OPTIM-1160]
- Add new endpoint to the list
- Add new parameter `scheduledAt`
- Add new response payload
Added new test file with sample
[OPTIM-1160]: https://algolia.atlassian.net/browse/OPTIM-1160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add /schedule endpoint

---

clients/algoliasearch-client-csharp/README.md
clients/algoliasearch-client-go/README.md
clients/algoliasearch-client-java/README.md
clients/algoliasearch-client-javascript/README.md
clients/algoliasearch-client-kotlin/README.md
clients/algoliasearch-client-php/README.md
clients/algoliasearch-client-python/README.md
clients/algoliasearch-client-ruby/README.md
clients/algoliasearch-client-scala/README.md
clients/algoliasearch-client-swift/README.md
templates/csharp/netcore_project.mustache
templates/javascript/clients/README.mustache
templates/kotlin/README.mustache

closes https://github.com/algolia/algoliasearch-client-csharp/issues/858, also fixes the Go client that targets the master branch

fix(clients): mention `main` branch instead of `master`

---

clients/algoliasearch-client-php/lib/Model/AbstractModel.php
config/generation.config.mjs
generators/src/main/java/com/algolia/codegen/AlgoliaPhpGenerator.java

Follow up https://github.com/algolia/api-clients-automation/pull/3562
- List changes

fix(php): native return types for AbstractModel methods

---

templates/issue.yml

Jira tickets are very ugly because the rest api v3 only support ADF, which is not compatible with markdown.
We can use version 2 of the Jira API that supports md.

chore(scripts): use markdown in jira

---

.github/workflows/check.yml
scripts/ci/githubActions/utils.ts

Ignore the benckmark report when the matrix is empty.
Also fix the common templates.

fix(scripts): dont fail on empty benchamrk

---

specs/common/schemas/SearchParams.yml

GH PR: https://github.com/algolia/AlgoliaSaaS/pull/11547
Change the `length` minimum from 1 to 0.

docs(specs): update api's length minimum value

---

clients/algoliasearch-client-swift/Sources/Core/Helpers/Extensions.swift

🎟 JIRA Ticket: closes [GH-ISSUE #867](https://github.com/algolia/algoliasearch-client-swift/issues/867) & [DI-2789]
- Accept any types during JSON encoding
[DI-2789]: https://algolia.atlassian.net/browse/DI-2789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(swift): accept any type during json encoding

---

templates/javascript/clients/algoliasearch/builds/definition.mustache
templates/javascript/clients/client/builds/definition.mustache

It is a best practice to prefix node packages with `node:`
Introduced in Node 18: https://stateful.com/blog/node-18-prefix-only-modules
This also ease support for edge-runtime like Cloudflare Workers (https://developers.cloudflare.com/workers/runtime-apis/nodejs/crypto/)
- Update import from `crypto` to `node:crypto`

fix(javascript): prefix with `node:` for node packages

---

scripts/release/createReleasePR.ts
templates/javascript/clients/README.mustache

- csharp: 7.2.1 -> **`patch` _(e.g. 7.2.2)_**
- dart: 1.23.1 -> **`patch` _(e.g. 1.23.2)_**
- go: 4.2.1 -> **`patch` _(e.g. 4.2.2)_**
- java: 4.2.2 -> **`patch` _(e.g. 4.2.3)_**
- javascript: 5.2.2 -> **`patch` _(e.g. 5.2.3)_**
- kotlin: 3.2.1 -> **`patch` _(e.g. 3.2.2)_**
- php: 4.3.2 -> **`patch` _(e.g. 4.3.3)_**
- python: 4.2.1 -> **`patch` _(e.g. 4.2.2)_**
- ruby: 3.2.1 -> **`patch` _(e.g. 3.2.2)_**
- scala: 2.2.1 -> **`patch` _(e.g. 2.2.2)_**
- swift: 9.2.1 -> **`patch` _(e.g. 9.2.2)_**
<p>It doesn't mean these commits are being excluded from the release. It means they're not taken into account when the release process figured out the …

chore: prepare release 2024-08-29 [skip-bc]

---

scripts/cts/runCts.ts
specs/insights/common/schemas/AddedToCartObjectIDs.yml
specs/insights/common/schemas/AddedToCartObjectIDsAfterSearch.yml
specs/insights/common/schemas/ClickedFilters.yml
specs/insights/common/schemas/ClickedObjectIDs.yml
specs/insights/common/schemas/ClickedObjectIDsAfterSearch.yml
specs/insights/common/schemas/ConvertedFilters.yml
specs/insights/common/schemas/ConvertedObjectIDs.yml
specs/insights/common/schemas/ConvertedObjectIDsAfterSearch.yml
specs/insights/common/schemas/EventAttributes.yml
specs/insights/common/schemas/PurchasedObjectIDs.yml
specs/insights/common/schemas/PurchasedObjectIDsAfterSearch.yml
specs/insights/common/schemas/ViewedFilters.yml
specs/insights/common/schemas/ViewedObjectIDs.yml

Looking at the spec for `View Filters` and seeing `example name: Product Clicked` is confusing.
🎟 JIRA Ticket: None
- Added examples to the eventName attribute of each concretization of the event concept
- Removed based example on eventName attribute (to keep the spec json schema compliant)
?? <- Let me know how I can do that! I ran `yarn website` to generate the bundled version and it seemed okay, but 🤷‍♂️ and I don't know how to view the website locally 😅

docs(insights): Example event name should change with eventType

---

generators/src/main/java/com/algolia/codegen/utils/Helpers.java
templates/csharp/Configuration.mustache
templates/dart/api.mustache
templates/go/client.mustache
templates/java/api.mustache
templates/javascript/clients/client/api/hosts.mustache
templates/kotlin/api.mustache
templates/php/api.mustache
templates/python/config.mustache
templates/ruby/api.mustache
templates/scala/api.mustache
templates/swift/client_configuration.mustache
tests/CTS/client/usage/api.json

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2857
closes https://github.com/algolia/api-clients-automation/issues/3621
correctly parses the servers when it's not an appID or regional host

fix(clients): correly parse usage hosts

---

specs/insights/spec.yml

Correct a false statement about the Insights API's server `insights.algolia.io`. It uses geo routing to forward to either `insights.de.algolia.io` or `insights.us.algolia.io`.

fix(specs): note on insights API server

---

templates/php/ApiException.mustache
templates/php/ConfigWithRegion.mustache
templates/php/Configuration.mustache
templates/php/ModelInterface.mustache
templates/php/ObjectSerializer.mustache
templates/php/api.mustache
templates/php/client_config.mustache
templates/php/model.mustache

🎟 JIRA Ticket: [DI-2878](https://algolia.atlassian.net/browse/DI-2878). closes https://github.com/algolia/algoliasearch-client-php/issues/736
The banner must be after `<?php`. I checked all the files and this was the only one.
`find . -name "*.php" -not -path "./clients/algoliasearch-client-php/vendor/*" -exec sh -c 'head -n 1 "$1" | grep -q "^<?php$" || echo "$1 does not start with <?php"' _ {} \;`
[DI-2878]: https://algolia.atlassian.net/browse/DI-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(php): put banner after php tag

---

clients/algoliasearch-client-csharp/algoliasearch/Http/AlgoliaUserAgent.cs
clients/algoliasearch-client-csharp/algoliasearch/Utils/SearchClientExtensions.cs
templates/csharp/api.mustache
templates/csharp/netcore_project.mustache
tests/output/csharp/src/Algolia.Search.Tests.csproj

🎟 JIRA Ticket: [DI-2888](https://algolia.atlassian.net/browse/DI-2888). closes https://github.com/algolia/algoliasearch-client-csharp/issues/864
Added all the helpers to the search interface, and cleaned up the documentation by using `inheritdoc`.
Also fix all the warnings, such as missing doc or vulnerable lib:
[DI-2888]: https://algolia.atlassian.net/browse/DI-2888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(csharp): add helpers to ISearchClient

---

clients/algoliasearch-client-javascript/packages/algoliasearch/__tests__/algoliasearch.browser.test.ts
clients/algoliasearch-client-javascript/packages/algoliasearch/__tests__/algoliasearch.node.test.ts
templates/javascript/clients/api-single.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2894
asserts the inherited helpers from search client and reflect different auth modes for the `setClientApiKey` helper

fix(javascript): assert helpers and fix setClientApiKey helper

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/client-usage/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
config/clients.config.json

- ~csharp: 7.3.0 (no commit)~
- ~dart: 1.24.0 (no commit)~
- ~go: 4.3.0 (no commit)~
- ~java: 4.3.0 (no commit)~
- javascript: 5.3.1 -> **`patch` _(e.g. 5.3.2)_**
- ~kotlin: 3.3.0 (no commit)~
- ~php: 4.4.0 (no commit)~
- ~python: 4.4.0 (no commit)~
- ~ruby: 3.3.0 (no commit)~
- ~scala: 2.3.0 (no commit)~
- ~swift: 9.3.0 (no commit)~
<details>
<summary>
</summary>
</details>
<details>
<summary> …

chore: prepare release 2024-09-09

---

specs/common/schemas/SearchResponse.yml

Return the parameter `_automaticInsights` (when possible) when calling search.
I need this value in the Recommend mono-repository so that the Recommend API can forward this parameter to the Recommend client.

feat(specs): add (optional) _automaticInsights to search result

---

clients/algoliasearch-client-javascript/packages/algoliasearch/__tests__/algoliasearch.fetch.test.ts
clients/algoliasearch-client-javascript/packages/algoliasearch/__tests__/algoliasearch.node.test.ts
playground/javascript/node/algoliasearch.ts

🎟 JIRA Ticket: contributes to https://github.com/algolia/algoliasearch-client-javascript/issues/1548
simple assertion to make sure that the methods exists on those builds https://github.com/algolia/algoliasearch-client-javascript/issues/1548#issuecomment-2343050973

chore: assert node helpers

---

scripts/release/__tests__/createReleasePR.test.ts
scripts/release/createReleasePR.ts
scripts/release/types.ts

I forgot about generated commits in my last PR, they should also contribute to the changelog, on behalf of the base commit.

chore(scripts): take generated commits into account for the release

---

templates/javascript/clients/rollup.config.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2909
close https://github.com/algolia/api-clients-automation/issues/3700
see context here https://github.com/algolia/api-clients-automation/issues/3700
the tsup build changed the exported global name on `window`, previously exposed `window['algoliasearch/lite']` changed to `window.lite`, which is incorrect, and a breaking change.
we now provide the previous names

fix(javascript): umd export name

---

clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-javascript/packages/requester-testing/package.json
config/clients.config.json

- ~csharp: 7.3.1 (no commit)~
- ~dart: 1.24.0 (no commit)~
- ~go: 4.3.1 (no commit)~
- ~java: 4.3.1 (no commit)~
- javascript: 5.4.1 -> **`patch` _(e.g. 5.4.2)_**
- ~kotlin: 3.3.1 (no commit)~
- ~php: 4.4.1 (no commit)~
- ~python: 4.4.1 (no commit)~
- ~ruby: 3.3.1 (no commit)~
- ~scala: 2.3.1 (no commit)~
- ~swift: 9.3.1 (no commit)~
<details>
<summary>
</summary>
- chore(scripts): take generated …

chore: prepare release 2024-09-12

---

clients/algoliasearch-client-python/algoliasearch/http/api_response.py
clients/algoliasearch-client-python/algoliasearch/http/helpers.py
clients/algoliasearch-client-python/algoliasearch/http/request_options.py
clients/algoliasearch-client-python/algoliasearch/http/serializer.py
clients/algoliasearch-client-python/algoliasearch/http/transporter.py
templates/python/api.mustache
templates/python/pyproject.mustache
templates/python/search_helpers.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2911
close https://github.com/algolia/algoliasearch-client-python/issues/571
I forgot the close method when introducing the sync client, also fix some typing issues

fix(python): missing transporter close

---

specs/common/schemas/HighlightResult.yml
specs/common/schemas/SearchResponse.yml
specs/common/schemas/SnippetResult.yml

🎟 JIRA Ticket: [DI-2912] & closes [#425](https://github.com/algolia/algoliasearch-client-kotlin/issues/425)
- Makes search response pagination props optional
- Fixes recursive spec for `highlightResult` and `snippetResult`
[DI-2912]: https://algolia.atlassian.net/browse/DI-2912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(specs): update search api specs [skip-bc]

---

clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
templates/javascript/clients/package.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2948
fixes https://github.com/algolia/algoliasearch-client-javascript/issues/1554#issuecomment-2358671330
the lite package also needs to have an entry point in the `react-native` field.
this object syntax is supported for every fields normally, so I hope it also works for react native
also adds the `react-native` field for the browser-xhr and fetch requester

 fix(javascript): react-native lite resolution

---

clients/algoliasearch-client-java/algoliasearch/src/main/java/com/algolia/internal/HttpRequester.java
clients/algoliasearch-client-scala/src/main/scala/algoliasearch/internal/HttpRequester.scala
templates/java/api.mustache
tests/CTS/client/search/api.json

The java search client is not using the read transporter at all.

fix(clients): use the dsn with the read transporter

---

clients/algoliasearch-client-javascript/packages/client-common/src/transporter/errors.ts
clients/algoliasearch-client-javascript/tsconfig.json

imported from https://github.com/algolia/algoliasearch-client-javascript/pull/1552
----
When using this library with the newest angular version (v18.2.2), the following error will be thrown.
You can "fix" the issue by using `noImplicitOverride: false` in the `tsconfig`, but I guess it would make sense to fix it here...
```
✖ Compiling with Angular sources in Ivy partial compilation mode.
node_modules/@algolia/client-common/src/transporter/errors.ts:4:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Error'.
4   name: string = 'AlgoliaError';
```
This PR adds the missing `override` property and should fix this issue.

fix(javascript): add override to name property

---

templates/java/api.mustache
templates/scala/api.mustache

The host for the retry stategy should end in .com

fix(clients): use the correct host for search

---

scripts/cts/testServer/apiKey.ts
specs/recommend/common/schemas/RecommendationsResponse.yml
templates/kotlin/oneof_interface.mustache

🎟 JIRA Ticket: [CR-6916]
- update recommend spec to add oneOf discriminators
- update template to generate all possible oneOf cases
- update template to fix array deserialization
[CR-6916]: https://algolia.atlassian.net/browse/CR-6916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(kotlin): deserialization

---

templates/python/snippets/method.mustache

showcase synchronous snippets, and mention the asynchronous class, for broader usage coverage https://algolia.slack.com/archives/C05C3DRTVFU/p1727267587674509

chore(python): show synchronous snippets

---

.eslintrc.cjs
.github/workflows/push-to-algolia-doc.yml
.github/workflows/renovate.yml
.github/workflows/scheduled-release.yml
scripts/ci/codegen/pushToAlgoliaDoc.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2969
add a simple action to be able to manually trigger the push to algolia doc script, so that we don't have to setup a github token nor know how to run the script

chore(ci): add a workflow to push to Algolia doc

---

specs/search/paths/keys/key.yml

Update the description for the 'Get API key' operation.
API key description will be obfuscated if using a non-admin API key.
This is a port from a change made in the docs repo. More information in https://github.com/algolia/doc/pull/9412

fix(specs): API key description will be obfuscated

---

templates/python/search_helpers.mustache

Make the Python helpers more consistent by supporting `request_options` for all helpers
that are based on `chunked_batch`.
Add `request_options` to the following helpers:
- `save_objects`
- `delete_objects`
- `partial_update_objects`
The rest of them already work with `request_options`.
Also provide `dict` as accepted type for API key restrictions in `generate_secured_api_key`, since the function already handles that case.

feat(templates): add request_options to python helpers consistently

---

.github/workflows/check.yml

To allow external contributors, we need to allow them to access token on the CI, this is safe because we need to approve the CI before it can run.

chore(ci): allow fork to access secrets

---

.github/workflows/check.yml
.github/workflows/cleanup.yml
specs/common/schemas/IndexSettings.yml
specs/common/schemas/SearchParams.yml
specs/search/paths/keys/common/schemas.yml
specs/search/paths/manage_indices/operationIndex.yml
specs/search/paths/objects/object.yml
specs/search/paths/objects/objects.yml
specs/search/paths/objects/partialUpdate.yml
specs/search/paths/rules/common/schemas.yml
specs/search/paths/search/browse.yml
specs/search/paths/search/search.yml
specs/search/paths/search/searchSingleIndex.yml
specs/search/paths/synonyms/synonym.yml
specs/search/spec.yml

Spotted a couple of typos when looking through the docs site output and decided to check for more.
- Just fixing some typos in the search API descriptions

fix(specs): correct typos is Search API

---

.github/workflows/check.yml
scripts/ci/codegen/pushGeneratedCode.ts
scripts/ci/utils.ts

this should revert the script changes from https://github.com/algolia/api-clients-automation/commit/bed119166c1c3cc53878c2c9a7d1d062d5a14b27 and https://github.com/algolia/api-clients-automation/commit/0cdb86601a0d42367a7f79432d12327d4b12ef06, which prevents the spread to properly execute
we can revisit the issue later on but so far we are late on few commits and a release

chore: spread release revert

---

scripts/ci/codegen/pushGeneratedCode.ts

double quotes in commit message makes the script fail
tested on this branch with `yarn workspace scripts pushGeneratedCode`

fix(scripts): escape "double quotes"

---

clients/algoliasearch-client-go/algolia/errs/no_more_host_to_try_err.go

The message `You can use 'ExposeIntermediateNetworkErrors: true'` should not appear when it is true, we can show the real errors instead.

fix(go): better network error

---

clients/algoliasearch-client-javascript/packages/client-common/index.d.ts
clients/algoliasearch-client-javascript/packages/client-common/index.js
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/logger-console/index.d.ts
clients/algoliasearch-client-javascript/packages/logger-console/index.js
clients/algoliasearch-client-javascript/packages/logger-console/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/index.d.ts
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/index.js
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/index.d.ts
clients/algoliasearch-client-javascript/packages/requester-fetch/index.js
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/index.d.ts
clients/algoliasearch-client-javascript/packages/requester-node-http/index.js
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-javascript/packages/requester-testing/index.d.ts
clients/algoliasearch-client-javascript/packages/requester-testing/index.js
clients/algoliasearch-client-javascript/packages/requester-testing/package.json

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3052
closes https://github.com/algolia/algoliasearch-client-javascript/issues/1561
we shouldn't publish the source files, it can causes downstream issues if different typescript rules are applied

fix(javascript): do not publish ts

---

.github/workflows/check.yml
specs/recommend/common/schemas/RecommendationsResponse.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3041
closes https://github.com/algolia/api-clients-automation/issues/3940 https://github.com/algolia/algoliasearch-client-javascript/issues/1560
there is a chance that this property is not present in the response (confirmed by @raed667 and @benamib)

fix(specs): recommend `_score` is optional

---

specs/common/schemas/IndexSettings.yml

🎟 JIRA ticket: https://algolia.atlassian.net/browse/DOC-1533
Docs focused more on a direct description rather than the usage. Added notes about the usage: ensuring exact matches for certain words.

fix(specs): Typo tolernace on words

---

scripts/ci/codegen/pushGeneratedCode.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3077
co author has been broken on generated commits for a few days, this should add the original authors back
last commit tested here https://github.com/algolia/api-clients-automation/commit/021c52419330804e6cf3c2d7b7e4686b3cd5ef9

chore: add co-author to generated commit

---

scripts/ci/codegen/pushGeneratedCode.ts
specs/ingestion/common/schemas/event.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2881
- remove parentID from ingestion specs
- fix the generated commit logic

fix(specs): remove `parentID` from ingestion specs [skip-bc]

---

generators/src/main/java/com/algolia/codegen/AlgoliaJavascriptGenerator.java
templates/javascript/clients/package.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3085
closes https://github.com/algolia/algoliasearch-client-javascript/issues/1562
the search client wasn't in the dependencies anymore

fix(javascript): missing search dependency

---

templates/javascript/clients/client/model/clientMethodProps.mustache
templates/javascript/clients/client/model/types/isGeneric.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3096
we've converted the `any` types to `unknown` lately, but left over some of the generic hardcoded ones

fix(javascript): use unknown over any

---

.github/workflows/check.yml
specs/analytics/common/parameters.yml

🎟 JIRA Ticket: [OPTIM-1314]
Update documents to reflect changes in the API brought by https://github.com/algolia/go/pull/16694
- Remove limitation on `offset + limit` combined limit and update documentation to reflect the changes
[OPTIM-1314]: https://algolia.atlassian.net/browse/OPTIM-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(analytics): constrain pagination only to limit query parameter

---

scripts/cache.ts
scripts/ci/codegen/createGitHubReleases.ts
scripts/ci/codegen/waitForAllReleases.ts
scripts/cli/index.ts
scripts/common.ts
scripts/config.ts
scripts/cts/runCts.ts
scripts/cts/testServer/apiKey.ts
scripts/cts/testServer/benchmark.ts
scripts/cts/testServer/chunkWrapper.ts
scripts/cts/testServer/gzip.ts
scripts/cts/testServer/index.ts
scripts/cts/testServer/replaceAllObjects.ts
scripts/cts/testServer/timeout.ts
scripts/cts/testServer/timeoutBis.ts
scripts/cts/testServer/waitFor.ts
scripts/generate.ts
scripts/specs/__tests__/snippets.test.ts
scripts/specs/types.ts
scripts/tsconfig.json
scripts/types.ts

The tests cannot run because they use js `module`

fix(scripts): use module in scripts

---

clients/algoliasearch-client-javascript/package.json
clients/algoliasearch-client-javascript/tsconfig.json
scripts/buildLanguages.ts
scripts/ci/githubActions/createMatrix.ts
templates/javascript/clients/algoliasearch/builds/models.mustache
templates/javascript/clients/client/api/operation/legacySearchCompatible/imports.mustache
templates/javascript/clients/client/builds/definition.mustache
templates/javascript/clients/client/model/clientMethodProps.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3102
close https://github.com/algolia/algoliasearch-client-javascript/issues/1565
close https://github.com/algolia/algoliasearch-client-javascript/issues/1562
seems like tsup doesn't remove type imports if the statement doesn't include `type` in it, leading to javascript files with type imports... see https://www.npmjs.com/package/algoliasearch?activeTab=code in `/algoliasearch/dist/node.js` L53-L54 for example
also add https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax to enforce import types consistency

fix(javascript): import type for bundler

---

clients/algoliasearch-client-ruby/lib/algolia.rb
clients/algoliasearch-client-ruby/lib/algolia/defaults.rb
config/generation.config.mjs

closes https://github.com/algolia/algoliasearch-client-ruby/pull/504
The client is referencing an file that doesn't exists anymore

fix(ruby): provide default ttl

---

generators/src/main/java/com/algolia/codegen/cts/tests/ParametersWithDataType.java
specs/common/schemas/Rule.yml
specs/recommend/common/responses/common.yml
specs/recommend/common/schemas/RecommendRule.yml
specs/search/paths/rules/common/schemas.yml

🎟 JIRA Ticket: [CR-7132]
- timestamps need an int64 to be able to handle date later than 2038
[CR-7132]: https://algolia.atlassian.net/browse/CR-7132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(specs): update time range number types [skip-bc]

---

specs/search/paths/objects/getObjects.yml

🎟 JIRA Ticket: just trying to make a small contribution :)
Add missing `message` attribute to `GetObjectsResponse`

feat(specs): add missing message attribute to GetObjectsResponse [skip-bc]

---

generators/src/main/java/com/algolia/codegen/AlgoliaJavaGenerator.java
generators/src/main/java/com/algolia/codegen/AlgoliaPythonGenerator.java
generators/src/main/java/com/algolia/codegen/utils/Helpers.java
specs/search/paths/synonyms/common/parameters.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3108
see https://github.com/algolia/AlgoliaWeb/pull/22442#discussion_r1816448163 and https://github.com/algolia/AlgoliaWeb/pull/22442#discussion_r1816451248 for context
the API accepts both casing, and the search is case insensitive, the camel case is the more obvious one and was supported in the previous major

fix(specs): support synonyms type in camel case [skip-bc]

---

templates/javascript/clients/package.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3141
It's impossible to import from the dist right now because it's not defined in the exports

fix(javascript): allow import from dist

---

specs/ai-personalization/common/enums.yml

Following https://github.com/algolia/doc/pull/9529, this PR also introduces the new error code, `all_facets_invalid` to the spec file for AI Personalization.
🎟 JIRA Ticket: [PRED-3297](https://algolia.atlassian.net/browse/PRED-3297)
- Updating the OpenAPI spec file for AI personalization
[PRED-3297]: https://algolia.atlassian.net/browse/PRED-3297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(ai-perso): add new application-level error

---

scripts/ci/codegen/createGitHubReleases.ts

🎟 JIRA Ticket: [DI-3117](https://algolia.atlassian.net/browse/DI-3117)
Use the already generated changelog and add it to the release.
[DI-3117]: https://algolia.atlassian.net/browse/DI-3117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ci): generate a pretty changelog for the release

---

clients/algoliasearch-client-csharp/CHANGELOG.md
clients/algoliasearch-client-go/CHANGELOG.md
clients/algoliasearch-client-java/CHANGELOG.md
clients/algoliasearch-client-javascript/CHANGELOG.md
clients/algoliasearch-client-javascript/bundlesize.config.json
clients/algoliasearch-client-javascript/packages/algoliasearch/package.json
clients/algoliasearch-client-javascript/packages/client-abtesting/package.json
clients/algoliasearch-client-javascript/packages/client-analytics/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-composition/package.json
clients/algoliasearch-client-javascript/packages/client-insights/package.json
clients/algoliasearch-client-javascript/packages/client-personalization/package.json
clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json
clients/algoliasearch-client-javascript/packages/client-search/package.json
clients/algoliasearch-client-javascript/packages/ingestion/package.json
clients/algoliasearch-client-javascript/packages/logger-console/package.json
clients/algoliasearch-client-javascript/packages/monitoring/package.json
clients/algoliasearch-client-javascript/packages/recommend/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-javascript/packages/requester-testing/package.json
clients/algoliasearch-client-kotlin/CHANGELOG.md
clients/algoliasearch-client-php/CHANGELOG.md
clients/algoliasearch-client-python/CHANGELOG.md
clients/algoliasearch-client-ruby/CHANGELOG.md
clients/algoliasearch-client-scala/CHANGELOG.md
clients/algoliasearch-client-swift/CHANGELOG.md
config/clients.config.json
config/versions.history.json

- csharp: 7.8.0 -> **`patch` _(e.g. 7.8.1)_**
- go: 4.7.0 -> **`patch` _(e.g. 4.7.1)_**
- java: 4.7.0 -> **`patch` _(e.g. 4.7.1)_**
- javascript: 5.12.0 -> **`minor` _(e.g. 5.13.0)_**
- kotlin: 3.8.0 -> **`minor` _(e.g. 3.9.0)_**
- php: 4.8.0 -> **`patch` _(e.g. 4.8.1)_**
- python: 4.8.0 -> **`patch` _(e.g. 4.8.1)_**
- ruby: 3.7.0 -> **`patch` _(e.g. 3.7.1)_**
- scala: 2.7.0 -> **`minor` _(e.g. 2.8.0)_**
- swift: 9.9.0 -> **`patch` _(e.g. 9.9.1)_**
<p>It doesn't mean these commits are being excluded from the release. It means they're not taken into account when the release process figured out the next version number, and updated the …

chore: prepare release 2024-11-06

---

.eslintrc.cjs
eslint/src/index.ts
eslint/src/rules/noBigInt.ts
eslint/tests/noBigInt.test.ts

I saw this type in one of the external contribution, we should never allow `BitInteger` or `BigDecimal` types

chore(eslint): add linter to forbid bigInt [skip-bc]

---

specs/ingestion/common/schemas/task.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3142
for `push`, the `action` is empty since it has no effect in this context

fix(specs): make `action` optional for tasks [skip-bc]

---

templates/go/api.mustache
templates/go/client.mustache
tests/CTS/client/search/indexExists.json
tests/CTS/client/search/saveObjects.json

GCP Cloud Armor can return raw HTML error, we can catch them and handle them gracefully instead of failing the json deserialization.

fix(go): handle HTML errors [skip-bc]

---

scripts/ci/codegen/createGitHubReleases.ts
scripts/release/common.ts
scripts/release/createReleasePR.ts
scripts/release/updateAPIVersions.ts

Remove `[skip-bc]` from the changelog to remove some noise.

fix(scripts): remove skip bc from the changelog [skip-bc]

---

specs/abtesting/common/schemas/EstimateABTestResponse.yml

[OPTIM-1329]
Dependent on merge and deploy of https://github.com/algolia/go/pull/16975
Changed the response type to an array of integers, rather than static numbers to account for multiple variants in estimation
- All tests should pass
[OPTIM-1329]: https://algolia.atlassian.net/browse/OPTIM-1329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): update estimate response type [skip-bc]

---

clients/algoliasearch-client-javascript/package.json
clients/algoliasearch-client-javascript/scripts/publish.ts
clients/algoliasearch-client-javascript/yarn.lock

the release script for js failed on the composition package, I assume it is because we went from a private to a public package with manual interventions
this pr updates the public script to support (in a non programmatically way) the private and alpha releases

fix(javascript): add support for private package publish

---

playground/python/app/search.py
playground/python/poetry.lock
specs/search/paths/objects/deleteBy.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3213
closes https://github.com/algolia/algoliasearch-client-python/issues/575
`delete_by` returns an `updatedAt` response, not a `deletedAt`

fix(specs): `deleteBy` returns an `updatedAt` response [skip-bc]

---

specs/composition/paths/rules/searchRules.yml

🎟 JIRA Ticket:
- remove `x-use-read-transporter` & `x-cacheable` that where set by default

fix(specs): do not cache searchCompositionRules

---

specs/crawler/common/schemas/configuration.yml

🎟 JIRA Tickets:
- https://algolia.atlassian.net/browse/DEX-1608
- https://algolia.atlassian.net/browse/DOC-1540
- Additional property in the safetyChecks object

fix(specs): additional safetyChecks

---

generators/src/main/java/com/algolia/codegen/AlgoliaJavascriptGenerator.java
templates/javascript/clients/api-single.mustache
templates/javascript/clients/client/api/imports.mustache
templates/javascript/clients/client/builds/browser.mustache
templates/javascript/clients/client/model/clientMethodProps.mustache

🎟 JIRA Ticket: [EMERCH-1759](https://algolia.atlassian.net/browse/EMERCH-1759)
- default authMode to WithinHeaders for Composition Client
- standardize variable name
[EMERCH-1759]: https://algolia.atlassian.net/browse/EMERCH-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): default authMode to WithinHeaders for Composition Client

---

clients/algoliasearch-client-javascript/scripts/publish.ts

the published alpha version isn't set as the latest available, meaning that npm shows the .1 everytime (cf screenshot)
we now set the latest tag explicitly, which seems to be enough https://www.npmjs.com/package/@algolia/client-composition?activeTab=versions

fix(javascript): set latest version on prereleases

---

clients/algoliasearch-client-python/algoliasearch/http/base_config.py
clients/algoliasearch-client-python/algoliasearch/http/user_agent.py
playground/python/app/search.py
playground/python/poetry.lock
templates/python/api.mustache
templates/python/config.mustache

there's no easy way to just get the user agent or just add segments to it, rather than keeping it local to the config we could just expose it so it's easier to play with

fix(python): expose `user_agent` on the config

---

clients/algoliasearch-client-javascript/packages/algoliasearch/__tests__/tsconfig.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/client-common/src/__tests__/cache/browser-local-storage-cache.test.ts
clients/algoliasearch-client-javascript/packages/client-common/src/__tests__/create-iterable-promise.test.ts
clients/algoliasearch-client-javascript/packages/client-common/src/createIterablePromise.ts
clients/algoliasearch-client-javascript/packages/client-common/src/types/createIterablePromise.ts
clients/algoliasearch-client-javascript/packages/client-common/tsconfig.json
clients/algoliasearch-client-javascript/packages/logger-console/package.json
clients/algoliasearch-client-javascript/packages/logger-console/tsconfig.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/src/__tests__/browser-xhr-requester.test.ts
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/tsconfig.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/src/__tests__/fetch-requester.test.ts
clients/algoliasearch-client-javascript/packages/requester-fetch/tsconfig.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/src/__tests__/node-http-requester.test.ts
clients/algoliasearch-client-javascript/packages/requester-node-http/tsconfig.json
playground/javascript/node/ingestion.ts
templates/javascript/clients/package.mustache

Allow all params of `createIterablePromise` to return `PromiseLike` and call them with await, if people want to use `await` inside their fonctions.
This is not a breaking change and stays compatible with before.

fix(javascript): allow async param on createIterablePromise

---

.github/workflows/check.yml
scripts/ci/githubActions/createMatrix.ts
scripts/ci/githubActions/types.ts

Run the macos jobs in parallel of the other codegen because they are slow as hell

chore(ci): run the macos jobs in parallel [skip-bc]

---

templates/ruby/search_helpers.mustache

Suggested by @kombucha in https://github.com/algolia/AlgoliaWeb/pull/22965#discussion_r1865709618, we can expose static helpers where needed, and forward the call of instance method to the static function to make it non-breaking.

fix(ruby): expose static helper [skip-bc]

---

clients/algoliasearch-client-javascript/package.json
clients/algoliasearch-client-javascript/packages/client-common/package.json
clients/algoliasearch-client-javascript/packages/logger-console/package.json
clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json
clients/algoliasearch-client-javascript/packages/requester-fetch/package.json
clients/algoliasearch-client-javascript/packages/requester-node-http/package.json
clients/algoliasearch-client-javascript/packages/requester-testing/package.json
templates/javascript/clients/package.mustache

in vscode for example, the homepage field will show when you hover over a library name in our own package.json
https://github.com/algolia/algoliasearch-client-javascript/pull/1504

chore: add homepage to JavaScript client package

---

specs/ingestion/common/observabilityParameters.yml
specs/ingestion/common/taskParameters.yml
specs/ingestion/paths/tasks/v2/tasks.yml

Add the `sourceType` query param to `listTasks`.
Also fix the type of the `type` query param in the `listRuns` endpoint.

fix(specs): add sourceType to listTasks [skip-bc]

---

templates/csharp/guides/ingestion/pushSetup.mustache
templates/go/guides/ingestion/pushSetup.mustache
templates/java/guides/ingestion/pushSetup.mustache
templates/javascript/guides/ingestion/pushSetup.mustache
templates/kotlin/guides/ingestion/pushSetup.mustache
templates/php/guides/ingestion/pushSetup.mustache
templates/python/guides/ingestion/pushSetup.mustache
templates/ruby/guides/ingestion/pushSetup.mustache
templates/scala/guides/ingestion/pushSetup.mustache
templates/swift/guides/ingestion/pushSetup.mustache

we shouldn't recommend to read a file at the root of the disk, we can keep it at the script level

guides: push records.json location [skip-bc]

---

specs/search/paths/objects/object.yml
specs/search/paths/objects/objects.yml

Better distinguish the `saveObject` and `addOrUpdateObject` methods with distinct summaries.
🎟 JIRA Ticket:
- List changes

fix(specs): different summaries for saveObject/addOrUpdate methods

---

scripts/release/__tests__/versionsHistory.test.ts
scripts/release/versionsHistory.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3338
this updates the scripts to reflect the latest changes, i've rewrote the logic a bit with as much comment as possible because it's pretty cumbersome to go through

fix(scripts): sla and support policy [skip-bc]

---

scripts/release/__tests__/versionsHistory.test.ts
scripts/release/versionsHistory.ts

skips invalid semver if encountered

fix(scripts): skip invalid semver [skip-bc]

---

clients/algoliasearch-client-javascript/packages/algoliasearch/__tests__/algoliasearch.common.test.ts
templates/javascript/clients/api-single.mustache

Expose the currently used api key. This is good for instantiating other information (like insights client) and is consistent with the appId being exposed.
- add apiKey to the client template
```js
const appId = "appId";
const apiKey = "apiKey";
const client = algoliasearch(appId, apiKey) // and other clients
expect(client. appId).toBe(appId)
expect(client.apiKey).toBe(apiKey)
```

feat(javascript): expose current apiKey on the client instance [skip-bc]

---

specs/personalization/common/schemas/eventsScoring.yml
specs/personalization/common/schemas/facetsScoring.yml
specs/personalization/common/schemas/personalizationStrategy.yml
tests/CTS/requests/personalization/setPersonalizationStrategy.json

[DI-3352](https://algolia.atlassian.net/browse/DI-3352)
fixes https://github.com/algolia/algoliasearch-client-javascript/issues/1577
[DI-3352]: https://algolia.atlassian.net/browse/DI-3352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(specs): personalization uses plural names [skip-bc]

---

specs/major-breaking-changes-rename.json

Remove the separate entry for the old `client.list_indexes` method which was only used for Ruby. This is better handled as an exception when constructing [the table](https://deploy-preview-9638--algolia-docs.netlify.app/doc/libraries/ruby/v3/upgrade/) since the URL is the same `list-indices` but only the name is different and only for Ruby. 
🎟 JIRA Ticket:
- Remove the `client.list_indexes` entry, since this is handled in https://github.com/algolia/doc/pull/9638

fix(clients): no list indexes entry

---

specs/ai-personalization/common/schemas/Configuration.yml

As per the ticket, we don't want to display references to predictive profiles whilst they're still in beta.
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/PRED-3403%5D
- Remove predictive profiles reference
n/a

feat(specs): remove predictive profiles from advanced perso [PRED-3403]

---

scripts/docker/Dockerfile.base
scripts/docker/Dockerfile.ruby
scripts/docker/Dockerfile.swift
specs/ingestion/common/schemas/source.yml

🎟 JIRA Ticket: [DI-3364](https://algolia.atlassian.net/browse/DI-3364)
The ingestion API is simplified for docker sources.
[DI-3364]: https://algolia.atlassian.net/browse/DI-3364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): only use shortname in the source input [skip-bc]

---

specs/common/schemas/SearchParams.yml

Port an amendment to the `optionalFilters` API parameter [DOC PR 9656](https://github.com/algolia/doc/pull/9656/), explaining that `optionalFilters` are usually applied _before_ custom ranking. 
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/CR-7529
- Mention that in the default ranking, `optionalFilters` are applied before custom ranking

fix(specs): optionalFilters additional explanation [skip-bc]

---

scripts/specs/__tests__/snippets.test.ts
scripts/specs/format.ts
scripts/specs/snippets.ts

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3385
https://github.com/algolia/api-clients-automation/pull/4227/files#diff-ef4366ac6fad81865865c07609a5388ce8c3e17f69292907304307dd3cd429beL70 removed the snippets file generation oopsie

fix(scripts): generate snippets.json files [skip-bc]

---

.github/workflows/check.yml
scripts/cli/index.ts
scripts/release/createReleasePR.ts

It's very annoying to add `[skip-bc]` to all PR because we slowed down our release cycle.
Now it will only be a warning in the sticky comment.

chore(scripts): only warn about breaking changes

---

specs/common/schemas/IndexSettings.yml

Fix capitalization of description fields for parameters related to banners.
🎟 JIRA Ticket:
- List changes

fix(specs): adjust style for banner descriptions

---

clients/algoliasearch-client-dart/.github/workflows/release.yml
clients/algoliasearch-client-dart/packages/client_composition/example/example.dart
clients/algoliasearch-client-dart/packages/client_composition/test/version_test.dart

https://github.com/algolia/api-clients-automation/actions/runs/12908009583/job/35993429541 fails because it's missing this test

fix(dart): version test

---

clients/algoliasearch-client-dart/packages/client_composition/README.md

The release is failing because a Dart package needs a README.

fix(dart): add readme for composition

---

specs/common/schemas/IndexSettings.yml

Port an edit from the docs repo: 
https://github.com/algolia/doc/pull/9693
Clarifying the behavior of `responseFields` with empty lists,
and slightly adjusting the style.
🎟 JIRA Ticket:
- List changes

fix(specs): responseFields description

---

.github/workflows/check.yml
tests/CTS/requests/search/searchSingleIndex.json
tests/CTS/requests/search/setSettings.json

This updates the snippets according to @gazconroy review in https://github.com/algolia/doc/pull/9688

guides: update the snippets according to the doc review

---

specs/advanced-personalization/common/responses/BadRequest.yml
specs/advanced-personalization/common/responses/BadUserID.yml
specs/advanced-personalization/common/responses/BaseResponse.yml
specs/advanced-personalization/common/responses/ConfigurationNotFound.yml
specs/advanced-personalization/common/responses/GenericNotFound.yml
specs/advanced-personalization/common/responses/GenericUnprocessableEntity.yml
specs/advanced-personalization/common/responses/InternalServerError.yml
specs/advanced-personalization/common/responses/InvalidUserID.yml
specs/advanced-personalization/common/responses/Unauthorized.yml
specs/advanced-personalization/common/responses/UserNotFound.yml
specs/advanced-personalization/common/schemas/Configuration.yml
specs/advanced-personalization/common/schemas/ErrorCodes.yml
specs/advanced-personalization/common/schemas/ErrorMessages.yml
specs/advanced-personalization/common/schemas/ErrorResponses.yml
specs/advanced-personalization/paths/config.yml
specs/advanced-personalization/paths/user.yml
specs/advanced-personalization/paths/users.yml

Instead of using the generic base response (see below), we detail the exact error message that is expected for each response.
🎟 JIRA Ticket: PRED-3384
- Change error code components to include detailed response codes and descriptions

feat(specs): detail perso error codes [PRED-3384]

---

clients/algoliasearch-client-php/composer.lock
templates/php/composer.mustache

🎟 JIRA Ticket: [DI-3448](https://algolia.atlassian.net/browse/DI-3448)
fixes https://github.com/algolia/algoliasearch-client-php/issues/747
[DI-3448]: https://algolia.atlassian.net/browse/DI-3448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(clients): mark php incompatible with 8.3.0

---

specs/common/schemas/Batch.yml

The example for `batchWriteParams` was wrongly constructed. The object in `example` is used as is (summary/value fields are for the `examples` field which is different. 
- Fix the `example` property of the `batchWriteParams` schema
N/A

fix(specs): fix batchWriteParams example

---

clients/algoliasearch-client-swift/Sources/Core/Helpers/Extensions.swift

fixes algolia/algoliasearch-client-swift#876
OpenAPI Generator overrides the default decoding/encoding methods for Decimal to be able to decode/encode from strings, in order to avoid losing precision
If users work with Decimal, it will override the default behavior for them
Also, we don't use the Decimal type in our specs, so it shouldn't be an issue for us
⚠️ For the future, here are some more details:
- OpenAPI Generator [uses a string to avoid losing precision](https://github.com/OpenAPITools/openapi-generator/pull/13589), because using a Double as an intermediary container WILL LOSE some
- When writing a spec, you can use a Decimal by specifying `{ "type": "string", "format": "decimal" }`, but we should avoid that and prefer a number type directly
- remove Decimal encoding/decoding …

fix(swift): don't overwrite decimal encoding/decoding methods

---

playground/php/src/search.php
templates/php/client_config.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/CR-7898 https://algolia.atlassian.net/browse/DI-3473
it is not possible to override the default value `maxRetries` value of the php client, and no parameters are provided at the `replaceAllObjects` level, this allows to configure it
alternatively, it could be a parameter on every method but seems redundant?

feat(php): add `setMaxRetries`

---

specs/composition-full/paths/search/searchForFacetValues.yml
specs/composition/spec.yml

🎟 JIRA Ticket: [EMERCH-1798](https://algolia.atlassian.net/browse/EMERCH-1798)
- lowercase a tag that was previously missed
- update composition API description
[EMERCH-1798]: https://algolia.atlassian.net/browse/EMERCH-1798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: more composition API update for docs

---

scripts/common.ts
scripts/docs/generate.ts

if we rename of remove existing guides/snippets they won't be deleted, this should take care of it

fix(scripts): cleanup guides gen before generation

---

templates/java/api_helpers.mustache

The `com.algolia.api.SearchClient#saveObjects(String, Iterable, boolean, RequestOptions)` method takes the `waitForTasks` parameter, but it is ignored and always set to `false`.
🎟 JIRA Ticket:
- Fixed the method by passing the `waitForTasks` parameter instead of hardcoding `false`

fix(java): saveObjects always passing waitForTasks as false

---

.github/workflows/issue.yml
templates/issue.yml

A new epic has been created just for APIC Github issues, [DI-3523](https://algolia.atlassian.net/browse/DI-3523)
Also add the component [API Clients And Frameworks](https://algolia.atlassian.net/issues/?jql=project%20%3D%20%22DI%22%20AND%20component%20%3D%20%22API%20Clients%20and%20Frameworks%22) to each created ticket.
[DI-3523]: https://algolia.atlassian.net/browse/DI-3523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(scripts): point jira issues to another epic

---

specs/crawler/common/schemas/action.yml
specs/crawler/common/schemas/configuration.yml
specs/crawler/spec.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DOC-1599
I made a bunch of changes on the [docs site](https://www.algolia.com/doc/tools/crawler/apis/overview/) to ensure the Crawler REST API is the one source of the truth. This update reflects and links to those changes

fix(specs): Update Crawler spec in line with doc site updates

---

specs/common/schemas/CustomRequest.yml
specs/common/schemas/IndexSettings.yml
specs/search/paths/advanced/getLogs.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DOC-1573
In common/schemas/IndexSettings, moved the description text from `optionalWordsArray` to `optionalWords` so that it’s visible when rendered by tools that are challenged by descriptions in `oneOf` (most of them)
Also updated:
- In search/paths/advanced/getLogs, format of `url` should be `uri-reference` since that allows relative URLs
- In search/paths/advanced/getLogs, maximum length of `answer` is 1,000 characters but the provided example was over 1,400 characters long
- In common/schemas/CustomRequest, corrected a small typo

fix(specs): Increase optionalWords visibility in docs

---

clients/algoliasearch-client-java/README.md

The `README.md` has a typo in the Getting Started code snippet. The variable `response` is used but never declared in the example. I declare the variables like we did on https://www.algolia.com/doc/libraries/java/v4/#test-your-installation code snippet.
- Declare the `response` var in the code snippet.

docs(java): fix typo on README

---

scripts/ci/codegen/pushToRepository.ts

idk why I added the auth step, as per https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-github-cli-in-workflows it's not required, the token is enough to login, and as per https://cli.github.com/manual/gh_help_environment, gh_token and github_token works

chore: remove gh auth login

---

.github/workflows/check.yml
scripts/ci/githubActions/createMatrix.ts
scripts/ci/githubActions/types.ts
scripts/common.ts

The improvements thanks to only running client that has changes is dwarfed by swift being so slow, we don't need this anymore.
And it's causing issues with guides because they are not in 1 folder by client

chore(ci): always run all clients

---

clients/algoliasearch-client-go/algolia/errs/net_err.go
clients/algoliasearch-client-go/algolia/errs/no_more_host_to_try_err.go
clients/algoliasearch-client-go/algolia/errs/wait_err.go
templates/go/client.mustache

This allow users to use `errors.Is` on our custom errors

fix(clients): implement Is on custom errors [skip-e2e]

---

clients/algoliasearch-client-python/algoliasearch/http/request_options.py

- `data` can be `None` in `request_options`

fix(python): npe in request options merge method

---

specs/ingestion/common/schemas/authentication.yml
specs/ingestion/common/schemas/common.yml
specs/ingestion/common/schemas/destination.yml
specs/ingestion/common/schemas/source.yml
specs/ingestion/common/schemas/task.yml
specs/ingestion/common/schemas/transformation.yml

🎟 JIRA Ticket: [DI-3653](https://algolia.atlassian.net/browse/DI-3653)
The `owner` attributes on ingestion resources is used to hide resources for internal use.
[DI-3653]: https://algolia.atlassian.net/browse/DI-3653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add the owner attributes to ingestion resources

---

clients/algoliasearch-client-python/algoliasearch/http/serializer.py

Added additional verification that converts Decimal to float in request body serializer.
Fixes ability to serialize and save Django models with DecimalField, resolves https://github.com/algolia/algoliasearch-django/issues/340

fix(python): missing Decimal to float conversion for body serializer

---

config/clients.config.json
config/clients.schema.json
generators/src/main/java/com/algolia/codegen/AlgoliaJavascriptGenerator.java
generators/src/main/java/com/algolia/codegen/cts/AlgoliaCTSGenerator.java
generators/src/main/java/com/algolia/codegen/cts/manager/JavascriptCTSManager.java

🎟 JIRA Ticket:
it requires manual intervention from an apic maintainer when someone wants to add a new client, because there's a bunch of condition for standalone clients to not be part of the `algoliasearch` package during the pre-release phase.
this pr adds a boolean to determine if the package should be included in `algoliasearch` or not (see composition), in order to eventually reduce the manual work required on that front.

chore: reduce manual intervention on javascript clients

---

specs/common/schemas/IndexSettings.yml
templates/kotlin/json_object_serializer.mustache
tests/CTS/requests/search/setSettings.json

fixes https://github.com/algolia/algoliasearch-client-go/issues/769
🎟 JIRA Ticket: [DI-3692](https://algolia.atlassian.net/browse/DI-3692)
The `userData` of the index settings can be anything since it's not serialized by the API, I tried with a string, an array, and a object and they are all accepted by the API.
I found out that we can generate the `any` type in all languages by just omitting the `type`, but this means its also nullable, not sure how to remove that.
[DI-3692]: https://algolia.atlassian.net/browse/DI-3692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(specs): userData is any type

---

specs/search/paths/objects/partialUpdate.yml

Add a small note on `partialUpdate` regarding aggregating multiple updates to the same record a single partial update.
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/CR-7983?focusedCommentId=535411
- Additional note on `partialUpdate`

docs(partialUpdate): add note about multiple operations

---

specs/ingestion/common/schemas/common.yml

🎟 JIRA Ticket: [CR-8231](https://algolia.atlassian.net/browse/CR-8231)
The `message` is not returned by the `push task` endpoint when `watcher=false`.
However the runID should be always returned.
[CR-8231]: https://algolia.atlassian.net/browse/CR-8231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(specs): message is not required in WatchResponse

---

specs/personalization/paths/deleteUserProfile.yml
specs/personalization/paths/getUserTokenProfile.yml
specs/personalization/paths/personalizationStrategy.yml
specs/personalization/spec.yml

Document the new rate limit for the personalization API.
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/PRED-3537
- Section added in specs/personalization/spec.yml that details the rate limit and the related headers.
N/A

docs(personalization): add rate limit information for personalization API

---

specs/ingestion/common/schemas/destination.yml

The `recordType` `collection` is used for destinations used by shopify.

fix(specs): add missing recordType collection

---

clients/algoliasearch-client-javascript/packages/client-composition/package.json
clients/algoliasearch-client-javascript/packages/composition/package.json

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3729
This should be enough for the next release to be the 1.0.0 of the JavaScript composition clients.

feat(javascript): prepare composition for stable release

---

specs/composition-full/common/schemas/listCompositionsResponse.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/CMP-424
- List changes
List composition endpoint response is enriched with response fields added since:
* https://github.com/algolia/metis/pull/11213
* https://github.com/algolia/metis/pull/11214
* CI
* Locally run
* `yarn cli build specs all`
* `yarn cli build clients javascript`

feat(specs): enrich response for list composition endpoint

---

specs/composition-full/common/schemas/listCompositionsResponse.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/CMP-424
- List changes
Follow up of https://github.com/algolia/api-clients-automation/pull/4819: fields `hitsPerPage`, `nbHits` and `page` are marked as required.
CI

feat(specs): make response fields required for composition list endpoint

---

specs/insights/paths/deleteUserToken.yml
specs/insights/paths/pushEvents.yml

Adds the required ACL to the Insights API endpoints, `search` for sending events, and `deleteObject` for deleting user token. After a request from a Support Engineer.
🎟 JIRA Ticket:
- List changes

fix(specs): add x-acl to insights endpoints

---

templates/csharp/guides/search/saveObjectsMovies.mustache
templates/dart/guides/search/saveObjectsMovies.mustache
templates/go/guides/search/saveObjectsMovies.mustache
templates/java/guides/search/saveObjectsMovies.mustache
templates/php/guides/search/saveObjectsMovies.mustache
templates/python/guides/search/saveObjectsMovies.mustache
templates/ruby/guides/search/saveObjectsMovies.mustache
templates/scala/guides/search/saveObjectsMovies.mustache
templates/swift/guides/search/saveObjectsMovies.mustache

🎟 JIRA Ticket: [SELFSER-1248](https://algolia.atlassian.net/browse/SELFSER-1248)
- Add a more explicit instruction comment towards write API key usage on API clients
[SELFSER-1248]: https://algolia.atlassian.net/browse/SELFSER-1248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

guides: update API key instructions

---

scripts/ci/codegen/pushToRepository.ts

- move must be done after files have been processed and copied
- stop dryrun before deleting the remote branch

fix(scripts): push to repository

---

specs/crawler/paths/crawler.yml

Fix a typo in the description of the patchCrawler spec.
🎟 JIRA Ticket:
- List changes

fix(specs): typo

---

clients/algoliasearch-client-javascript/packages/algoliasearch/__tests__/algoliasearch.common.test.ts
playground/javascript/node/algoliasearch.ts
templates/javascript/clients/algoliasearch/builds/definition.mustache
templates/javascript/clients/client/api/helpers.mustache

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3786
add the bridge methods from the search api to the ingestion api, only `saveObjects` and `partialUpdateObjects` are added for now.

feat(javascript): add bridge to transformation on algoliasearch

---

specs/abtesting-v3/paths/timeseries.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/jira/software/c/projects/OPTIM/boards/284?selectedIssue=OPTIM-1591
- Added `startDate`, `endDate`, and `metric` as query params
- Added `422` as potential status code for a response

feat(abtests): Add query params for GET /3/abtests/{id}/timeseries

---

generators/src/main/java/com/algolia/codegen/utils/OneOf.java
specs/common/schemas/IndexSettings.yml
tests/CTS/requests/search/getSettings.json
tests/CTS/requests/search/setSettings.json

🎟 JIRA Ticket: [CR-8559](https://algolia.atlassian.net/browse/CR-8559)
The `setSettings` accepts `true`, `false`, `"true"`, `"false"`, `"min"`, `"strict"` for `typoTolerance`,
but `getSettings` always returns a string.
It would be better to remove the `oneOf` entirely, but it would be a breaking change.
[CR-8559]: https://algolia.atlassian.net/browse/CR-8559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(specs): typoTolerance can be a boolean string

---

specs/search/paths/settings/settings.yml

getSettings should require `settings` ACL.
🎟 JIRA Ticket:
- List changes

fix(specs): wrong ACL for getSettings

---

playground/python/app/search.py
templates/go/configuration.mustache
templates/python/config.mustache
templates/python/tests/client/createClient.mustache

I've went with Go namestyle for this helper to set the region on the config by automatism, but realized while implementing the Java one that we've used the setters instead for other helpers (e.g. `SetClientApiKey`) or similar, in order to make the usage consistent, let's stick with this
The doc is not publicly released and no communication have been done on those helpers so better act quick, i'll do a release right away just after

fix(clients): consistent naming in transformation region helper

---

.github/workflows/check.yml

seems like this is more suitable if we want to cancel in progress matrix, which avoid waiting minuts before the next run https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#cancelled
see it in action when failure occurs, it continues https://github.com/algolia/api-clients-automation/actions/runs/15486920547

chore: use !cancelled instead of always

---

specs/ingestion/common/schemas/transformation.yml
tests/CTS/requests/ingestion/tryTransformation.json
tests/CTS/requests/ingestion/tryTransformationBeforeUpdate.json

A follow-up to https://github.com/algolia/api-clients-automation/pull/4901. 
This PR adds no-code transformations support to the try endpoint specs. 
- The try endpoint spec is updated.

feat(specs): update try transformation specs for no-code

---

specs/ingestion/paths/push.yml
templates/java/api_helpers.mustache
tests/CTS/requests/ingestion/push.json

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3903
this new property is only available on the push per index name endpoint

feat(specs): add new ingestion property for push

---

clients/algoliasearch-client-java/api/build.gradle

We used OSSRH to release our JVM clients, but the support has been dropped on the 30th of June: https://central.sonatype.org/pages/ossrh-eol/#central-support
Migrate to the new Maven Central Publishing.
I've generated a new token, it's stored in vault and the Java, Kotlin and Scala github secrets.

fix(clients): upgrade to maven central publishing

---

specs/ingestion/common/schemas/source.yml
specs/ingestion/paths/sources/runSource.yml

This updates the docs for the POST source run endpoint following https://github.com/algolia/data-ingestion/pull/5176

chore(sourceRun): update docs

---

specs/abtesting/spec.yml
specs/analytics/spec.yml

Turns out that this information was incorrect, `analytics.algolia.com` is just routing to `analytics.us.algolia.com`. 
🎟 JIRA Ticket: [CR-8865](https://algolia.atlassian.net/browse/CR-8865)
- List changes
[CR-8865]: https://algolia.atlassian.net/browse/CR-8865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(specs): analytics base url correction

---

templates/javascript/clients/client/builds/browser.mustache

Change the auth mode to default to header auth for the JS advanced perso client, due to query param based auth being disallowed in the API.
🎟 JIRA Ticket: none
- Change templates
n/a

feat(templates): use headers in js advanced perso client

---

clients/algoliasearch-client-java/.github/workflows/release.yml
clients/algoliasearch-client-java/api/build.gradle
clients/algoliasearch-client-kotlin/.github/workflows/release.yml
clients/algoliasearch-client-scala/.github/workflows/release.yml
clients/algoliasearch-client-scala/build.sbt
clients/algoliasearch-client-scala/project/plugins.sbt
config/generation.config.mjs
generators/src/main/java/com/algolia/codegen/AlgoliaScalaGenerator.java
templates/java/gradle.properties.mustache
templates/kotlin/gradle.properties.mustache

Retry to upgrade, for all clients this time, because #5055 didn't work.

chore(clients): correctly upgrade to maven central publishing

---

specs/abtesting/common/schemas/Variant.yml

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/CR-8944
the average is not always an integer

fix(specs): `averageClickPosition` return type

---

specs/advanced-personalization/common/schemas/RealtimeUser.yml

Add `lastUpdatedAt` property to Advanced-Personalization Real-time user response.

feat(specs): add lastUpdatedAt to personalization real-time user

---

clients/algoliasearch-client-go/CHANGELOG.md
config/clients.config.json
docs/versions-history-with-sla-and-support-policy.json

- ~csharp: 7.23.1 (no commit)~
- ~dart: 1.34.2 (no commit)~
- go: 4.22.1 -> **`patch` _(e.g. 4.22.2)_**
- ~java: 4.22.1 (no commit)~
- ~javascript: 5.34.1 (no commit)~
- ~kotlin: 3.25.1 (no commit)~
- ~php: 4.25.1 (no commit)~
- ~python: 4.23.1 (no commit)~
- ~ruby: 3.22.1 (no commit)~
- ~scala: 2.24.1 (no commit)~
- ~swift: 9.25.1 (no commit)~
_(None)_

chore: prepare release 2025-07-25

---

scripts/cts/testServer/accountCopyIndex.ts
specs/search/helpers/accountCopyIndex.yml
templates/javascript/clients/client/api/nodeHelpers.mustache
templates/javascript/clients/client/model/clientMethodProps.mustache
tests/CTS/client/search/accountCopyIndex.json

🎟 JIRA Ticket: [CR-8910](https://algolia.atlassian.net/browse/CR-8910)
Customers want to configure the `batchSize` when using `accountCopyIndex`, we can just forward the value to the other helpers.
[CR-8910]: https://algolia.atlassian.net/browse/CR-8910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(clients): add batchSize to accountCopyIndex

---

.github/workflows/check.yml
scripts/ci/codegen/spreadGeneration.ts
scripts/ci/codegen/waitForAllReleases.ts

Make the release non-blocking, it will only create the github release for the language that succeeded to release, and send a slack message for the one that failed.
We can retry the CI since it will only try to release languages that have changes.

chore(scripts): allow retry of the release

---

specs/composition-full/common/schemas/components/CompositionBehavior.yml
specs/composition-full/common/schemas/responses/Hit.yml

🎟 JIRA Ticket: [CMP-485](https://algolia.atlassian.net/browse/CMP-485)
Add support for the new `metadata` field on `injectedItems` and the corresponding `_extra` field on each `hit`.
- Add the `metadata` property to `injectedItems`
- It currently only has a `hits` property. You can see the full details [here](https://algolia.atlassian.net/wiki/spaces/CMP/pages/5149753345/Models#Key-definition).
- Add the `_extra` property to `hit`
- This contains the metadata specified in `injectedItems` + an optional `_injectedItemKey` property
- Green CI
[CMP-485]: https://algolia.atlassian.net/browse/CMP-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(specs): add fields for metadata in composition injectedItems

---

specs/composition-full/paths/objects/objects.yml
specs/composition-full/paths/rules/rule.yml
tests/CTS/requests/composition-full/deleteComposition.json
tests/CTS/requests/composition-full/deleteCompositionRule.json
tests/CTS/requests/composition-full/putComposition.json
tests/CTS/requests/composition-full/putCompositionRule.json

🎟 JIRA Ticket: 
- https://algolia.atlassian.net/browse/CMP-452
- Add PUT and DELETE actions to `/1/compositions/{compositionID}/` for Compositions
- Add PUT and DELETE actions to `/1/compositions/{compositionID}/rules/{ruleID}` for Composition Rules
CI

feat(specs): add put and delete API for compositions and rules

---

specs/composition-full/common/params/Composition.yml
specs/composition-full/common/schemas/components/CompositionBehavior.yml
specs/composition-full/common/schemas/components/InjectionSource.yml
specs/composition-full/common/schemas/requestBodies/RunParams.yml
tests/CTS/requests/composition-full/putComposition.json
tests/CTS/requests/composition-full/search.json

🎟 JIRA Ticket: 
- https://algolia.atlassian.net/browse/CMP-486
as part of 
- https://algolia.atlassian.net/browse/CMP-471
- Add `external` injection search source
- `injectedItems` can now either be a `search` or `external` source.
- Add `injectedItems` compositions runtime parameter.
CI

feat(specs): add external injection source definition and runtime parameter

---

.github/workflows/check.yml
templates/kotlin/gradle.properties.mustache

The Kotlin released failed because of OOM https://github.com/algolia/algoliasearch-client-kotlin/actions/runs/17431280970/job/49490485139#step:5:639
Also edit the slack message.

chore(scripts): increase memory for kotlin release

---

clients/algoliasearch-client-python/algoliasearch/http/retry.py
playground/python/app/search.py
playground/python/poetry.lock

🎟 JIRA Ticket:
discovered while trying https://github.com/algolia/api-clients-automation/issues/5337, we already check for that in the `_is_success` method

chore(python): remove redundant check

---

specs/advanced-personalization/paths/computeRealtimeUser.yml
specs/advanced-personalization/paths/getRealtimeUser.yml

Deprecate the `compute real-time user` endpoint.
The Real-time Personalization feature now does this behind the scenes automatically.
I also updated the description of the `getRealtimeUser` endpoint to make it clearer to differentiate with the "regular" get-profile endpoint

feat(specs): deprecate Predict real-time endpoints

---

scripts/buildLanguages.ts
specs/search/helpers/deleteObjects.yml
specs/search/helpers/generateSecuredApiKey.yml
specs/search/helpers/indexExists.yml
specs/search/helpers/partialUpdateObjects.yml
specs/search/helpers/replaceAllObjects.yml
specs/search/helpers/saveObjects.yml
specs/search/helpers/waitForApiKey.yml
specs/search/helpers/waitForAppTask.yml
specs/search/helpers/waitForTask.yml
templates/dart/snippets/method.mustache

Noticed by @kai687, we don't validate dart snippets and some helpers that we call in the snippets don't exists.
We can remove the snippets for now, and validate dart files so this doesn't happen again.

snippets: remove snippets for non-existing helpers

---

scripts/ci/codegen/types.ts

👋 Used the wrong output directory, this PR aims to fix that
- Updates n8n-nodes-algolia output path for generated spec files

chore(n8n): update output path

---

specs/composition/common/schemas/components/CompositionBehavior.yml
tests/CTS/requests/composition/multipleBatch.json
tests/CTS/requests/composition/putComposition.json
tests/CTS/requests/composition/putCompositionRule.json
tests/CTS/requests/composition/saveRules.json

🎟 JIRA Ticket: https://algolia.atlassian.net/browse/CMP-539
- Added deduplication.positioning setting to Composition Injection
- Added Composition and Composition Rule tests
- Added Composition Batch and Batch Rules tests
CTS

feat(specs): add compositions deduplication setting

---

.github/workflows/scheduled-release.yml
scripts/release/updateAPIVersions.ts

The release is not working from the CI because when we use `setVerbose(true)`, the behavior of the `run` function is different and might return unexpected results.
Removing `setVerbose(CI)` might solve the issues.

chore(scripts): dont use verbose when releasing from the CI
