algolia/api-clients-automation

.github/workflows/renovate.yml
🎟 JIRA Ticket: [APIC-589](https://algolia.atlassian.net/browse/APIC-589)
Use optional params to configure the dependencies pull request.
Wait until friday
=> chore(deps): custom params for renovate action

clients/algoliasearch-client-java-2/CHANGELOG.md, clients/algoliasearch-client-javascript/CHANGELOG.md, clients/algoliasearch-client-javascript/packages/client-common/package.json, clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json, clients/algoliasearch-client-javascript/packages/requester-fetch/package.json, clients/algoliasearch-client-javascript/packages/requester-node-http/package.json, clients/algoliasearch-client-php/CHANGELOG.md, config/clients.config.json, config/openapitools.json
- javascript: 5.0.0-alpha.2 -> **`prerelease` _(e.g. 5.0.0-alpha.3)_**
- java: 4.4.1-SNAPSHOT -> **`patch` _(e.g. 4.4.2-SNAPSHOT)_**
- php: 4.0.0-alpha.7 -> **`prerelease` _(e.g. 4.0.0-alpha.8)_**
_(None)_
=> chore: prepare release 2022-07-28

templates/php/tests/requests/requests.mustache
🎟 JIRA Ticket: APIC-591
- Add tests for POST requests with empty body according to what was done for js and java.
- CI
=> fix(php): Test post empty body

templates/php/composer.mustache
Added a small change on the dependencies of the composer.json since there's an issue when I try to install the PHP client on a raw laravel app.
CI
=> fix(php): composer dependency

README.md
Link does not work in the README.md
Click link
=> chore: fix license link

.github/workflows/renovate.yml
=> chore(deps): fix version of bodinsamuel/renovate-automatic-branch

specs/ingestion/common/parameters.yml, specs/ingestion/spec.yml
- Add dot to description
- Fix the path
- Fix the taskID param
=> fix(specs): mistakes in the ingestion spec

netlify.toml, website/package.json, website/yarn.lock
bump docs deps for security issue
=> chore: bump docs deps

specs/ingestion/common/schemas/source.yml
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-755
This updates the client with the new CT input payload
=> fix(specs): new CT source input

tests/output/javascript/package.json
Seems like it exit 1 when no tests are found
=> fix(javascript): pass with no tests

specs/ingestion/common/schemas/source.yml
Add an example to the `locales`
=> fix(javascript): update ingestion specs

clients/algoliasearch-client-java-2/CHANGELOG.md, clients/algoliasearch-client-javascript/CHANGELOG.md, clients/algoliasearch-client-javascript/packages/client-common/package.json, clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json, clients/algoliasearch-client-javascript/packages/requester-fetch/package.json, clients/algoliasearch-client-javascript/packages/requester-node-http/package.json, clients/algoliasearch-client-php/CHANGELOG.md, config/clients.config.json, config/openapitools.json
- javascript: 5.0.0-alpha.31 -> **`prerelease` _(e.g. 5.0.0-alpha.32)_**
- php: 4.0.0-alpha.31 -> **`prerelease` _(e.g. 4.0.0-alpha.32)_**
_(None)_
=> chore: prepare release 2023-01-13

specs/ingestion/paths/tasks/disableTask.yml, specs/ingestion/paths/tasks/enableTask.yml
=> fix(specs): fix method for task enable/disable status

clients/algoliasearch-client-java-2/CHANGELOG.md, clients/algoliasearch-client-javascript/CHANGELOG.md, clients/algoliasearch-client-javascript/packages/client-common/package.json, clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json, clients/algoliasearch-client-javascript/packages/requester-fetch/package.json, clients/algoliasearch-client-javascript/packages/requester-node-http/package.json, clients/algoliasearch-client-php/CHANGELOG.md, config/clients.config.json, config/openapitools.json
This reverts commit 7fb00d1cfa2317fecd1477bd8b576800d707daa8.
Release is failing for some reason, checking...
=> chore: revert "chore: prepare release 2023-01-19 (#1247)"

specs/ingestion/common/schemas/authentication.yml, specs/ingestion/common/schemas/destination.yml, specs/ingestion/common/schemas/source.yml, specs/ingestion/common/schemas/task.yml, specs/ingestion/paths/authentications/searchAuthentications.yml, specs/ingestion/paths/destinations/searchDestinations.yml, specs/ingestion/paths/sources/searchSources.yml, specs/ingestion/paths/tasks/searchTasks.yml, specs/ingestion/spec.yml
🎟 JIRA Ticket: [DI-895](https://algolia.atlassian.net/browse/DI-895)
Add search endpoints to the following APIs:
- tasks
- sources
- destinations
- authentications
[DI-895]: https://algolia.atlassian.net/browse/DI-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(specs): add search endpoint to every item type

specs/ingestion/common/schemas/task.yml, templates/javascript/clients/api-single.mustache, templates/javascript/clients/client/api/guards.mustache
🎟 JIRA Ticket: Related to [DI-873](https://algolia.atlassian.net/browse/DI-873)
- export type guard functions directly
- handle undefined trigger value
[DI-873]: https://algolia.atlassian.net/browse/DI-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(javascript): improve on task trigger type guards

templates/javascript/clients/client/builds/imports.mustache
🎟 JIRA Ticket: Related to [DI-873](https://algolia.atlassian.net/browse/DI-873)
Export type guards from each build entrypoints
[DI-873]: https://algolia.atlassian.net/browse/DI-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(javascript): export task trigger guards from each build entrypoints

specs/ingestion/common/authenticationParameters.yml, specs/ingestion/common/destinationParameters.yml, specs/ingestion/common/observabilityParameters.yml, specs/ingestion/common/parameters.yml, specs/ingestion/common/schemas/source.yml, specs/ingestion/common/sourceParameters.yml, specs/ingestion/common/taskParameters.yml, specs/ingestion/paths/authentications/authentications.yml, specs/ingestion/paths/destinations/destinations.yml, specs/ingestion/paths/runs/events/events.yml, specs/ingestion/paths/runs/runs.yml, specs/ingestion/paths/sources/sources.yml, specs/ingestion/paths/tasks/tasks.yml
🎟 JIRA Ticket: related to [DI-891](https://algolia.atlassian.net/browse/DI-891)
Add `sort` and `order` keys for all list endpoints:
- authentications
- sources
- destinations
- tasks
- events
- runs
[DI-891]: https://algolia.atlassian.net/browse/DI-891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(specs): add sort and order handling in query parameters

specs/ingestion/paths/authentications/authenticationID.yml, specs/ingestion/paths/destinations/destinationID.yml, specs/ingestion/paths/sources/sourceID.yml, specs/ingestion/paths/tasks/taskID.yml
🎟 JIRA Ticket: Related to [DI-962](https://algolia.atlassian.net/browse/DI-962)
Replaced `204 No Content` status code for all APIs DELETE endpoints by a `200 OK`
Wait for https://github.com/algolia/data-ingestion/pull/1056 before merging
[DI-962]: https://algolia.atlassian.net/browse/DI-962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(specs): make DELETE endpoints return a 200 OK

clients/algoliasearch-client-java-2/CHANGELOG.md, clients/algoliasearch-client-javascript/CHANGELOG.md, clients/algoliasearch-client-javascript/packages/client-common/package.json, clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json, clients/algoliasearch-client-javascript/packages/requester-fetch/package.json, clients/algoliasearch-client-javascript/packages/requester-node-http/package.json, clients/algoliasearch-client-php/CHANGELOG.md, config/clients.config.json, config/openapitools.json
- javascript: 5.0.0-alpha.46 -> **`prerelease` _(e.g. 5.0.0-alpha.47)_**
- php: 4.0.0-alpha.44 -> **`prerelease` _(e.g. 4.0.0-alpha.45)_**
_(None)_
=> chore: prepare release 2023-02-15

specs/ingestion/common/schemas/source.yml
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-851
- `UniqueIDColumn` added to `SourceJSON` spec
=> fix(specs): add `UniqueIDColumn` property to `SourceJSON` input

specs/ingestion/paths/runs/events/events.yml
Add back events pagination now that it works better.
=> fix(specs): add pagination to events

specs/ingestion/common/schemas/source.yml
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1029
This PR adds the new fields to the source spec for a BigCommerce integration
=> feat(specs): add new BigCommerce source fields

clients/algoliasearch-client-java-2/CHANGELOG.md, clients/algoliasearch-client-javascript/CHANGELOG.md, clients/algoliasearch-client-javascript/packages/client-common/package.json, clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json, clients/algoliasearch-client-javascript/packages/requester-fetch/package.json, clients/algoliasearch-client-javascript/packages/requester-node-http/package.json, clients/algoliasearch-client-php/CHANGELOG.md, config/clients.config.json, config/openapitools.json
- javascript: 5.0.0-alpha.52 -> **`prerelease` _(e.g. 5.0.0-alpha.53)_**
- php: 4.0.0-alpha.50 -> **`prerelease` _(e.g. 4.0.0-alpha.51)_**
_(None)_
=> chore: prepare release 2023-03-14

.github/workflows/check.yml, generators/src/main/java/com/algolia/codegen/cts/AlgoliaCTSGenerator.java, generators/src/main/java/com/algolia/codegen/cts/tests/TestsClient.java, generators/src/main/java/com/algolia/codegen/cts/tests/TestsRequest.java, generators/src/main/java/com/algolia/codegen/exceptions/CTSException.java, scripts/buildClients.ts, scripts/common.ts
Add the name of the CTS test in the error message to ease debugging.
The diff is misleading, the only change is the indentation.
=> fix(scripts): report testName in error

templates/javascript/clients/client/api/guards.mustache
Update task trigger guard so we can use TaskCreateTrigger with them, since its signature changed
=> fix(specs): task trigger guard update

templates/javascript/clients/client/api/guards.mustache
Update task trigger guard import order so it matches the linter's
=> fix(specs): task trigger guard import order

specs/ingestion/common/schemas/event.yml
🎟 JIRA Ticket: [DI-1201](https://algolia.atlassian.net/browse/DI-1201)
Add the new `transform` event type, used by pipeline during flow steps.
[DI-1201]: https://algolia.atlassian.net/browse/DI-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(specs): add transform event type

specs/predict/responses/Segment.yml, tests/CTS/methods/requests/ingestion/createTask.json
Fixes necessary API/CTS specifications for Kotlin API client to pass
- CTS specs
- API specs
=> fix(specs): update required for kotlin tests to pass

specs/ingestion/common/schemas/run.yml
🎟 JIRA Ticket: DI-1351
- Add `blocking` to possible `RunOutcome` values
=> fix(specs): add blocking run outcome

.github/actions/setup/action.yml
Release setup process requires having dart environment to generate changelog and versions update.
Remove the condition to setup dart.
=> chore(ci): dart env for release process

website/docs/clients/guides/delete-objects.mdx, website/sidebars.js
🎟 JIRA Ticket: APIC-521
This PR adds a guide showing how to delete multiple objects using `batch`.
[Preview](https://deploy-preview-1667--api-clients-automation.netlify.app/docs/clients/guides/delete-objects)
=> docs(guides): delete multiple objects using batch

specs/search/paths/objects/batch.yml, specs/search/paths/objects/clearObjects.yml, specs/search/paths/objects/common/schemas.yml, specs/search/paths/objects/deleteBy.yml, specs/search/paths/objects/getObjects.yml, specs/search/paths/objects/multipleBatch.yml, specs/search/paths/objects/object.yml, specs/search/paths/objects/objects.yml, specs/search/paths/objects/partialUpdate.yml
This PR reviews just the record operations of the Search API.
Is there a better way to phrase this? It’s difficult to understand.
“If you specify a nested attribute, the engine treats it as a replacement of its first-level ancestor.”
=> docs(specs): Review OpenAPI Search API (record operations)

specs/search/paths/vault/appendSource.yml, specs/search/paths/vault/common/schemas.yml, specs/search/paths/vault/deleteSource.yml, specs/search/paths/vault/vaultSources.yml
This PR reviews just the vault operations of the Search API.
=> docs(specs): Review OpenAPI Search API (vault operations)

specs/analytics/common/parameters.yml, specs/analytics/paths/click/getAverageClickPosition.yml, specs/analytics/paths/click/getClickPositions.yml, specs/analytics/paths/click/getClickThroughRate.yml, specs/analytics/paths/click/getConversionRate.yml
This is one of several PRs addressing the Analytics API.
This PR reviews just the click analytics operations of the Analytics API.
🎟 JIRA Ticket: [DOC-1112](https://algolia.atlassian.net/browse/DOC-1112)
Update summary, description and examples
[DOC-1112]: https://algolia.atlassian.net/browse/DOC-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(specs): Review OpenAPI Analytics (click analytics)

scripts/docker/build.sh, website/docs/contributing/release-process.md
updates the doc to reflect the new usage of the release process, also copy the .env file if it doesn't exist.
=> docs: update release process

Dockerfile, scripts/common.ts, scripts/package.json
ssh via docker was broken because:
- ssh wasn't available anymore in the image
- docker keeps quotes when using the env var, so wrong credentials error 🤷🏻
=> fix(scripts): release script with ssh

renovate.json
=> chore: fix renovate for Dart

clients/algoliasearch-client-java/.github/workflows/release.yml, clients/algoliasearch-client-java/algoliasearch/gradle.properties, generators/src/main/java/com/algolia/codegen/AlgoliaJavaGenerator.java, templates/java/gradle.properties.mustache
- Add `gradle.properties` generation
- Fix the CI to properly make a release _(create staging, upload and close)_
=> chore(ci): update java release CI

scripts/release/common.ts
the new tag name is invalid, my bad
=> fix(scripts): remove spaces from tag name

specs/ingestion/common/schemas/source.yml
update specs to reflect BigCommerce additions
=> feat(specs): update ingestion specs for BigCommerce

clients/algoliasearch-client-dart/packages/client_core/CHANGELOG.md
- add `client_core` missing a changelog
=> chore(dart): add missing changelog entry

.github/workflows/renovate.yml
upgrade to see if https://github.com/bodinsamuel/renovate-automatic-branch/issues/300 have been fixed
job https://github.com/algolia/api-clients-automation/actions/runs/6046430277/job/16407996398
=> chore: upgrade renovate-automatic-branch

specs/ingestion/common/schemas/source.yml
- remove the `outputFile` unused property from the Docker source
=> feat(javascript): remove unused property

clients/algoliasearch-client-go/CHANGELOG.md, clients/algoliasearch-client-java/CHANGELOG.md, clients/algoliasearch-client-javascript/CHANGELOG.md, clients/algoliasearch-client-javascript/packages/algoliasearch/package.json, clients/algoliasearch-client-javascript/packages/client-abtesting/package.json, clients/algoliasearch-client-javascript/packages/client-analytics/package.json, clients/algoliasearch-client-javascript/packages/client-common/package.json, clients/algoliasearch-client-javascript/packages/client-insights/package.json, clients/algoliasearch-client-javascript/packages/client-personalization/package.json, clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json, clients/algoliasearch-client-javascript/packages/client-search/package.json, clients/algoliasearch-client-javascript/packages/ingestion/package.json, clients/algoliasearch-client-javascript/packages/monitoring/package.json, clients/algoliasearch-client-javascript/packages/recommend/package.json, clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json, clients/algoliasearch-client-javascript/packages/requester-fetch/package.json, clients/algoliasearch-client-javascript/packages/requester-node-http/package.json, clients/algoliasearch-client-kotlin/CHANGELOG.md, clients/algoliasearch-client-php/CHANGELOG.md, config/clients.config.json
This is a manual release because everything is broken
=> chore: prepare release 2023-09-07

clients/algoliasearch-client-javascript/package.json
nx cache seems broken, lets disable it for a moment until we find the issue
see all attempts https://github.com/algolia/api-clients-automation/actions/runs/6183577894/job/16788300465
=> fix(scripts): disable nx cache

specs/ingestion/common/schemas/event.yml
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1521
- add batchSize to the observability event object
=> feat(javascript): add batchSize to the observability event object

clients/algoliasearch-client-dart/.github/workflows/publish.yml
- CI: fix dart packages directories
=> chore(dart): update ci packages directories

specs/ingestion/common/schemas/task.yml
🎟 JIRA Ticket: [DI-1534]
- add a new `partial` task action type
[DI-1534]: https://algolia.atlassian.net/browse/DI-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(javascript): add partial task action type

specs/ingestion/common/schemas/run.yml
🎟 JIRA Ticket: [DI-1493]
- add run `discover` type
[DI-1493]: https://algolia.atlassian.net/browse/DI-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(javascript): handle run discover type

specs/ingestion/common/schemas/source.yml
- Synchronize specs for all clients
=> feat(specs): synchronize specs for all client

playground/go/recommend.go
- Because it's a pain in the 🍑 when trying to run the go playground.
=> fix(playground): update go recommend test

specs/ingestion/common/schemas/run.yml, specs/ingestion/common/schemas/task.yml
🎟 JIRA Ticket: DI-1601
- Add `failureThreshold` to `Task` and `TaskUpdate` types
=> feat(specs): Add `failureThreshold` to `Task` and `TaskUpdate` types

specs/ingestion/common/schemas/task.yml
🎟 JIRA Ticket: DI-1601
- Change trigger input for task update to allow changing cron
=> fix(specs): Change trigger input for task update

.lintstagedrc
Add specs to the pre-commit linter
=> chore(specs): lint --fix on pre-commit

specs/ingestion/common/schemas/run.yml
=> fix(specs): require `window` in list runs

specs/ingestion/common/observabilityParameters.yml, specs/ingestion/paths/runs/events/events.yml, specs/ingestion/paths/runs/runs.yml
events now allow the `startDate` and `endDate` query parameters to be passed.
=> feat(specs): add `startDate` and `endDate` query parameter to list events

scripts/website/build.sh, website/.gitignore, website/docs/clients/installation.mdx, website/docusaurus.config.js, website/src/variables.js
🎟 JIRA Ticket: [DI-1653](https://algolia.atlassian.net/browse/DI-1653)
We can use variable interpolation to display the correct version in the installation doc
[DI-1653]: https://algolia.atlassian.net/browse/DI-1653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: use the correct client version

config/generation.config.mjs, generators/src/main/java/com/algolia/codegen/AlgoliaPythonGenerator.java, playground/python/app/abtesting.py, playground/python/app/analytics.py, playground/python/app/ingestion.py, playground/python/app/insights.py, playground/python/app/personalization.py, playground/python/app/query_suggestions.py, playground/python/app/recommend.py, playground/python/app/search.py, scripts/formatter.ts, templates/python/__init.client__.mustache, templates/python/__init.http__.mustache, templates/python/__init.model__.mustache, templates/python/__init.package__.mustache, templates/python/api.mustache, templates/python/config.mustache, templates/python/imports.mustache, templates/python/model.mustache, templates/python/model_anyof.mustache, templates/python/model_enum.mustache, templates/python/model_generic.mustache, templates/python/model_oneof.mustache, templates/python/version.mustache
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1667
- fixes response deserializing
- use latest pydantic methods to output JSON data
- remove defaults API values from the API client
- remove unused serialized/deserializer helpers
- fixes region fallback definition
- improve imports to prevent user finding the correct files
next step will be about CTS coverage
=> fix(python): deserializer and unused helpers

specs/search/paths/objects/objects.yml
`POST /1/indexes/{indexName}` returns a `201 Created` on success, not a 200.
🎟 JIRA Ticket: n/a
- Change return code and description for the success response for this operation.
=> docs: return code for objects endpoint

scripts/common.ts, scripts/pre-gen/removeExistingCodegen.ts
the snake cased folders were not deleted, resulting in the query_suggestions client being outdated
=> chore: correctly delete python on pregen

clients/algoliasearch-client-ruby/.rubocop.yml, clients/algoliasearch-client-ruby/Gemfile, clients/algoliasearch-client-ruby/Rakefile, clients/algoliasearch-client-ruby/algolia.gemspec, clients/algoliasearch-client-ruby/lib/algolia.rb, clients/algoliasearch-client-ruby/lib/algolia/api_client.rb, clients/algoliasearch-client-ruby/lib/algolia/api_error.rb, clients/algoliasearch-client-ruby/lib/algolia/configuration.rb, clients/algoliasearch-client-ruby/lib/algolia/http/http_requester.rb, clients/algoliasearch-client-ruby/lib/algolia/transport/request_options.rb, clients/algoliasearch-client-ruby/lib/algolia/transport/retry_strategy.rb, clients/algoliasearch-client-ruby/lib/algolia/transport/stateful_host.rb, clients/algoliasearch-client-ruby/lib/algolia/transport/transport.rb, clients/algoliasearch-client-ruby/lib/algolia/user_agent.rb, scripts/formatter.ts, templates/ruby/api.mustache, templates/ruby/base_object.mustache, templates/ruby/partial_model_generic.mustache, templates/ruby/partial_oneof_module.mustache
Use a different set of linter rules to better match our repository and the generated code.
=> fix(ruby): customize linter

generators/src/main/java/com/algolia/codegen/AlgoliaJavascriptGenerator.java, templates/javascript/clients/api-single.mustache, templates/javascript/clients/client/README.md, templates/javascript/clients/client/builds/browser.mustache, templates/javascript/clients/client/builds/imports.mustache, templates/javascript/clients/client/builds/node.mustache, templates/javascript/clients/package.mustache
we can use lambdas instead of generating a property for it
=> chore(javascript): remove some non needed props from generators

clients/algoliasearch-client-python/README.md, clients/algoliasearch-client-python/algoliasearch/http/api_response.py, clients/algoliasearch-client-python/algoliasearch/http/request_options.py, clients/algoliasearch-client-python/algoliasearch/http/transporter.py, templates/python/api.mustache, templates/python/config.mustache, templates/python/tests/client/suite.mustache
🎟 JIRA Ticket:
Some cleanup on the Python client, add the final readme, fix some variable name and type def
=> chore(python): cleanup and variable names

clients/algoliasearch-client-python/algoliasearch/http/helpers.py, clients/algoliasearch-client-python/algoliasearch/http/serializer.py, playground/javascript/node/search.ts, templates/python/search_helpers.mustache
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-1737
add missing browse helpers in the Python client, and also fix some helpers related stuff
=> feat(python): add browse helpers

clients/algoliasearch-client-python/.github/workflows/release.yml
remove poetry cache for python, it's a rarely ran job anyway we don't need it
=> fix(python): python and ruby release

website/docs/clients/migration-guides/index.mdx
🎟 JIRA Ticket: DI-1738
- Add PHP code sample for A/B Testing
=> docs: add PHP code sample for A/B Testing

generators/src/main/java/com/algolia/codegen/cts/tests/TestsClient.java, snippets/ruby/.rubocop.yml, templates/dart/tests/client/step.mustache, templates/java/tests/client/step.mustache, templates/javascript/tests/client/step.mustache, templates/kotlin/tests/client/step.mustache, templates/python/tests/client/step.mustache, templates/scala/tests/client/step.mustache, tests/output/ruby/.rubocop.yml
Fight with rubocop to make something nice on the eye.
Also remove unused `isVariable`.
=> fix(ruby): make the snippets pretty

specs/abtesting/common/schemas/Variant.yml
🎟 JIRA Ticket: [OPTIM-1016]
- Add `trackedUserCount` to the variant response for an AB test.
Green CI
[OPTIM-1016]: https://algolia.atlassian.net/browse/OPTIM-1016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(specs): AB testing tracked user count

.github/workflows/check.yml, scripts/ci/codegen/pushSpecsToNewWorldDocs.ts, scripts/ci/codegen/waitForAllReleases.ts
This step didn't trigger on the last release, maybe because the condition was wrong, let's try in js instead.
=> fix(scripts): check for last commit in js

specs/query-suggestions/common/responses/Unauthorized.yml
Follow up of #2604
Updating the QS Unauthorized examples to remove the "Missing Admin API Key" one and replace it with "Missing ACL". 
I'm not sure if I followed the proper formatting, please let me know! I also assumed that everything under "bundled" was generated so I did not touch anything there.
=> feat(specs): update query suggestions unauthorized response example 

.github/workflows/check.yml, scripts/ci/codegen/pushSpecsToNewWorldDocs.ts
The CI failed on main, because the git command is malformed.
=> fix(scripts): push origin for new docs

clients/algoliasearch-client-swift/Sources/Core/Networking/RetryStrategy/AlgoliaRetryStrategy.swift, templates/swift/client_configuration.mustache
🎟 JIRA Ticket: [DI-1794]
- fix retry strategy not selecting the next host in the list
- handle custom hosts in client configuration
[DI-1794]: https://algolia.atlassian.net/browse/DI-1794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(swift): retry strategy

scripts/cli/index.ts, scripts/cts/runCts.ts, specs/ingestion/common/schemas/source.yml
follow up of https://github.com/algolia/data-ingestion/pull/2566
=> fix(specs): allow custom fields to be nullable

templates/swift/Package.mustache, templates/swift/api.mustache, templates/swift/tests/Package.mustache, tests/output/swift/Tests/Utils/MockSearchClient.swift, tests/output/swift/Tests/handwritten/Browsers.swift, tests/output/swift/Tests/handwritten/Waiters.swift
🎟 JIRA Ticket: [DI-1746]
- browseObjects
- browseRules
- browseSynonyms
- searchForHits
- searchForFacets
Added handwritten tests for each helper
[DI-1746]: https://algolia.atlassian.net/browse/DI-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(swift): remaining helpers

templates/javascript/tests/requests/helpers.mustache
seems like I merged with a broken test https://github.com/algolia/api-clients-automation/actions/runs/8020801101/job/21911507593, this PR tries to fix it
=> chore(javascript): broken tests

.github/workflows/check.yml
- run macOS CTS CI only on release PR
- also check for podspec validation and duplicates
=> fix(swift): better macOS CI

templates/javascript/clients/client/api/helpers.mustache, templates/javascript/clients/client/api/nodeHelpers.mustache
Fix the casing in the JSdoc and also a failed copy paste (sorry) that left an unwanted param
=> fix(javascript): extra parameter in jsdoc def

website/docs/contributing/docs.md
Fix a typo in the contribution guide.
=> docs: fix typo

CODEOWNERS
- @kai687 is one of the more active contributors to the specs and website parts of this project
=> feat(specs): promote @kai687 to code owner

clients/algoliasearch-client-swift/PrivacyInfo.xcprivacy
- add newly required Apple privacy manifest
=> chore(swift): add privacy manifest

config/generation.config.mjs, scripts/husky/pre-commit.mjs, tests/CTS/requests/abtesting/listABTests.json
Instead of creating a new abtest every 3 month because of abtest limit, @JonathanMontane created a abtest that last a 100 year ! (thanks a lot)
Also fix python init files
=> fix(cts): use a ever lasting abtest

clients/algoliasearch-client-kotlin/.github/workflows/release.yml
- We were not automatically releasing new Kotlin versions
=> fix(kotlin): ci release workflow

scripts/release/createReleasePR.ts
maintenance dates were not properly set, it would change their starting date to today
also prevent support of multiple patch versions
=> fix(scripts): properly handle maintenance versions

.github/actions/setup/action.yml, renovate.json, scripts/docker/Dockerfile.swift
🎟 JIRA Ticket: [DI-2469](https://algolia.atlassian.net/browse/DI-2469)
We have a discrepancy between local and CI that make weird format on the generated code, we can sync the versions.
[DI-2469]: https://algolia.atlassian.net/browse/DI-2469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(deps): automatically update swiftformat

specs/ingestion/common/schemas/common.yml, specs/ingestion/common/schemas/task.yml
=> fix(specs): ingestion cursor for task

scripts/husky/pre-commit.mjs, scripts/release/createReleasePR.ts
skipRelease was set to true still, which led some languages to be skipped even when force
also fix release script to properly push generated files on releases
=> fix(scripts): set skipRelease to false

specs/ingestion/paths/transformations/transformationsTry.yml, specs/ingestion/spec.yml
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2537
transformations are not listed in our docs https://api-clients-automation.netlify.app/specs/ingestion#tag/authentications
=> fix(clients): update ingestion transformations description and fix taggroups

.github/workflows/check.yml, .github/workflows/cleanup.yml, scripts/ci/codegen/pushGeneratedCode.ts
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2543
allow the CI to delete branches https://github.com/algolia/api-clients-automation/actions/runs/9743684183/job/26887678022 and https://github.com/algolia/api-clients-automation/actions/runs/9743686082/job/26888122262?pr=3296
also fix @Fluf22 comment that I forgot before merging
=> chore: delete branch on origin

.github/workflows/check.yml, scripts/ci/codegen/pushGeneratedCode.ts, scripts/ci/githubActions/createMatrix.ts
similarly to the previous custom action:
- if no code is generated, put a comment
- if code is generated, add the generated commit hash to the comment
=> chore: CI generated commit hash and no gen comment

.github/workflows/check.yml
We already use algolia-bot everywhere else in this repo, IMO it makes sense to also use it here
=> chore(ci): use algolia-bot for gen comments

specs/search/paths/search/browse.yml
I felt like [this information](https://www.algolia.com/doc/api-reference/api-methods/browse/#method-param-browseparameters) about the behavior of the `browse` operation is important to document.
=> fix(specs): clarify browse parameters

playground/python/app/search.py, templates/python/api.mustache, templates/python/search_helpers.mustache
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2594
- use the object model like other clients
- init when none provided to ease DX
=> fix(python): browse objects

specs/ingestion/common/schemas/source.yml, specs/ingestion/common/schemas/task.yml, specs/ingestion/common/schemas/transformation.yml
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2595
- remove outdated task input types
- update transformation description not required anymore
- add task input docker type
=> fix(specs): ingestion task and transformation

specs/abtesting/common/schemas/Variant.yml, specs/abtesting/paths/abtest.yml, specs/abtesting/paths/abtests.yml, specs/abtesting/paths/stopABTest.yml, specs/analytics/common/parameters.yml, specs/analytics/common/schemas/getTopHits.yml, specs/analytics/common/schemas/getTopSearches.yml, specs/analytics/paths/click/getAddToCartRate.yml, specs/analytics/paths/click/getAverageClickPosition.yml, specs/analytics/paths/click/getClickPositions.yml, specs/analytics/paths/click/getClickThroughRate.yml, specs/analytics/paths/click/getConversionRate.yml, specs/analytics/paths/click/getPurchaseRate.yml, specs/analytics/paths/search/getNoClickRate.yml, specs/analytics/paths/search/getNoResultsRate.yml, specs/analytics/paths/search/getSearchesCount.yml, specs/analytics/paths/search/getSearchesNoClicks.yml, specs/analytics/paths/search/getSearchesNoResults.yml, specs/analytics/paths/search/getTopCountries.yml, specs/analytics/paths/search/getTopFilterAttributes.yml, specs/analytics/paths/search/getTopFilterForAttribute.yml, specs/analytics/paths/search/getTopFiltersNoResults.yml, specs/analytics/paths/search/getTopHits.yml, specs/analytics/paths/search/getTopSearches.yml, specs/analytics/paths/search/getUsersCount.yml, specs/common/parameters.yml, specs/common/responses/rateLimit.yml, specs/insights/paths/deleteUserToken.yml
Remove the last cross references in the specs
=> fix(specs): remove cross-references of analytics

specs/ingestion/common/schemas/common.yml, specs/ingestion/common/schemas/destination.yml, specs/ingestion/paths/transformations/transformations.yml, tests/CTS/requests/ingestion/createDestination.json, tests/CTS/requests/ingestion/listRuns.json, tests/CTS/requests/ingestion/listSources.json, tests/CTS/requests/ingestion/listTransformations.json
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2703
- list allows pagination
- destinations have an optional transformationIDs parameter
=> fix(specs): ingestion destinations and transformations

config/release.config.json, scripts/release/__tests__/sla.test.ts, scripts/release/sla.ts
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2702
easier for the doc to highlight dates that way
=> fix(scripts): add end of support date for patch versions

specs/ingestion/common/schemas/transformation.yml, tests/CTS/requests/ingestion/searchTransformations.json
=> fix(specs): ingestion search endpoint

specs/ingestion/common/schemas/transformation.yml, specs/ingestion/paths/transformations/transformationTryID.yml, specs/ingestion/spec.yml, tests/CTS/requests/ingestion/tryTransformation.json, tests/CTS/requests/ingestion/tryTransformationBeforeUpdate.json
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-2720
=> feat(specs): add authentications to ingestion transformations

.github/workflows/check.yml, specs/insights/paths/deleteUserToken.yml
Port from https://github.com/algolia/doc/pull/9263
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/EEX-1281
- Improve the description of the `deleteUserToken` endpoint of the Insights API.
=> fix(specs): delete user token processing time

clients/algoliasearch-client-javascript/package.json, clients/algoliasearch-client-javascript/yarn.lock
use a maintained tool instead of bundlesize2
=> chore: use bundlesize for JavaScript client

specs/search/paths/objects/objects.yml
Fix a broken link in the Search spec.
[Slack thread](https://algolia.slack.com/archives/C0D3A9E82/p1724174289576419)
=> fix(specs): another wrong link

templates/Bug_report.yml
=> chore: fix the bug report template

clients/algoliasearch-client-javascript/CHANGELOG.md, clients/algoliasearch-client-javascript/packages/algoliasearch/package.json, clients/algoliasearch-client-javascript/packages/client-abtesting/package.json, clients/algoliasearch-client-javascript/packages/client-analytics/package.json, clients/algoliasearch-client-javascript/packages/client-common/package.json, clients/algoliasearch-client-javascript/packages/client-insights/package.json, clients/algoliasearch-client-javascript/packages/client-personalization/package.json, clients/algoliasearch-client-javascript/packages/client-query-suggestions/package.json, clients/algoliasearch-client-javascript/packages/client-search/package.json, clients/algoliasearch-client-javascript/packages/client-usage/package.json, clients/algoliasearch-client-javascript/packages/ingestion/package.json, clients/algoliasearch-client-javascript/packages/monitoring/package.json, clients/algoliasearch-client-javascript/packages/recommend/package.json, clients/algoliasearch-client-javascript/packages/requester-browser-xhr/package.json, clients/algoliasearch-client-javascript/packages/requester-fetch/package.json, clients/algoliasearch-client-javascript/packages/requester-node-http/package.json, clients/algoliasearch-client-javascript/packages/requester-testing/package.json, clients/algoliasearch-client-javascript/yarn.lock, config/clients.config.json, templates/javascript/clients/package.mustache
- ~csharp: 7.3.0 (no commit)~
- ~dart: 1.24.0 (no commit)~
- ~go: 4.3.0 (no commit)~
- ~java: 4.3.0 (no commit)~
- javascript: 5.3.2 -> **`minor` _(e.g. 5.4.0)_**
- ~kotlin: 3.3.0 (no commit)~
- ~php: 4.4.0 (no commit)~
- ~python: 4.4.0 (no commit)~
- ~ruby: 3.3.0 (no commit)~
- ~scala: 2.3.0 (no commit)~
- ~swift: 9.3.0 (no commit)~
_(None)_
=> chore: prepare release 2024-09-10

package.json
I merged main without the [skip-bc] tag, which fails to generate https://github.com/algolia/api-clients-automation/actions/runs/10937891335/job/30364915272
=> chore: trigger main CI [skip-bc]

clients/algoliasearch-client-python/CHANGELOG.md, config/clients.config.json
- ~csharp: 7.4.1 (no commit)~
- ~dart: 1.24.2 (no commit)~
- ~go: 4.3.3 (no commit)~
- ~java: 4.3.3 (no commit)~
- ~javascript: 5.5.2 (no commit)~
- ~kotlin: 3.3.3 (no commit)~
- ~php: 4.4.3 (no commit)~
- python: 4.4.3 -> **`patch` _(e.g. 4.4.4)_**
- ~ruby: 3.3.3 (no commit)~
- ~scala: 2.3.3 (no commit)~
- ~swift: 9.3.3 (no commit)~
_(None)_
=> chore: prepare release 2024-09-19

clients/algoliasearch-client-javascript/package.json, specs/ingestion/common/authenticationParameters.yml, specs/ingestion/common/destinationParameters.yml, specs/ingestion/common/parameters.yml, specs/ingestion/common/sourceParameters.yml, specs/ingestion/common/transformationParameters.yml, specs/ingestion/paths/destinations/destinations.yml, specs/ingestion/paths/transformations/transformations.yml
fix the qp for auth and transfo, and add the new one for destinations.
=> fix(specs): correct query params for ingestion [skip-bc]

specs/ingestion/common/schemas/authentication.yml
add the new auth type for ingestion
=> feat(specs): add secrets authentications to ingestion

specs/ingestion/common/schemas/authentication.yml
the input payload needs to include the secrets shape too
=> fix(specs): add secrets payload for updates

clients/algoliasearch-client-csharp/algoliasearch/Utils/SearchClientExtensions.cs, clients/algoliasearch-client-php/lib/Iterators/RuleIterator.php, clients/algoliasearch-client-php/lib/Iterators/SynonymIterator.php, clients/algoliasearch-client-swift/Sources/Search/Extra/SearchClientExtension.swift, templates/go/search_helpers.mustache, templates/java/api_helpers.mustache, templates/javascript/clients/client/api/helpers.mustache, templates/python/search_helpers.mustache, templates/ruby/search_helpers.mustache, tests/output/csharp/src/ClientExtensionsTests.cs
🎟 JIRA Ticket: [CR-7214]
[CR-7214]: https://algolia.atlassian.net/browse/CR-7214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(clients): update browse iterator

config/versions.history.json, scripts/generate.ts, scripts/release/__tests__/versionsHistory.test.ts, scripts/release/versionsHistory.ts
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3258
the versions (SLA and support) history are now final, we can replace the placeholder naming as well as adding correct dates
=> fix(scripts): update versions history script [skip-bc]

specs/ingestion/paths/tasks/v2/pushTask.yml, tests/CTS/requests/ingestion/pushTask.json, tests/output/javascript/yarn.lock
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3290
adds the new query parameter to the `pushTask` endpoint
=> feat(specs): add `watch` to `pushTask` ingestion

templates/do-not-edit-this-repository.yml
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3316
https://github.com/algolia/algoliasearch-client-javascript/pull/1573 wasn't closed because the trigger only works on non forked repos, this should fix it
=> chore: trigger auto close pr

scripts/ci/codegen/__tests__/CHANGELOG.md, scripts/ci/codegen/__tests__/__snapshots__/createGithubReleases.test.ts.snap, scripts/ci/codegen/__tests__/codegen.test.ts, scripts/ci/codegen/__tests__/createGithubReleases.test.ts, scripts/ci/codegen/createGitHubReleases.ts, scripts/release/__tests__/createReleasePR.test.ts
So that the contributor can appear in the github release and be tagged.
Also add a test to this and found a bug !
=> chore(scripts): add the contrib in the github release

tests/CTS/requests/search/searchSingleIndex.json, tests/CTS/requests/search/setSettings.json, tests/output/javascript/yarn.lock
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3457
For some reason I thought client tests generated guides as well, so i'm adding the request test instead
=> chore: more guides

scripts/ci/codegen/pushToRepository.ts, scripts/ci/codegen/types.ts
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3469
create a guide file for the docs to consume them
=> feat(scripts): spread guides to docs

scripts/ci/codegen/pushToRepository.ts
gh auth login is only required on the ci, also fix the auto merge option
=> chore: only gh auth login for the ci

specs/ingestion/common/schemas/task.yml
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3561
this pr adds the new property to the tasks, named `subscriptionAction`
=> feat(specs): add `subscriptionAction` to ingestion specs

specs/ingestion/common/schemas/common.yml
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-3841
new fields are available
=> fix(specs): updated watchResponse

specs/advanced-personalization/common/schemas/RealtimeUser.yml, specs/advanced-personalization/paths/getRealtimeUser.yml
Fix the current type `RealtimeUserUser` -> `RealtimeUser`
=> fix(specs): fix type in realtime_user

specs/insights/common/schemas/EventAttributes.yml
Clarified the description for `price` and `value`.
🎟 JIRA Ticket: [DOC-1655](https://algolia.atlassian.net/browse/DOC-1655)
- List changes
[DOC-1655]: https://algolia.atlassian.net/browse/DOC-1655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(specs): value/price clarifications in the Insights API

specs/ingestion/common/transformationParameters.yml, specs/ingestion/paths/transformations/transformations.yml, tests/CTS/requests/ingestion/listTransformations.json, tests/output/javascript/yarn.lock
🎟 JIRA Ticket: https://algolia.atlassian.net/browse/DI-4201
reflects the backend addition
=> feat(specs): allow filtering transformations type
